import type { FastifyInstance } from 'fastify';
import { z } from 'zod';
import { audit } from '../../shared/audit.js';

const patientParams=z.object({patientId:z.uuid()});

export async function messageRoutes(app:FastifyInstance){
  app.addHook('preHandler',app.requireAdmin);
  app.get('/',async()=>{const result=await app.db.query(`SELECT p.id AS "patientId",p.name AS "patientName",p.email,p.whatsapp,m.body AS "lastMessage",m.sender_role AS "lastSenderRole",m.created_at AS "lastMessageAt",COALESCE(u.unread,0)::int AS "unreadCount" FROM patients p JOIN LATERAL(SELECT body,sender_role,created_at FROM patient_messages WHERE patient_id=p.id ORDER BY created_at DESC LIMIT 1)m ON true LEFT JOIN LATERAL(SELECT count(*) AS unread FROM patient_messages WHERE patient_id=p.id AND sender_role='PATIENT' AND read_at IS NULL)u ON true WHERE p.active=true ORDER BY COALESCE(u.unread,0) DESC,m.created_at DESC`);return{data:result.rows}});
  app.get('/:patientId',async(request,reply)=>{const{patientId}=patientParams.parse(request.params);const patient=(await app.db.query<{id:string;name:string}>('SELECT id,name FROM patients WHERE id=$1 AND active=true',[patientId])).rows[0];if(!patient)return reply.code(404).send({error:'Paciente não encontrado.'});await app.db.query(`UPDATE patient_messages SET read_at=now() WHERE patient_id=$1 AND sender_role='PATIENT' AND read_at IS NULL`,[patientId]);const messages=await app.db.query(`SELECT id,sender_role AS "senderRole",body,read_at AS "readAt",created_at AS "createdAt" FROM patient_messages WHERE patient_id=$1 ORDER BY created_at`,[patientId]);return{data:{patient,messages:messages.rows}}});
  app.post('/:patientId',async(request,reply)=>{const{patientId}=patientParams.parse(request.params);const{body}=z.object({body:z.string().trim().min(1).max(2000)}).parse(request.body);const patient=(await app.db.query<{id:string}>('SELECT id FROM patients WHERE id=$1 AND active=true',[patientId])).rows[0];if(!patient)return reply.code(404).send({error:'Paciente não encontrado.'});const result=await app.db.query<{id:string}>(`INSERT INTO patient_messages(patient_id,sender_role,body)VALUES($1,'ADMIN',$2) RETURNING id`,[patientId,body]);await app.db.query(`INSERT INTO patient_notifications(patient_id,title,body,kind)VALUES($1,'Nova mensagem da nutricionista','Você recebeu uma resposta no canal de mensagens.','MESSAGE')`,[patientId]);await audit(app.db,'PATIENT_MESSAGE_SENT','patient_message',{actorUserId:request.auth!.userId,entityId:result.rows[0]!.id,metadata:{patientId}});return reply.code(201).send({data:{id:result.rows[0]!.id},message:'Resposta enviada ao paciente.'})});
}
