import type { FastifyInstance } from 'fastify';
import { z } from 'zod';
import { audit } from '../../shared/audit.js';
const patientParams=z.object({patientId:z.uuid()});const itemParams=z.object({id:z.uuid()});
export async function followUpRoutes(app:FastifyInstance){app.addHook('preHandler',app.requireAdmin);
 app.get('/:patientId',async(request,reply)=>{const{patientId}=patientParams.parse(request.params);const patient=(await app.db.query<{id:string;name:string}>('SELECT id,name FROM patients WHERE id=$1 AND active=true',[patientId])).rows[0];if(!patient)return reply.code(404).send({error:'Paciente não encontrado.'});const[diary,goals,measurements]=await Promise.all([
  app.db.query(`SELECT id,to_char(entry_date,'YYYY-MM-DD') AS "entryDate",meal_notes AS "mealNotes",symptoms,hunger,satiety,water_liters::float8 AS "waterLiters",adherence,created_at AS "createdAt" FROM patient_diary_entries WHERE patient_id=$1 ORDER BY entry_date DESC,created_at DESC LIMIT 60`,[patientId]),
  app.db.query(`SELECT id,title,description,to_char(due_date,'YYYY-MM-DD') AS "dueDate",status,created_at AS "createdAt",completed_at AS "completedAt" FROM patient_goals WHERE patient_id=$1 ORDER BY CASE status WHEN 'ACTIVE' THEN 0 WHEN 'COMPLETED' THEN 1 ELSE 2 END,due_date NULLS LAST,created_at DESC`,[patientId]),
  app.db.query(`SELECT id,to_char(measured_at,'YYYY-MM-DD') AS "measuredAt",weight::float8,body_fat::float8 AS "bodyFat",waist::float8,notes,visible_to_patient AS "visibleToPatient" FROM patient_measurements WHERE patient_id=$1 ORDER BY measured_at DESC,created_at DESC`,[patientId])]);return{data:{patient,diary:diary.rows,goals:goals.rows,measurements:measurements.rows}}});
 app.post('/:patientId/goals',async(request,reply)=>{const{patientId}=patientParams.parse(request.params);const b=z.object({title:z.string().trim().min(2).max(160),description:z.string().trim().max(1000).optional(),dueDate:z.iso.date().optional()}).parse(request.body);const r=await app.db.query<{id:string}>(`INSERT INTO patient_goals(patient_id,title,description,due_date,created_by) SELECT $1,$2,$3,$4,$5 WHERE EXISTS(SELECT 1 FROM patients WHERE id=$1 AND active=true) RETURNING id`,[patientId,b.title,b.description||null,b.dueDate||null,request.auth!.userId]);if(!r.rows[0])return reply.code(404).send({error:'Paciente não encontrado.'});await audit(app.db,'PATIENT_GOAL_CREATED','patient_goal',{actorUserId:request.auth!.userId,entityId:r.rows[0].id,metadata:{patientId}});return reply.code(201).send({data:{id:r.rows[0].id}})});
 app.patch('/goals/:id',async(request,reply)=>{const{id}=itemParams.parse(request.params);const{status}=z.object({status:z.enum(['ACTIVE','COMPLETED','CANCELLED'])}).parse(request.body);const r=await app.db.query(`UPDATE patient_goals SET status=$1,completed_at=CASE WHEN $1='COMPLETED' THEN COALESCE(completed_at,now()) ELSE NULL END WHERE id=$2 RETURNING id`,[status,id]);if(!r.rows[0])return reply.code(404).send({error:'Meta não encontrada.'});await audit(app.db,'PATIENT_GOAL_UPDATED','patient_goal',{actorUserId:request.auth!.userId,entityId:id,metadata:{status}});return{message:'Meta atualizada.'}});
 app.post('/:patientId/measurements',async(request,reply)=>{const{patientId}=patientParams.parse(request.params);const b=z.object({measuredAt:z.iso.date(),weight:z.number().positive().max(500).optional(),bodyFat:z.number().min(0).max(100).optional(),waist:z.number().positive().max(400).optional(),notes:z.string().trim().max(1000).optional(),visibleToPatient:z.boolean().default(true)}).refine(v=>v.weight!=null||v.bodyFat!=null||v.waist!=null,{message:'Informe ao menos uma medida.'}).parse(request.body);const r=await app.db.query<{id:string}>(`INSERT INTO patient_measurements(patient_id,measured_at,weight,body_fat,waist,notes,visible_to_patient) SELECT $1,$2,$3,$4,$5,$6,$7 WHERE EXISTS(SELECT 1 FROM patients WHERE id=$1 AND active=true) RETURNING id`,[patientId,b.measuredAt,b.weight??null,b.bodyFat??null,b.waist??null,b.notes||null,b.visibleToPatient]);if(!r.rows[0])return reply.code(404).send({error:'Paciente não encontrado.'});await audit(app.db,'PATIENT_MEASUREMENT_CREATED','patient_measurement',{actorUserId:request.auth!.userId,entityId:r.rows[0].id,metadata:{patientId}});return reply.code(201).send({data:{id:r.rows[0].id}})});
}
