import type{FastifyInstance}from'fastify';import{z}from'zod';import{audit}from'../../shared/audit.js';import{examStorage}from'../../integrations/storage.js';import{randomUUID}from'node:crypto';import{getVapidPublicKey}from'../../shared/push-service.js';
const uuid=z.object({id:z.uuid()});
export async function portalRoutes(app:FastifyInstance){app.addHook('preHandler',app.authenticate);app.addHook('preHandler',async(req,reply)=>{if(req.auth?.role!=='PATIENT'||!req.auth.patientId)return reply.code(403).send({error:'Acesso restrito ao paciente.'})});
 app.get('/checkins',async req=>{const result=await app.db.query(`SELECT id,appointment_id AS "appointmentId",answers,status,submitted_at AS "submittedAt",reviewed_at AS "reviewedAt" FROM preconsult_checkins WHERE patient_id=$1 ORDER BY submitted_at DESC LIMIT 20`,[req.auth!.patientId]);return{data:result.rows}});
 app.post('/checkins',async(req,reply)=>{const body=z.object({appointmentId:z.uuid().optional(),answers:z.object({improvements:z.string().trim().max(1500).optional(),mainDifficulty:z.string().trim().max(1500).optional(),medicationChanges:z.string().trim().max(1500).optional(),newSymptoms:z.string().trim().max(1500).optional(),adherence:z.number().int().min(0).max(10).optional(),examsCompleted:z.string().trim().max(1500).optional(),discussionTopics:z.string().trim().max(1500).optional()})}).parse(req.body);if(body.appointmentId){const appointment=await app.db.query('SELECT id FROM appointments WHERE id=$1 AND patient_id=$2',[body.appointmentId,req.auth!.patientId]);if(!appointment.rows[0])return reply.code(400).send({error:'Consulta não pertence ao paciente autenticado.'})}const result=await app.db.query<{id:string}>(`INSERT INTO preconsult_checkins(patient_id,appointment_id,answers) VALUES($1,$2,$3) ON CONFLICT(appointment_id) WHERE appointment_id IS NOT NULL DO UPDATE SET answers=excluded.answers,status='PENDING_REVIEW',submitted_at=now(),reviewed_at=null,reviewed_by=null RETURNING id`,[req.auth!.patientId,body.appointmentId||null,body.answers]);await audit(app.db,'PRECONSULT_CHECKIN_SUBMITTED','preconsult_checkin',{actorUserId:req.auth!.userId,entityId:result.rows[0]!.id,metadata:{appointmentId:body.appointmentId||null}});return reply.code(201).send({data:{id:result.rows[0]!.id,status:'PENDING_REVIEW'}})});
 app.get('/home',async req=>{const id=req.auth!.patientId!;const [patient,appointments,plans,settings,documents,diary,exams,messages,requests,goals,measurements,notifications,finance,activeEnc]=await Promise.all([
  app.db.query(`SELECT id,name,email,whatsapp,birth_date AS "birthDate",objective,address,emergency_contact AS "emergencyContact",communication_preference AS "communicationPreference" FROM patients WHERE id=$1 AND active=true`,[id]),
  app.db.query(`SELECT a.id,to_char(a.appointment_date,'YYYY-MM-DD') AS "appointmentDate",to_char(a.appointment_time,'HH24:MI') AS "appointmentTime",a.duration_minutes AS "durationMinutes",a.appointment_type AS "appointmentType",CASE WHEN e.status='COMPLETED' THEN 'COMPLETED' ELSE a.status END AS status,a.patient_response AS "patientResponse",a.patient_response_note AS "patientResponseNote",a.notes,CASE WHEN (e.status IS NULL OR e.status<>'COMPLETED') AND a.status IN('CONFIRMED','WAITING','IN_PROGRESS') AND NOT EXISTS(SELECT 1 FROM teleconsultation_sessions s WHERE s.source_id=a.id AND s.ended_at IS NOT NULL) THEN '/portal/video/'||a.id::text END AS "meetingUrl" FROM appointments a LEFT JOIN clinical_encounters e ON e.appointment_id=a.id WHERE a.patient_id=$1 ORDER BY CASE WHEN a.appointment_date>=current_date AND a.status IN('CONFIRMED','WAITING','IN_PROGRESS') AND (e.status IS NULL OR e.status<>'COMPLETED') THEN 0 ELSE 1 END,CASE WHEN a.appointment_date>=current_date AND a.status IN('CONFIRMED','WAITING','IN_PROGRESS') AND (e.status IS NULL OR e.status<>'COMPLETED') THEN a.appointment_date END ASC,CASE WHEN a.appointment_date>=current_date AND a.status IN('CONFIRMED','WAITING','IN_PROGRESS') AND (e.status IS NULL OR e.status<>'COMPLETED') THEN a.appointment_time END ASC,a.appointment_date DESC,a.appointment_time DESC LIMIT 100`,[id]),
  app.db.query(`SELECT id,title,CASE WHEN status='ARCHIVED' THEN 'Plano anterior · '||COALESCE(objective,'Histórico nutricional') ELSE COALESCE(objective,'Plano vigente') END AS objective,status,content,published_at AS "publishedAt",updated_at AS "updatedAt" FROM meal_plans WHERE patient_id=$1 AND status IN('PUBLISHED','ARCHIVED') ORDER BY CASE WHEN status='PUBLISHED' THEN 0 ELSE 1 END,updated_at DESC`,[id]),app.db.query(`SELECT clinic_name AS "clinicName",professional_name AS "professionalName",specialty,logo_url AS "logoUrl" FROM clinic_settings WHERE singleton=true`),
  app.db.query(`SELECT id,document_number AS "documentNumber",title,issued_at AS "issuedAt" FROM clinical_documents WHERE patient_id=$1 AND status='ISSUED' AND available_to_patient=true ORDER BY issued_at DESC`,[id]),
  app.db.query(`SELECT id,to_char(entry_date,'YYYY-MM-DD') AS "entryDate",meal_notes AS "mealNotes",symptoms,hunger,satiety,water_liters::float8 AS "waterLiters",adherence,created_at AS "createdAt" FROM patient_diary_entries WHERE patient_id=$1 ORDER BY entry_date DESC,created_at DESC LIMIT 30`,[id]),
  app.db.query(`SELECT id,title,exam_date AS "examDate",file_path AS "filePath",file_url AS "legacyUrl",mime_type AS "mimeType",file_size AS "fileSize",notes,status,created_at AS "createdAt" FROM patient_exam_uploads WHERE patient_id=$1 ORDER BY created_at DESC`,[id]),
  app.db.query(`SELECT id,sender_role AS "senderRole",body,read_at AS "readAt",created_at AS "createdAt" FROM patient_messages WHERE patient_id=$1 ORDER BY created_at`,[id]),
  app.db.query(`SELECT id,to_char(preferred_date,'YYYY-MM-DD') AS "preferredDate",preferred_period AS "preferredPeriod",appointment_type AS "appointmentType",notes,status,created_at AS "createdAt" FROM appointment_requests WHERE patient_id=$1 ORDER BY created_at DESC`,[id]),
  app.db.query(`SELECT id,title,description,due_date AS "dueDate",status FROM patient_goals WHERE patient_id=$1 AND status<>'CANCELLED' ORDER BY status,due_date NULLS LAST`,[id]),
  app.db.query(`SELECT id,measured_at AS "measuredAt",weight::float8,body_fat::float8 AS "bodyFat",waist::float8,neck::float8,notes FROM patient_measurements WHERE patient_id=$1 AND visible_to_patient ORDER BY measured_at`,[id]),
  app.db.query(`SELECT id,title,body,kind,priority,status,action_url AS "actionUrl",read_at AS "readAt",resolved_at AS "resolvedAt",created_at AS "createdAt" FROM patient_notifications WHERE patient_id=$1 AND status='ACTIVE' AND (expires_at IS NULL OR expires_at>now()) ORDER BY CASE WHEN read_at IS NULL THEN 0 ELSE 1 END,created_at DESC LIMIT 30`,[id]),
  app.db.query(`SELECT id,description,amount::float8,due_date AS "dueDate",paid_at AS "paidAt",payment_method AS "paymentMethod",status FROM financial_transactions WHERE patient_id=$1 ORDER BY due_date DESC`,[id]),
  app.db.query(`SELECT e.id, e.appointment_id AS "appointmentId", e.video_room_token AS "videoRoomToken", COALESCE(to_char(a.appointment_time, 'HH24:MI'), to_char(e.started_at AT TIME ZONE 'America/Sao_Paulo', 'HH24:MI')) AS "time", COALESCE(a.appointment_type, 'Consulta Nutricional Online') AS "type", '/portal/video/' || COALESCE(a.id, e.id)::text AS "meetingUrl", e.started_at AS "startedAt" FROM clinical_encounters e LEFT JOIN appointments a ON a.id = e.appointment_id WHERE e.patient_id = $1 AND e.status = 'IN_PROGRESS' AND NOT EXISTS(SELECT 1 FROM teleconsultation_sessions s WHERE s.source_id IN(e.id,e.appointment_id) AND s.ended_at IS NOT NULL) ORDER BY e.started_at DESC LIMIT 1`, [id])]);await audit(app.db,'PATIENT_PORTAL_VIEWED','patient',{actorUserId:req.auth!.userId,entityId:id});return{data:{patient:patient.rows[0],appointments:appointments.rows,plans:plans.rows,planHistory:plans.rows.filter(plan=>plan.status==='ARCHIVED'),documents:documents.rows,settings:settings.rows[0],diary:diary.rows,exams:exams.rows,messages:messages.rows,requests:requests.rows,goals:goals.rows,measurements:measurements.rows,notifications:notifications.rows,finance:finance.rows,activeConsultation:activeEnc.rows[0]||null}}});
 app.post('/profile',async req=>{const b=z.object({whatsapp:z.string().trim().max(30).optional(),address:z.string().trim().max(300).optional(),emergencyContact:z.string().trim().max(200).optional(),communicationPreference:z.enum(['EMAIL','WHATSAPP','BOTH'])}).parse(req.body);await app.db.query(`UPDATE patients SET whatsapp=$1,address=$2,emergency_contact=$3,communication_preference=$4,updated_at=now() WHERE id=$5`,[b.whatsapp||null,b.address||null,b.emergencyContact||null,b.communicationPreference,req.auth!.patientId]);return{message:'Perfil atualizado.'}});
 app.post('/diary',async(req,reply)=>{const b=z.object({entryDate:z.iso.date(),mealNotes:z.string().max(2000).optional(),symptoms:z.string().max(1000).optional(),hunger:z.number().int().min(0).max(10).optional(),satiety:z.number().int().min(0).max(10).optional(),waterLiters:z.number().min(0).max(20).optional(),adherence:z.number().int().min(0).max(100).optional()}).parse(req.body);await app.db.query(`INSERT INTO patient_diary_entries(patient_id,entry_date,meal_notes,symptoms,hunger,satiety,water_liters,adherence)VALUES($1,$2,$3,$4,$5,$6,$7,$8)`,[req.auth!.patientId,b.entryDate,b.mealNotes||null,b.symptoms||null,b.hunger??null,b.satiety??null,b.waterLiters??null,b.adherence??null]);return reply.code(201).send({message:'Diário registrado.'})});
 app.post('/exams/upload-url',async(req,reply)=>{const b=z.object({fileName:z.string().trim().min(1).max(180),mimeType:z.enum(['application/pdf','image/jpeg','image/png','image/webp']),size:z.number().int().positive().max(10*1024*1024)}).parse(req.body);if(!app.env.SUPABASE_URL||!app.env.SUPABASE_SERVICE_ROLE_KEY||!app.env.SUPABASE_EXAMS_BUCKET)return reply.code(503).send({error:'O envio de exames está temporariamente indisponível. O armazenamento privado precisa ser configurado pelo consultório.'});const ext=({ 'application/pdf':'pdf','image/jpeg':'jpg','image/png':'png','image/webp':'webp'}as Record<string,string>)[b.mimeType];const path=`${req.auth!.patientId}/${randomUUID()}.${ext}`;const{data,error}=await examStorage(app.env).createSignedUploadUrl(path);if(error){app.log.error({storageStatus:error.statusCode,storageCode:'code'in error?error.code:undefined},'Falha ao criar URL privada para exame');return reply.code(502).send({error:'Não foi possível preparar o armazenamento do exame. Tente novamente em instantes.'})}return{data:{path,token:data.token,signedUrl:data.signedUrl}}});
 app.post('/exams',async(req,reply)=>{const b=z.object({title:z.string().trim().min(2).max(160),examDate:z.iso.date().optional(),filePath:z.string().max(500),mimeType:z.enum(['application/pdf','image/jpeg','image/png','image/webp']),fileSize:z.number().int().positive().max(10*1024*1024),notes:z.string().max(1000).optional()}).parse(req.body);if(!b.filePath.startsWith(`${req.auth!.patientId}/`))return reply.code(403).send({error:'Arquivo inválido.'});await app.db.query(`INSERT INTO patient_exam_uploads(patient_id,title,exam_date,file_path,mime_type,file_size,notes)VALUES($1,$2,$3,$4,$5,$6,$7)`,[req.auth!.patientId,b.title,b.examDate||null,b.filePath,b.mimeType,b.fileSize,b.notes||null]);return reply.code(201).send({message:'Exame enviado com segurança.'})});
 app.get('/exams/:id/url',async(req,reply)=>{const{id}=uuid.parse(req.params);const r=await app.db.query<{file_path:string|null;file_url:string|null}>('SELECT file_path,file_url FROM patient_exam_uploads WHERE id=$1 AND patient_id=$2',[id,req.auth!.patientId]);const row=r.rows[0];if(!row)return reply.code(404).send({error:'Exame não encontrado.'});if(row.file_path){const{data,error}=await examStorage(app.env).createSignedUrl(row.file_path,300);if(error)throw error;return{data:{url:data.signedUrl}}}return{data:{url:row.file_url}}});
 app.post('/messages',async(req,reply)=>{const{body}=z.object({body:z.string().trim().min(1).max(2000)}).parse(req.body);await app.db.query(`INSERT INTO patient_messages(patient_id,sender_role,body)VALUES($1,'PATIENT',$2)`,[req.auth!.patientId,body]);return reply.code(201).send({message:'Mensagem enviada.'})});
 app.patch('/messages/read',async(req,reply)=>{await app.db.query(`UPDATE patient_messages SET read_at=now() WHERE patient_id=$1 AND sender_role='ADMIN' AND read_at IS NULL`,[req.auth!.patientId]);return reply.code(204).send()});
 app.post('/appointment-requests',async(req,reply)=>{const b=z.object({preferredDate:z.iso.date(),preferredPeriod:z.enum(['MORNING','AFTERNOON','EVENING']),appointmentType:z.string().trim().min(2).max(100),notes:z.string().max(1000).optional()}).parse(req.body);const todayIso=new Date().toISOString().slice(0,10);if(b.preferredDate<todayIso)return reply.code(400).send({error:'A data da consulta deve ser igual ou posterior à data de hoje.'});await app.db.query(`INSERT INTO appointment_requests(patient_id,preferred_date,preferred_period,appointment_type,notes)VALUES($1,$2,$3,$4,$5)`,[req.auth!.patientId,b.preferredDate,b.preferredPeriod,b.appointmentType,b.notes||null]);return reply.code(201).send({message:'Solicitação enviada.'})});
 app.patch('/goals/:id',async(req,reply)=>{const{id}=uuid.parse(req.params);const{completed}=z.object({completed:z.boolean()}).parse(req.body);const r=await app.db.query(`UPDATE patient_goals SET status=$1,completed_at=CASE WHEN $1='COMPLETED' THEN now() ELSE NULL END WHERE id=$2 AND patient_id=$3 RETURNING id`,[completed?'COMPLETED':'ACTIVE',id,req.auth!.patientId]);return r.rows[0]?{message:'Meta atualizada.'}:reply.code(404).send({error:'Meta não encontrada.'})});
 app.patch('/notifications/read-all',async(req,reply)=>{await app.db.query(`UPDATE patient_notifications SET read_at=COALESCE(read_at,now()) WHERE patient_id=$1 AND status<>'ARCHIVED'`,[req.auth!.patientId]);return reply.code(204).send()});
 app.patch('/notifications/:id/read',async(req,reply)=>{const{id}=uuid.parse(req.params);const r=await app.db.query(`UPDATE patient_notifications SET read_at=COALESCE(read_at,now()) WHERE id=$1 AND patient_id=$2 AND status<>'ARCHIVED' RETURNING id`,[id,req.auth!.patientId]);return r.rows[0]?reply.code(204).send():reply.code(404).send({error:'Notificação não encontrada.'})});
 app.patch('/notifications/:id/archive',async(req,reply)=>{const{id}=uuid.parse(req.params);const r=await app.db.query(`UPDATE patient_notifications SET status='ARCHIVED',archived_at=now(),read_at=COALESCE(read_at,now()) WHERE id=$1 AND patient_id=$2 RETURNING id`,[id,req.auth!.patientId]);return r.rows[0]?reply.code(204).send():reply.code(404).send({error:'Notificação não encontrada.'})});
 app.get('/plans/:id',async(req,reply)=>{const{id}=uuid.parse(req.params);const r=await app.db.query(`SELECT id,title,objective,status,content,published_at AS "publishedAt",updated_at AS "updatedAt" FROM meal_plans WHERE id=$1 AND patient_id=$2 AND status IN('PUBLISHED','ARCHIVED')`,[id,req.auth!.patientId]);return r.rows[0]?{data:r.rows[0]}:reply.code(404).send({error:'Plano não encontrado.'})});
 app.get('/documents/:id',async(req,reply)=>{const{id}=uuid.parse(req.params);const r=await app.db.query(`SELECT d.snapshot,d.document_number AS "documentNumber",d.type,d.title,d.issued_at AS "issuedAt",s.clinic_name AS "clinicName",s.professional_name AS "professionalName",s.crn,s.specialty,s.document_footer AS "documentFooter" FROM clinical_documents d JOIN patients p ON p.id=d.patient_id LEFT JOIN clinic_settings s ON s.singleton=true WHERE d.id=$1 AND d.patient_id=$2 AND d.status='ISSUED' AND d.available_to_patient=true`,[id,req.auth!.patientId]);return r.rows[0]?{data:r.rows[0]}:reply.code(404).send({error:'Documento não encontrado ou não disponibilizado.'})});
 app.get('/push/vapid-key',async()=>{return{data:{publicKey:getVapidPublicKey()}}});
 app.post('/push/subscribe',async(req,reply)=>{const b=z.object({endpoint:z.string().url().max(2000),keys:z.object({p256dh:z.string().min(1).max(500),auth:z.string().min(1).max(500)}),userAgent:z.string().max(500).optional()}).parse(req.body);await app.db.query(`INSERT INTO push_subscriptions(user_id,patient_id,endpoint,p256dh,auth,user_agent,updated_at) VALUES($1,$2,$3,$4,$5,$6,now()) ON CONFLICT(endpoint) DO UPDATE SET patient_id=EXCLUDED.patient_id,p256dh=EXCLUDED.p256dh,auth=EXCLUDED.auth,user_agent=EXCLUDED.user_agent,updated_at=now()`,[req.auth!.userId||null,req.auth!.patientId,b.endpoint,b.keys.p256dh,b.keys.auth,b.userAgent||null]);return reply.code(201).send({message:'Notificações push ativadas com sucesso.'})});
 app.post('/push/unsubscribe',async(req,reply)=>{const b=z.object({endpoint:z.string().url().max(2000)}).parse(req.body);await app.db.query(`DELETE FROM push_subscriptions WHERE endpoint=$1 AND patient_id=$2`,[b.endpoint,req.auth!.patientId]);return reply.code(200).send({message:'Notificações push desativadas.'})})}
