import type{FastifyInstance}from'fastify';import{z}from'zod';import{audit}from'../../shared/audit.js';
const uuid=z.object({id:z.uuid()});
export async function portalRoutes(app:FastifyInstance){app.addHook('preHandler',app.authenticate);app.addHook('preHandler',async(req,reply)=>{if(req.auth?.role!=='PATIENT'||!req.auth.patientId)return reply.code(403).send({error:'Acesso restrito ao paciente.'})});
 app.get('/home',async req=>{const id=req.auth!.patientId!;const [patient,appointments,plans,settings,documents,diary,exams,messages,requests,goals,measurements,notifications,finance]=await Promise.all([
  app.db.query(`SELECT id,name,email,whatsapp,birth_date AS "birthDate",objective,address,emergency_contact AS "emergencyContact",communication_preference AS "communicationPreference" FROM patients WHERE id=$1 AND active=true`,[id]),
  app.db.query(`SELECT id,appointment_date AS "appointmentDate",appointment_time AS "appointmentTime",duration_minutes AS "durationMinutes",appointment_type AS "appointmentType",status,CASE WHEN status IN('CONFIRMED','WAITING','IN_PROGRESS') THEN '/portal/video/'||id::text END AS "meetingUrl" FROM appointments WHERE patient_id=$1 ORDER BY appointment_date DESC,appointment_time DESC LIMIT 30`,[id]),
  app.db.query(`SELECT id,title,objective,content,updated_at AS "updatedAt" FROM meal_plans WHERE patient_id=$1 AND status='PUBLISHED' ORDER BY updated_at DESC`,[id]),app.db.query(`SELECT clinic_name AS "clinicName",professional_name AS "professionalName",logo_url AS "logoUrl" FROM clinic_settings WHERE singleton=true`),
  app.db.query(`SELECT id,document_number AS "documentNumber",title,issued_at AS "issuedAt" FROM clinical_documents WHERE patient_id=$1 AND status='ISSUED' AND available_to_patient=true ORDER BY issued_at DESC`,[id]),
  app.db.query(`SELECT id,entry_date AS "entryDate",meal_notes AS "mealNotes",symptoms,hunger,satiety,water_liters::float8 AS "waterLiters",adherence,created_at AS "createdAt" FROM patient_diary_entries WHERE patient_id=$1 ORDER BY entry_date DESC,created_at DESC LIMIT 30`,[id]),
  app.db.query(`SELECT id,title,exam_date AS "examDate",file_url AS "fileUrl",notes,status,created_at AS "createdAt" FROM patient_exam_uploads WHERE patient_id=$1 ORDER BY created_at DESC`,[id]),
  app.db.query(`SELECT id,sender_role AS "senderRole",body,read_at AS "readAt",created_at AS "createdAt" FROM patient_messages WHERE patient_id=$1 ORDER BY created_at`,[id]),
  app.db.query(`SELECT id,preferred_date AS "preferredDate",preferred_period AS "preferredPeriod",appointment_type AS "appointmentType",notes,status,created_at AS "createdAt" FROM appointment_requests WHERE patient_id=$1 ORDER BY created_at DESC`,[id]),
  app.db.query(`SELECT id,title,description,due_date AS "dueDate",status FROM patient_goals WHERE patient_id=$1 AND status<>'CANCELLED' ORDER BY status,due_date NULLS LAST`,[id]),
  app.db.query(`SELECT id,measured_at AS "measuredAt",weight::float8,body_fat::float8 AS "bodyFat",waist::float8 FROM patient_measurements WHERE patient_id=$1 AND visible_to_patient ORDER BY measured_at`,[id]),
  app.db.query(`SELECT id,title,body,kind,read_at AS "readAt",created_at AS "createdAt" FROM patient_notifications WHERE patient_id=$1 ORDER BY created_at DESC LIMIT 30`,[id]),
  app.db.query(`SELECT id,description,amount::float8,due_date AS "dueDate",paid_at AS "paidAt",payment_method AS "paymentMethod",status FROM financial_transactions WHERE patient_id=$1 ORDER BY due_date DESC`,[id])]);await audit(app.db,'PATIENT_PORTAL_VIEWED','patient',{actorUserId:req.auth!.userId,entityId:id});return{data:{patient:patient.rows[0],appointments:appointments.rows,plans:plans.rows,documents:documents.rows,settings:settings.rows[0],diary:diary.rows,exams:exams.rows,messages:messages.rows,requests:requests.rows,goals:goals.rows,measurements:measurements.rows,notifications:notifications.rows,finance:finance.rows}}});
 app.post('/profile',async req=>{const b=z.object({whatsapp:z.string().trim().max(30).optional(),address:z.string().trim().max(300).optional(),emergencyContact:z.string().trim().max(200).optional(),communicationPreference:z.enum(['EMAIL','WHATSAPP','BOTH'])}).parse(req.body);await app.db.query(`UPDATE patients SET whatsapp=$1,address=$2,emergency_contact=$3,communication_preference=$4,updated_at=now() WHERE id=$5`,[b.whatsapp||null,b.address||null,b.emergencyContact||null,b.communicationPreference,req.auth!.patientId]);return{message:'Perfil atualizado.'}});
 app.post('/diary',async(req,reply)=>{const b=z.object({entryDate:z.iso.date(),mealNotes:z.string().max(2000).optional(),symptoms:z.string().max(1000).optional(),hunger:z.number().int().min(0).max(10).optional(),satiety:z.number().int().min(0).max(10).optional(),waterLiters:z.number().min(0).max(20).optional(),adherence:z.number().int().min(0).max(100).optional()}).parse(req.body);await app.db.query(`INSERT INTO patient_diary_entries(patient_id,entry_date,meal_notes,symptoms,hunger,satiety,water_liters,adherence)VALUES($1,$2,$3,$4,$5,$6,$7,$8)`,[req.auth!.patientId,b.entryDate,b.mealNotes||null,b.symptoms||null,b.hunger??null,b.satiety??null,b.waterLiters??null,b.adherence??null]);return reply.code(201).send({message:'Diário registrado.'})});
 app.post('/exams',async(req,reply)=>{const b=z.object({title:z.string().trim().min(2).max(160),examDate:z.iso.date().optional(),fileUrl:z.url().max(1500),notes:z.string().max(1000).optional()}).parse(req.body);await app.db.query(`INSERT INTO patient_exam_uploads(patient_id,title,exam_date,file_url,notes)VALUES($1,$2,$3,$4,$5)`,[req.auth!.patientId,b.title,b.examDate||null,b.fileUrl,b.notes||null]);return reply.code(201).send({message:'Exame enviado.'})});
 app.post('/messages',async(req,reply)=>{const{body}=z.object({body:z.string().trim().min(1).max(2000)}).parse(req.body);await app.db.query(`INSERT INTO patient_messages(patient_id,sender_role,body)VALUES($1,'PATIENT',$2)`,[req.auth!.patientId,body]);return reply.code(201).send({message:'Mensagem enviada.'})});
 app.post('/appointment-requests',async(req,reply)=>{const b=z.object({preferredDate:z.iso.date(),preferredPeriod:z.enum(['MORNING','AFTERNOON','EVENING']),appointmentType:z.string().trim().min(2).max(100),notes:z.string().max(1000).optional()}).parse(req.body);await app.db.query(`INSERT INTO appointment_requests(patient_id,preferred_date,preferred_period,appointment_type,notes)VALUES($1,$2,$3,$4,$5)`,[req.auth!.patientId,b.preferredDate,b.preferredPeriod,b.appointmentType,b.notes||null]);return reply.code(201).send({message:'Solicitação enviada.'})});
 app.patch('/goals/:id',async(req,reply)=>{const{id}=uuid.parse(req.params);const{completed}=z.object({completed:z.boolean()}).parse(req.body);const r=await app.db.query(`UPDATE patient_goals SET status=$1,completed_at=CASE WHEN $1='COMPLETED' THEN now() ELSE NULL END WHERE id=$2 AND patient_id=$3 RETURNING id`,[completed?'COMPLETED':'ACTIVE',id,req.auth!.patientId]);return r.rows[0]?{message:'Meta atualizada.'}:reply.code(404).send({error:'Meta não encontrada.'})});
 app.patch('/notifications/:id/read',async(req,reply)=>{const{id}=uuid.parse(req.params);await app.db.query(`UPDATE patient_notifications SET read_at=now() WHERE id=$1 AND patient_id=$2`,[id,req.auth!.patientId]);return reply.code(204).send()});
 app.get('/plans/:id',async(req,reply)=>{const{id}=uuid.parse(req.params);const r=await app.db.query(`SELECT id,title,objective,content,updated_at AS "updatedAt" FROM meal_plans WHERE id=$1 AND patient_id=$2 AND status='PUBLISHED'`,[id,req.auth!.patientId]);return r.rows[0]?{data:r.rows[0]}:reply.code(404).send({error:'Plano não encontrado.'})});
 app.get('/documents/:id',async(req,reply)=>{const{id}=uuid.parse(req.params);const r=await app.db.query(`SELECT d.snapshot,d.document_number AS "documentNumber",d.type,d.title,d.issued_at AS "issuedAt",s.clinic_name AS "clinicName",s.professional_name AS "professionalName",s.crn,s.specialty,s.document_footer AS "documentFooter" FROM clinical_documents d JOIN patients p ON p.id=d.patient_id LEFT JOIN clinic_settings s ON s.singleton=true WHERE d.id=$1 AND d.patient_id=$2 AND d.status='ISSUED' AND d.available_to_patient=true`,[id,req.auth!.patientId]);return r.rows[0]?{data:r.rows[0]}:reply.code(404).send({error:'Documento não encontrado ou não disponibilizado.'})})}
