import { Plus, Save, Trash2 } from 'lucide-react';
import { useEffect, useState } from 'react';
import { api } from '../lib/api';

export type Lab={id?:string;examDate?:string;marker:string;value:string;unit?:string;referenceValue?:string;status?:string;observation?:string};
export type Supplement={id?:string;name:string;dosage?:string;posology?:string;pharmaceuticalForm?:string;observation?:string};

export function LabsList({encounterId,initial,locked,reload}:{encounterId:string;initial:Lab[];locked:boolean;reload:()=>void}){
 const[items,setItems]=useState(initial);const[busy,setBusy]=useState(false);const[notice,setNotice]=useState('');useEffect(()=>setItems(initial),[initial]);
 const change=(i:number,key:keyof Lab,value:string)=>setItems(all=>all.map((item,index)=>index===i?{...item,[key]:value}:item));
 async function save(){setBusy(true);setNotice('');try{await api(`/api/encounters/${encounterId}/labs`,{method:'PUT',body:JSON.stringify({items:items.map(({id:_,...item})=>item)})});setNotice('Exames salvos.');reload()}catch(c){setNotice(c instanceof Error?c.message:'Erro ao salvar.')}finally{setBusy(false)}}
 return <Editor title="Marcadores laboratoriais" add={()=>setItems(v=>[...v,{marker:'',value:''}])} save={save} busy={busy} locked={locked} notice={notice}>{items.map((item,i)=><article className="clinical-list-row" key={item.id||i}><div className="clinical-list-fields labs"><label>Data<input type="date" value={item.examDate||''} onChange={e=>change(i,'examDate',e.target.value)}/></label><label>Marcador<input value={item.marker} onChange={e=>change(i,'marker',e.target.value)} placeholder="Glicemia em jejum"/></label><label>Resultado<input value={item.value} onChange={e=>change(i,'value',e.target.value)}/></label><label>Unidade<input value={item.unit||''} onChange={e=>change(i,'unit',e.target.value)} placeholder="mg/dL"/></label><label>Referência<input value={item.referenceValue||''} onChange={e=>change(i,'referenceValue',e.target.value)}/></label><label>Status<select value={item.status||''} onChange={e=>change(i,'status',e.target.value)}><option value="">Selecione</option><option>Dentro da referência</option><option>Atenção</option><option>Alterado</option></select></label><label className="wide">Observação<input value={item.observation||''} onChange={e=>change(i,'observation',e.target.value)}/></label></div><button className="icon-button danger" onClick={()=>setItems(v=>v.filter((_,index)=>index!==i))} disabled={locked}><Trash2 size={17}/></button></article>)}</Editor>
}

export function SupplementsList({encounterId,initial,locked,reload}:{encounterId:string;initial:Supplement[];locked:boolean;reload:()=>void}){
 const[items,setItems]=useState(initial);const[busy,setBusy]=useState(false);const[notice,setNotice]=useState('');useEffect(()=>setItems(initial),[initial]);
 const change=(i:number,key:keyof Supplement,value:string)=>setItems(all=>all.map((item,index)=>index===i?{...item,[key]:value}:item));
 async function save(){setBusy(true);setNotice('');try{await api(`/api/encounters/${encounterId}/supplements`,{method:'PUT',body:JSON.stringify({items:items.map(({id:_,...item})=>item)})});setNotice('Prescrição salva.');reload()}catch(c){setNotice(c instanceof Error?c.message:'Erro ao salvar.')}finally{setBusy(false)}}
 return <Editor title="Prescrição estruturada" add={()=>setItems(v=>[...v,{name:'',pharmaceuticalForm:'Cápsula'}])} save={save} busy={busy} locked={locked} notice={notice}>{items.map((item,i)=><article className="clinical-list-row" key={item.id||i}><div className="clinical-list-fields supplements"><label>Suplemento<input value={item.name} onChange={e=>change(i,'name',e.target.value)} placeholder="Vitamina D3"/></label><label>Dose<input value={item.dosage||''} onChange={e=>change(i,'dosage',e.target.value)} placeholder="2.000 UI"/></label><label>Forma<select value={item.pharmaceuticalForm||''} onChange={e=>change(i,'pharmaceuticalForm',e.target.value)}><option>Cápsula</option><option>Comprimido</option><option>Pó</option><option>Líquido</option><option>Gotas</option><option>Sachê</option></select></label><label className="wide">Posologia<input value={item.posology||''} onChange={e=>change(i,'posology',e.target.value)} placeholder="Uma vez ao dia após o almoço"/></label><label className="wide">Observação<input value={item.observation||''} onChange={e=>change(i,'observation',e.target.value)}/></label></div><button className="icon-button danger" onClick={()=>setItems(v=>v.filter((_,index)=>index!==i))} disabled={locked}><Trash2 size={17}/></button></article>)}</Editor>
}

function Editor({title,add,save,busy,locked,notice,children}:{title:string;add:()=>void;save:()=>void;busy:boolean;locked:boolean;notice:string;children:React.ReactNode}){return <div className="clinical-list-editor"><header><div><h3>{title}</h3><p>Adicione, edite ou remova cada registro separadamente.</p></div><button className="secondary-button" onClick={add} disabled={locked}><Plus size={16}/> Adicionar</button></header><div className="clinical-list-items">{children||<div className="empty-state compact"><strong>Nenhum item registrado</strong></div>}</div>{notice&&<div className="form-success">{notice}</div>}<button className="primary-button" onClick={save} disabled={busy||locked}><Save size={16}/>{busy?'Salvando...':'Salvar lista'}</button></div>}
