import { useCallback, useEffect, useRef, useState, type FormEvent } from 'react';
import { AlertTriangle, Check, CheckCircle2, Cloud, ExternalLink, Globe2, Lightbulb, Link2Off, LoaderCircle, PencilLine, RefreshCw, ShieldAlert } from 'lucide-react';
import { vercelPlatformApi, type VercelIntegration } from '../../lib/vercelPlatformApi';

function projectSlug(value: string) { return value.normalize('NFD').replace(/[\u0300-\u036f]/g, '').toLowerCase().trim().replace(/[^a-z0-9]+/g, '-').replace(/^-+|-+$/g, '').slice(0, 90) || 'minha-clinica'; }
type Props = { tenantId: string; clinicName?: string; currentProjectName?: string; onProjectReady?: (projectName: string) => Promise<void> };

export function VercelProvisioningPanel({ tenantId, clinicName = 'minha-clinica', currentProjectName = '', onProjectReady }: Props) {
  const [state, setState] = useState<VercelIntegration | null>(null), [loading, setLoading] = useState(true), [busy, setBusy] = useState(''), [error, setError] = useState('');
  const [name, setName] = useState(currentProjectName || projectSlug(clinicName)), [verified, setVerified] = useState(false), [feedback, setFeedback] = useState('');
  const popupRef = useRef<Window | null>(null), oauthRef = useRef<{ state: string; origin: string } | null>(null), timerRef = useRef<number | null>(null);
  const load = useCallback(async () => { setLoading(true); try { const next = await vercelPlatformApi.get(tenantId); setState(next); if (next.projectName) setName(next.projectName); } catch (cause) { setError(cause instanceof Error ? cause.message : 'Falha ao consultar a hospedagem.'); } finally { setLoading(false); } }, [tenantId]);
  const finishOauth = useCallback((message?: string) => { if (timerRef.current !== null) window.clearInterval(timerRef.current); timerRef.current = null; popupRef.current?.close(); popupRef.current = null; oauthRef.current = null; setBusy(''); if (message) setError(message); void load(); }, [load]);
  useEffect(() => { void load(); }, [load]);
  useEffect(() => { const receive = (event: MessageEvent) => { const expected = oauthRef.current, popup = popupRef.current, data = event.data; if (!expected || !popup || event.source !== popup || event.origin !== expected.origin || !data || data.type !== 'nutri:vercel-oauth' || data.state !== expected.state) return; if (data.status === 'success' && data.tenantId === tenantId) finishOauth(); else finishOauth('A autorização não foi concluída. Abra novamente e confirme o acesso.'); }; window.addEventListener('message', receive); return () => { window.removeEventListener('message', receive); if (timerRef.current !== null) window.clearInterval(timerRef.current); popupRef.current?.close(); }; }, [finishOauth, tenantId]);
  async function run(key: string, action: () => Promise<void>, reload = true) { setBusy(key); setError(''); try { await action(); if (reload) await load(); } catch (cause) { setError(cause instanceof Error ? cause.message : 'Não foi possível concluir esta ação.'); } finally { setBusy(''); } }
  async function connect() { setBusy('connect'); setError(''); try { const { authorizationUrl } = await vercelPlatformApi.connect(tenantId), url = new URL(authorizationUrl), stateToken = url.searchParams.get('state'), redirect = url.searchParams.get('redirect_uri'), origin = redirect ? new URL(redirect).origin : window.location.origin; if (!stateToken && url.origin !== window.location.origin) throw new Error('A autorização retornou sem a verificação de segurança.'); const popup = window.open(authorizationUrl, 'vercel-connect', 'popup,width=600,height=760'); if (!popup) throw new Error('Seu navegador bloqueou a janela. Permita pop-ups para este site e tente novamente.'); popupRef.current = popup; oauthRef.current = { state: stateToken || 'mock', origin }; timerRef.current = window.setInterval(() => { if (popup.closed) finishOauth(); }, 500); } catch (cause) { finishOauth(cause instanceof Error ? cause.message : 'Não foi possível abrir a autorização.'); } }
  async function verify(event: FormEvent) { event.preventDefault(); setBusy('verify'); setFeedback(''); setError(''); try { const result = await vercelPlatformApi.verifyName(tenantId, name); setName(result.normalizedName); setVerified(result.available); setFeedback(result.available ? 'Endereço disponível. Você já pode criar o espaço da clínica.' : result.message || 'Esse endereço já está em uso. Experimente uma das sugestões abaixo.'); } catch (cause) { setFeedback(cause instanceof Error ? cause.message : 'Não foi possível verificar o endereço.'); } finally { setBusy(''); } }
  async function createAndContinue() { await run('provision', async () => { await vercelPlatformApi.provision(tenantId, name); if (onProjectReady) await onProjectReady(name); else await load(); }, false); }
  if (loading) return <section className="platform-panel vercel-panel"><div className="vercel-loading" role="status"><LoaderCircle />Preparando a próxima etapa…</div></section>;
  if (!state) return <section className="platform-panel vercel-panel"><div className="vercel-unavailable"><AlertTriangle /><div><h3>Não foi possível consultar a hospedagem</h3><p>{error}</p><button className="platform-secondary" onClick={() => void load()}><RefreshCw />Tentar novamente</button></div></div></section>;
  if (!state.configured) return <section className="platform-panel vercel-panel"><div className="platform-panel-head"><div><h2>Hospedagem do site</h2><span>Configuração protegida</span></div><Cloud /></div><div className="vercel-unavailable"><ShieldAlert /><div><h3>Integração ainda não configurada</h3><p>{state.message}</p><small>Nenhuma senha ou token deve ser informado nesta tela.</small></div></div></section>;
  const connected = state.step !== 'DISCONNECTED', named = ['NAME_VERIFIED', 'PROVISIONING', 'READY'].includes(state.step);
  return <section className="platform-panel vercel-panel"><div className="platform-panel-head"><div><h2>Publicar o site da clínica</h2><span>Assistente automático</span></div><Cloud /></div>
    <ol className="vercel-guide-progress" aria-label="Etapas da hospedagem">{[['1', 'Autorizar'], ['2', 'Escolher endereço'], ['3', 'Criar espaço']].map(([number, label], index) => <li key={number} className={index === 0 || (index === 1 && connected) || (index === 2 && named) ? 'done' : ''}><i>{(index === 0 && connected) || (index === 1 && named) || (index === 2 && state.step === 'READY') ? <Check /> : number}</i><span>{label}</span></li>)}</ol>
    <div className="vercel-content">
      {state.step === 'DISCONNECTED' && <div className="vercel-callout vercel-guided-callout"><span className="vercel-guide-icon"><ExternalLink /></span><small>PASSO 1 DE 3</small><h3>Autorize a criação do site</h3><p>Uma janela oficial da Vercel será aberta. Entre na sua conta e clique em autorizar. Nós nunca veremos sua senha.</p><div className="vercel-expectation"><ShieldAlert /><span><strong>O que você verá na janela?</strong><small>O nome KOS Nutri Provisionamento e a conta onde o site será criado.</small></span></div><button className="platform-primary" disabled={!!busy} onClick={connect}><ExternalLink />{busy ? 'Aguardando sua autorização…' : 'Abrir autorização segura'}</button><p className="vercel-help">A janela não abriu? Verifique o ícone de pop-up bloqueado ao lado da barra de endereço.</p></div>}
      {['CONNECTED', 'NAME_VERIFIED'].includes(state.step) && <><div className="vercel-account"><CheckCircle2 /><div><small>Autorização concluída</small><strong>{state.accountName || 'Conta Vercel conectada'}</strong></div><button disabled={!!busy} onClick={() => run('revoke', () => vercelPlatformApi.revoke(tenantId))}><Link2Off />Desconectar</button></div><div className="vercel-step-heading"><span className="vercel-guide-icon"><Globe2 /></span><div><small>PASSO 2 DE 3</small><h3>Escolha o endereço do site</h3><p>Já sugerimos um nome com base na clínica. Você pode usar como está ou personalizar.</p></div></div><form className="vercel-name" onSubmit={verify}><label htmlFor="vercel-project">Endereço desejado</label><div className="vercel-domain-field"><PencilLine /><input id="vercel-project" aria-describedby="vercel-domain-preview vercel-name-help" value={name} onChange={event => { setName(projectSlug(event.target.value)); setVerified(false); setFeedback(''); }} required minLength={3} pattern="[a-z0-9-]+" /><span>.vercel.app</span></div><small id="vercel-name-help">Use letras, números e hífens. Espaços e acentos são ajustados automaticamente.</small><div id="vercel-domain-preview" className="vercel-address-preview"><Globe2 /><span><small>Seu endereço ficará assim</small><strong>https://{name || 'minha-clinica'}.vercel.app</strong></span></div>{feedback && <p className={verified ? 'success' : 'error'} role="status">{feedback}</p>}{!verified && <button className="platform-secondary vercel-verify" disabled={busy === 'verify'}>{busy === 'verify' ? <><LoaderCircle className="activity-spinner" />Verificando disponibilidade…</> : <>Verificar este endereço<CheckCircle2 /></>}</button>}</form>{!verified && feedback && <div className="vercel-suggestions"><Lightbulb /><span><strong>Tente uma variação simples</strong><small>{name}-nutri · {name}-clinica · {name}-online</small></span></div>}{verified && <div className="vercel-create-step"><span><CheckCircle2 /></span><div><small>PASSO 3 DE 3</small><h3>Tudo pronto para criar</h3><p>Ao continuar, criaremos o espaço da clínica e avançaremos automaticamente. Você não precisará configurar nada dentro da Vercel agora.</p><button className="platform-primary" disabled={!!busy} onClick={createAndContinue}>{busy === 'provision' ? <><LoaderCircle className="activity-spinner" />Criando o espaço…</> : <><Cloud />Criar site e continuar</>}</button></div></div>}</>}
      {state.step === 'PROVISIONING' && <div className="vercel-progress" role="status"><LoaderCircle /><h3>Estamos preparando o site</h3><p>{state.message || 'Isso costuma levar menos de um minuto. Não feche esta página.'}</p><progress max="100" value={state.progress} /><small>{state.progress}% concluído</small></div>}
      {state.step === 'READY' && <div className="vercel-ready"><CheckCircle2 /><div><h3>Hospedagem pronta</h3><p>{state.message}</p><a href={state.deploymentUrl || '#'} target="_blank" rel="noreferrer">Abrir o site criado <ExternalLink /></a></div></div>}
      {state.step === 'FAILED' && <div className="vercel-unavailable"><AlertTriangle /><div><h3>Precisamos tentar novamente</h3><p>{state.message}</p>{state.canRetry && <button className="platform-primary" onClick={() => run('retry', () => vercelPlatformApi.retry(tenantId))}><RefreshCw />Tentar novamente</button>}</div></div>}
      {error && <div className="platform-form-error" role="alert">{error}</div>}
    </div></section>;
}
