ALTER TABLE patients ADD COLUMN IF NOT EXISTS address text;
ALTER TABLE patients ADD COLUMN IF NOT EXISTS emergency_contact text;
ALTER TABLE patients ADD COLUMN IF NOT EXISTS communication_preference text DEFAULT 'EMAIL';

CREATE TABLE patient_diary_entries(id uuid PRIMARY KEY DEFAULT gen_random_uuid(),patient_id uuid NOT NULL REFERENCES patients(id) ON DELETE CASCADE,entry_date date NOT NULL DEFAULT current_date,meal_notes text,symptoms text,hunger smallint CHECK(hunger BETWEEN 0 AND 10),satiety smallint CHECK(satiety BETWEEN 0 AND 10),water_liters numeric(4,2),adherence smallint CHECK(adherence BETWEEN 0 AND 100),created_at timestamptz NOT NULL DEFAULT now());
CREATE INDEX patient_diary_patient_idx ON patient_diary_entries(patient_id,entry_date DESC);
CREATE TABLE patient_exam_uploads(id uuid PRIMARY KEY DEFAULT gen_random_uuid(),patient_id uuid NOT NULL REFERENCES patients(id) ON DELETE CASCADE,title text NOT NULL,exam_date date,file_url text NOT NULL,notes text,status text NOT NULL DEFAULT 'SENT' CHECK(status IN('SENT','REVIEWED')),created_at timestamptz NOT NULL DEFAULT now());
CREATE TABLE patient_messages(id uuid PRIMARY KEY DEFAULT gen_random_uuid(),patient_id uuid NOT NULL REFERENCES patients(id) ON DELETE CASCADE,sender_role text NOT NULL CHECK(sender_role IN('PATIENT','ADMIN')),body text NOT NULL,read_at timestamptz,created_at timestamptz NOT NULL DEFAULT now());
CREATE INDEX patient_messages_patient_idx ON patient_messages(patient_id,created_at DESC);
CREATE TABLE appointment_requests(id uuid PRIMARY KEY DEFAULT gen_random_uuid(),patient_id uuid NOT NULL REFERENCES patients(id) ON DELETE CASCADE,preferred_date date NOT NULL,preferred_period text NOT NULL CHECK(preferred_period IN('MORNING','AFTERNOON','EVENING')),appointment_type text NOT NULL,notes text,status text NOT NULL DEFAULT 'PENDING' CHECK(status IN('PENDING','APPROVED','DECLINED')),created_at timestamptz NOT NULL DEFAULT now());
CREATE TABLE patient_goals(id uuid PRIMARY KEY DEFAULT gen_random_uuid(),patient_id uuid NOT NULL REFERENCES patients(id) ON DELETE CASCADE,title text NOT NULL,description text,due_date date,status text NOT NULL DEFAULT 'ACTIVE' CHECK(status IN('ACTIVE','COMPLETED','CANCELLED')),created_by uuid REFERENCES users(id) ON DELETE SET NULL,created_at timestamptz NOT NULL DEFAULT now(),completed_at timestamptz);
CREATE TABLE patient_measurements(id uuid PRIMARY KEY DEFAULT gen_random_uuid(),patient_id uuid NOT NULL REFERENCES patients(id) ON DELETE CASCADE,measured_at date NOT NULL,weight numeric(6,2),body_fat numeric(5,2),waist numeric(6,2),notes text,visible_to_patient boolean NOT NULL DEFAULT true,created_at timestamptz NOT NULL DEFAULT now());
CREATE TABLE patient_notifications(id uuid PRIMARY KEY DEFAULT gen_random_uuid(),patient_id uuid NOT NULL REFERENCES patients(id) ON DELETE CASCADE,title text NOT NULL,body text NOT NULL,kind text NOT NULL DEFAULT 'INFO',read_at timestamptz,created_at timestamptz NOT NULL DEFAULT now());

ALTER TABLE patient_diary_entries ENABLE ROW LEVEL SECURITY;ALTER TABLE patient_exam_uploads ENABLE ROW LEVEL SECURITY;ALTER TABLE patient_messages ENABLE ROW LEVEL SECURITY;ALTER TABLE appointment_requests ENABLE ROW LEVEL SECURITY;ALTER TABLE patient_goals ENABLE ROW LEVEL SECURITY;ALTER TABLE patient_measurements ENABLE ROW LEVEL SECURITY;ALTER TABLE patient_notifications ENABLE ROW LEVEL SECURITY;
