import type { FastifyInstance } from 'fastify';
import { z } from 'zod';
import { audit } from '../../shared/audit.js';
import { restorePlanNutrition } from './plan-content.js';

const jsonValue:z.ZodType<unknown>=z.lazy(()=>z.union([z.string().max(20000),z.number(),z.boolean(),z.null(),z.array(jsonValue).max(200),z.record(z.string().max(100),jsonValue)]));

export async function nutritionRoutes(app:FastifyInstance){
 app.addHook('preHandler',app.requireAdmin);
 app.get('/foods',async request=>{const {q,category}=z.object({q:z.string().trim().max(100).optional(),category:z.string().trim().max(80).optional()}).parse(request.query);const term=q?`%${q}%`:null;const result=await app.db.query(`SELECT id,legacy_id AS "legacyId",name,category,source,reference_unit AS "referenceUnit",kcal,carbohydrate,protein,fat,fiber FROM foods WHERE active=true AND ($1::text IS NULL OR name ILIKE $1) AND ($2::text IS NULL OR category=$2) ORDER BY name LIMIT 80`,[term,category||null]);return{data:result.rows}});
 app.get('/food-categories',async()=>{const result=await app.db.query('SELECT category, count(*)::int AS count FROM foods WHERE active=true GROUP BY category ORDER BY category');return{data:result.rows}});
 app.get('/recipes',async request=>{const {q,category}=z.object({q:z.string().trim().max(100).optional(),category:z.string().trim().max(80).optional()}).parse(request.query);const result=await app.db.query(`SELECT r.id,r.legacy_id AS "legacyId",r.title,r.category,r.preparation_time AS "preparationTime",r.yield_text AS "yieldText",r.instructions,
 COALESCE(json_agg(json_build_object('id',i.id,'foodId',i.food_id,'name',i.name_snapshot,'amount',i.amount_text,'kcal',i.kcal::float8,'carbohydrate',i.carbohydrate::float8,'protein',i.protein::float8,'fat',i.fat::float8) ORDER BY i.position) FILTER(WHERE i.id IS NOT NULL),'[]') AS ingredients
 FROM recipes r LEFT JOIN recipe_ingredients i ON i.recipe_id=r.id WHERE r.active=true AND ($1::text IS NULL OR r.title ILIKE $1 OR r.instructions ILIKE $1) AND ($2::text IS NULL OR r.category=$2) GROUP BY r.id ORDER BY r.title LIMIT 60`,[q?`%${q}%`:null,category||null]);return{data:result.rows}});
 app.get('/templates',async()=>{const result=await app.db.query('SELECT id,legacy_id AS "legacyId",title,objective,target_kcal::float8 AS "targetKcal",content FROM meal_plan_templates WHERE active=true ORDER BY target_kcal NULLS LAST,title');return{data:result.rows}});
 app.get('/plans',async request=>{const {patientId}=z.object({patientId:z.uuid().optional()}).parse(request.query);const result=await app.db.query(`SELECT mp.id,mp.patient_id AS "patientId",p.name AS "patientName",mp.encounter_id AS "encounterId",mp.title,mp.objective,mp.status,mp.content,mp.published_at AS "publishedAt",mp.updated_at AS "updatedAt" FROM meal_plans mp JOIN patients p ON p.id=mp.patient_id WHERE ($1::uuid IS NULL OR mp.patient_id=$1) ORDER BY mp.updated_at DESC LIMIT 50`,[patientId||null]);return{data:result.rows}});
 app.post('/plans/for-encounter',async(request,reply)=>{const{encounterId,templateId}=z.object({encounterId:z.uuid(),templateId:z.uuid().optional()}).parse(request.body);const encounter=await app.db.query<{patient_id:string;patient_name:string;objective:string|null}>(`SELECT e.patient_id,p.name AS patient_name,p.objective FROM clinical_encounters e JOIN patients p ON p.id=e.patient_id WHERE e.id=$1 AND e.status='IN_PROGRESS'`,[encounterId]);if(!encounter.rows[0])return reply.code(404).send({error:'Atendimento em andamento não encontrado.'});const existing=await app.db.query<{id:string}>('SELECT id FROM meal_plans WHERE encounter_id=$1 AND status<>\'ARCHIVED\' LIMIT 1',[encounterId]);if(existing.rows[0])return{data:{id:existing.rows[0].id,resumed:true}};let title=`Plano alimentar · ${encounter.rows[0].patient_name}`;let objective=encounter.rows[0].objective;let content:unknown={meals:[],extras:[]};if(templateId){const template=await app.db.query<{title:string;objective:string|null;content:unknown}>('SELECT title,objective,content FROM meal_plan_templates WHERE id=$1 AND active=true',[templateId]);if(!template.rows[0])return reply.code(404).send({error:'Modelo não encontrado.'});title=template.rows[0].title;objective=template.rows[0].objective||objective;content=template.rows[0].content}const result=await app.db.query<{id:string}>(`INSERT INTO meal_plans(patient_id,encounter_id,template_id,title,objective,content,created_by) VALUES($1,$2,$3,$4,$5,$6,$7) RETURNING id`,[encounter.rows[0].patient_id,encounterId,templateId||null,title,objective,content,request.auth!.userId]);const id=result.rows[0]!.id;await app.db.query(`INSERT INTO clinical_sections(encounter_id,section_key,data,saved_by) VALUES($1,'plan',$2,$3) ON CONFLICT(encounter_id,section_key) DO UPDATE SET data=excluded.data,saved_by=excluded.saved_by,saved_at=now()`,[encounterId,{planId:id},request.auth!.userId]);await audit(app.db,'MEAL_PLAN_CREATED_FROM_ENCOUNTER','meal_plan',{actorUserId:request.auth!.userId,entityId:id,metadata:{encounterId}});return reply.code(201).send({data:{id,resumed:false}})});
 app.get('/plans/:id',async(request,reply)=>{const{id}=z.object({id:z.uuid()}).parse(request.params);const result=await app.db.query(`SELECT mp.id,mp.patient_id AS "patientId",p.name AS "patientName",p.birth_date AS "birthDate",mp.encounter_id AS "encounterId",mp.template_id AS "templateId",mp.title,mp.objective,mp.status,mp.content,mt.content AS "templateContent",mp.published_at AS "publishedAt",mp.updated_at AS "updatedAt" FROM meal_plans mp JOIN patients p ON p.id=mp.patient_id LEFT JOIN meal_plan_templates mt ON mt.id=mp.template_id WHERE mp.id=$1`,[id]);const plan=result.rows[0];if(!plan)return reply.code(404).send({error:'Plano não encontrado.'});plan.content=restorePlanNutrition(plan.content,plan.templateContent);delete plan.templateContent;return{data:plan}});
 app.post('/plans',async(request,reply)=>{const body=z.object({patientId:z.uuid(),encounterId:z.uuid().optional(),templateId:z.uuid().optional(),title:z.string().trim().min(2).max(160),objective:z.string().trim().max(1000).optional(),content:jsonValue}).parse(request.body);const result=await app.db.query<{id:string}>(`INSERT INTO meal_plans(patient_id,encounter_id,template_id,title,objective,content,created_by) VALUES($1,$2,$3,$4,$5,$6,$7) RETURNING id`,[body.patientId,body.encounterId||null,body.templateId||null,body.title,body.objective||null,body.content,request.auth!.userId]);const id=result.rows[0]!.id;await audit(app.db,'MEAL_PLAN_CREATED','meal_plan',{actorUserId:request.auth!.userId,entityId:id,metadata:{patientId:body.patientId}});return reply.code(201).send({data:{id}})});
 app.patch('/plans/:id',async(request,reply)=>{const {id}=z.object({id:z.uuid()}).parse(request.params);const body=z.object({title:z.string().trim().min(2).max(160).optional(),objective:z.string().trim().max(1000).optional(),content:jsonValue.optional(),status:z.enum(['DRAFT','PUBLISHED','ARCHIVED']).optional()}).parse(request.body);const client=await app.db.connect();try{await client.query('BEGIN');const current=await client.query<Record<string,unknown>>('SELECT * FROM meal_plans WHERE id=$1 FOR UPDATE',[id]);if(!current.rows[0]){await client.query('ROLLBACK');return reply.code(404).send({error:'Plano não encontrado.'})}const p=current.rows[0];const nextStatus=body.status??p.status;if(nextStatus==='PUBLISHED')await client.query(`UPDATE meal_plans SET status='ARCHIVED',updated_at=now() WHERE patient_id=$1 AND id<>$2 AND status='PUBLISHED'`,[p.patient_id,id]);await client.query(`UPDATE meal_plans SET title=$1,objective=$2,content=$3,status=$4,published_at=CASE WHEN $4='PUBLISHED' AND published_at IS NULL THEN now() ELSE published_at END,updated_at=now() WHERE id=$5`,[body.title??p.title,body.objective??p.objective,body.content??p.content,nextStatus,id]);await client.query('COMMIT');await audit(app.db,'MEAL_PLAN_UPDATED','meal_plan',{actorUserId:request.auth!.userId,entityId:id,metadata:{fields:Object.keys(body),previousPlansArchived:nextStatus==='PUBLISHED'}});return{data:{id}}}catch(error){await client.query('ROLLBACK');throw error}finally{client.release()}});
}
