import type { FastifyInstance } from 'fastify';
import { z } from 'zod';
import { audit } from '../../shared/audit.js';

const patientParams = z.object({ patientId: z.uuid() });
const itemParams = patientParams.extend({ id: z.uuid() });
const optionalText = z.string().trim().max(1000).nullish();
const problemBody = z.object({ title:z.string().trim().min(2).max(180), status:z.enum(['ACTIVE','MONITORING','CONTROLLED','RESOLVED']).default('ACTIVE'), onsetDate:z.iso.date().nullish(), conduct:optionalText, notes:optionalText, sourceEncounterId:z.uuid().nullish() });
const therapyBody = z.object({ kind:z.enum(['MEDICATION','SUPPLEMENT']), name:z.string().trim().min(2).max(180), dosage:z.string().trim().max(120).nullish(), schedule:z.string().trim().max(240).nullish(), indication:z.string().trim().max(240).nullish(), prescriber:z.string().trim().max(180).nullish(), foodGuidance:optionalText, startedOn:z.iso.date().nullish(), endedOn:z.iso.date().nullish(), status:z.enum(['ACTIVE','PAUSED','FINISHED']).default('ACTIVE'), sourceEncounterId:z.uuid().nullish() });
const taskBody = z.object({ title:z.string().trim().min(2).max(240), details:optionalText, dueDate:z.iso.date().nullish(), priority:z.enum(['LOW','NORMAL','HIGH']).default('NORMAL'), status:z.enum(['OPEN','DONE','CANCELLED']).default('OPEN'), sourceEncounterId:z.uuid().nullish() });
const labBody = z.object({ encounterId:z.uuid(), examDate:z.iso.date().nullish(), marker:z.string().trim().min(1).max(160), markerKey:z.string().trim().max(100).nullish(), value:z.string().trim().min(1).max(100), numericValue:z.number().finite().nullish(), unit:z.string().trim().max(60).nullish(), referenceValue:z.string().trim().max(160).nullish(), status:z.string().trim().max(60).nullish(), observation:optionalText });

async function patientExists(app:FastifyInstance, patientId:string){ return Boolean((await app.db.query('SELECT 1 FROM patients WHERE id=$1 AND active=true',[patientId])).rows[0]); }
async function sourceEncounterBelongsToPatient(app:FastifyInstance, encounterId:string, patientId:string){return Boolean((await app.db.query('SELECT 1 FROM clinical_encounters WHERE id=$1 AND patient_id=$2',[encounterId,patientId])).rows[0]);}
function notFound(reply:any){ return reply.code(404).send({error:'Paciente ou registro clínico não encontrado.'}); }

export async function clinicalCoreRoutes(app: FastifyInstance) {
  app.addHook('preHandler', app.requireAdmin);

  app.get('/patients/:patientId/summary', async (request, reply) => {
    const {patientId}=patientParams.parse(request.params); if(!await patientExists(app,patientId)) return notFound(reply);
    const [patient,problems,therapies,tasks,labs,measurements,dismissed,latestSections]=await Promise.all([
      app.db.query(`SELECT id,name,objective,birth_date AS "birthDate" FROM patients WHERE id=$1`,[patientId]),
      app.db.query(`SELECT id,title,status,onset_date AS "onsetDate",conduct,notes,updated_at AS "updatedAt" FROM clinical_problems WHERE patient_id=$1 ORDER BY CASE status WHEN 'ACTIVE' THEN 0 WHEN 'MONITORING' THEN 1 WHEN 'CONTROLLED' THEN 2 ELSE 3 END,updated_at DESC`,[patientId]),
      app.db.query(`SELECT id,kind,name,dosage,schedule,indication,prescriber,food_guidance AS "foodGuidance",started_on AS "startedOn",ended_on AS "endedOn",status,updated_at AS "updatedAt" FROM clinical_therapies WHERE patient_id=$1 ORDER BY CASE status WHEN 'ACTIVE' THEN 0 WHEN 'PAUSED' THEN 1 ELSE 2 END,updated_at DESC`,[patientId]),
      app.db.query(`SELECT id,title,details,due_date AS "dueDate",priority,status,completed_at AS "completedAt" FROM clinical_followup_tasks WHERE patient_id=$1 ORDER BY CASE status WHEN 'OPEN' THEN 0 ELSE 1 END,due_date NULLS LAST,created_at DESC`,[patientId]),
      app.db.query(`SELECT id,exam_date AS "examDate",marker,marker_key AS "markerKey",value,numeric_value AS "numericValue",unit,reference_value AS "referenceValue",status,observation FROM laboratory_results WHERE patient_id=$1 ORDER BY exam_date DESC NULLS LAST,created_at DESC LIMIT 100`,[patientId]),
      app.db.query(`SELECT cs.data,e.started_at AS "startedAt" FROM clinical_sections cs JOIN clinical_encounters e ON e.id=cs.encounter_id WHERE e.patient_id=$1 AND cs.section_key='assessment' ORDER BY e.started_at DESC LIMIT 2`,[patientId]),
      app.db.query(`SELECT alert_key FROM clinical_alert_dismissals WHERE patient_id=$1`,[patientId]),
      app.db.query(`SELECT DISTINCT ON (cs.section_key) cs.section_key AS "sectionKey",cs.data,cs.saved_at AS "savedAt" FROM clinical_sections cs JOIN clinical_encounters e ON e.id=cs.encounter_id WHERE e.patient_id=$1 AND cs.section_key IN ('context','anamnesis','conduct') ORDER BY cs.section_key,cs.saved_at DESC`,[patientId])
    ]);
    const alerts:any[]=[]; const dismissedKeys=new Set(dismissed.rows.map((r:any)=>r.alert_key));
    for(const p of problems.rows.filter((x:any)=>x.status==='ACTIVE')) alerts.push({key:`problem:${p.id}`,severity:'INFO',title:p.title,detail:'Problema clínico ativo'});
    for(const l of labs.rows.filter((x:any)=>['ALTERADO','CRITICAL','CRÍTICO'].includes(String(x.status||'').toUpperCase())).slice(0,5)) alerts.push({key:`lab:${l.id}`,severity:String(l.status).toUpperCase().includes('CR')?'HIGH':'WARNING',title:`${l.marker}: ${l.value}${l.unit?' '+l.unit:''}`,detail:'Resultado laboratorial sinalizado'});
    const overdue=tasks.rows.filter((x:any)=>x.status==='OPEN'&&x.dueDate&&new Date(x.dueDate)<new Date()); if(overdue.length) alerts.push({key:'tasks:overdue',severity:'WARNING',title:`${overdue.length} pendência(s) vencida(s)`,detail:'Revise o plano de acompanhamento'});
    const assessment=measurements.rows.map((r:any)=>r.data); const currentWeight=Number(assessment[0]?.weight||assessment[0]?.peso); const priorWeight=Number(assessment[1]?.weight||assessment[1]?.peso);
    if(currentWeight>0&&priorWeight>0&&Math.abs((currentWeight-priorWeight)/priorWeight)>=.05) alerts.push({key:'weight:rapid-change',severity:'WARNING',title:'Variação de peso acima de 5%',detail:`${priorWeight} kg para ${currentWeight} kg entre os dois últimos registros`});
    const sections=Object.fromEntries(latestSections.rows.map((r:any)=>[r.sectionKey,r.data]));
    return {data:{patient:patient.rows[0],clinicalContext:{allergies:sections.anamnesis?.allergies||'',medications:sections.anamnesis?.medications||'',diagnosticImpression:sections.conduct?.diagnosticImpression||'',goals:sections.conduct?.goals||'',lastSavedAt:latestSections.rows[0]?.savedAt||null},problems:problems.rows,therapies:therapies.rows,tasks:tasks.rows,labs:labs.rows,alerts:alerts.filter(a=>!dismissedKeys.has(a.key))}};
  });

  app.post('/patients/:patientId/problems',async(request,reply)=>{const{patientId}=patientParams.parse(request.params);const b=problemBody.parse(request.body);if(!await patientExists(app,patientId))return notFound(reply);if(b.sourceEncounterId&&!await sourceEncounterBelongsToPatient(app,b.sourceEncounterId,patientId))return reply.code(400).send({error:'O atendimento de origem não pertence ao paciente.'});const r=await app.db.query<{id:string}>(`INSERT INTO clinical_problems(patient_id,source_encounter_id,title,status,onset_date,conduct,notes,resolved_at,created_by) VALUES($1,$2,$3,$4,$5,$6,$7,CASE WHEN $4='RESOLVED' THEN now() ELSE NULL END,$8) RETURNING id`,[patientId,b.sourceEncounterId,b.title,b.status,b.onsetDate,b.conduct,b.notes,request.auth!.userId]);await audit(app.db,'CLINICAL_PROBLEM_CREATED','patient',{actorUserId:request.auth!.userId,entityId:patientId,metadata:{problemId:r.rows[0]!.id}});return reply.code(201).send({data:{id:r.rows[0]!.id}})});
  app.patch('/patients/:patientId/problems/:id',async(request,reply)=>{const{patientId,id}=itemParams.parse(request.params);const b=problemBody.partial().parse(request.body);const current=(await app.db.query<any>('SELECT * FROM clinical_problems WHERE id=$1 AND patient_id=$2',[id,patientId])).rows[0];if(!current)return notFound(reply);const n={title:b.title??current.title,status:b.status??current.status,onsetDate:b.onsetDate===undefined?current.onset_date:b.onsetDate,conduct:b.conduct===undefined?current.conduct:b.conduct,notes:b.notes===undefined?current.notes:b.notes};await app.db.query(`UPDATE clinical_problems SET title=$1,status=$2,onset_date=$3,conduct=$4,notes=$5,resolved_at=CASE WHEN $2='RESOLVED' THEN COALESCE(resolved_at,now()) ELSE NULL END,updated_at=now() WHERE id=$6`,[n.title,n.status,n.onsetDate,n.conduct,n.notes,id]);await audit(app.db,'CLINICAL_PROBLEM_UPDATED','patient',{actorUserId:request.auth!.userId,entityId:patientId,metadata:{problemId:id}});return{data:{id}}});
  app.post('/patients/:patientId/therapies',async(request,reply)=>{const{patientId}=patientParams.parse(request.params);const b=therapyBody.parse(request.body);if(!await patientExists(app,patientId))return notFound(reply);if(b.sourceEncounterId&&!await sourceEncounterBelongsToPatient(app,b.sourceEncounterId,patientId))return reply.code(400).send({error:'O atendimento de origem não pertence ao paciente.'});const r=await app.db.query<{id:string}>(`INSERT INTO clinical_therapies(patient_id,source_encounter_id,kind,name,dosage,schedule,indication,prescriber,food_guidance,started_on,ended_on,status,created_by) VALUES($1,$2,$3,$4,$5,$6,$7,$8,$9,$10,$11,$12,$13) RETURNING id`,[patientId,b.sourceEncounterId,b.kind,b.name,b.dosage,b.schedule,b.indication,b.prescriber,b.foodGuidance,b.startedOn,b.endedOn,b.status,request.auth!.userId]);await audit(app.db,'CLINICAL_THERAPY_CREATED','patient',{actorUserId:request.auth!.userId,entityId:patientId,metadata:{therapyId:r.rows[0]!.id,kind:b.kind}});return reply.code(201).send({data:{id:r.rows[0]!.id}})});
  app.patch('/patients/:patientId/therapies/:id',async(request,reply)=>{const{patientId,id}=itemParams.parse(request.params);const b=therapyBody.partial().parse(request.body);const c=(await app.db.query<any>('SELECT * FROM clinical_therapies WHERE id=$1 AND patient_id=$2',[id,patientId])).rows[0];if(!c)return notFound(reply);await app.db.query(`UPDATE clinical_therapies SET kind=$1,name=$2,dosage=$3,schedule=$4,indication=$5,prescriber=$6,food_guidance=$7,started_on=$8,ended_on=$9,status=$10,updated_at=now() WHERE id=$11`,[b.kind??c.kind,b.name??c.name,b.dosage===undefined?c.dosage:b.dosage,b.schedule===undefined?c.schedule:b.schedule,b.indication===undefined?c.indication:b.indication,b.prescriber===undefined?c.prescriber:b.prescriber,b.foodGuidance===undefined?c.food_guidance:b.foodGuidance,b.startedOn===undefined?c.started_on:b.startedOn,b.endedOn===undefined?c.ended_on:b.endedOn,b.status??c.status,id]);return{data:{id}}});
  app.post('/patients/:patientId/tasks',async(request,reply)=>{const{patientId}=patientParams.parse(request.params);const b=taskBody.parse(request.body);if(!await patientExists(app,patientId))return notFound(reply);if(b.sourceEncounterId&&!await sourceEncounterBelongsToPatient(app,b.sourceEncounterId,patientId))return reply.code(400).send({error:'O atendimento de origem não pertence ao paciente.'});const r=await app.db.query<{id:string}>(`INSERT INTO clinical_followup_tasks(patient_id,source_encounter_id,title,details,due_date,priority,status,completed_at,created_by) VALUES($1,$2,$3,$4,$5,$6,$7,CASE WHEN $7='DONE' THEN now() ELSE NULL END,$8) RETURNING id`,[patientId,b.sourceEncounterId,b.title,b.details,b.dueDate,b.priority,b.status,request.auth!.userId]);return reply.code(201).send({data:{id:r.rows[0]!.id}})});
  app.patch('/patients/:patientId/tasks/:id',async(request,reply)=>{const{patientId,id}=itemParams.parse(request.params);const b=taskBody.partial().parse(request.body);const c=(await app.db.query<any>('SELECT * FROM clinical_followup_tasks WHERE id=$1 AND patient_id=$2',[id,patientId])).rows[0];if(!c)return notFound(reply);const status=b.status??c.status;await app.db.query(`UPDATE clinical_followup_tasks SET title=$1,details=$2,due_date=$3,priority=$4,status=$5,completed_at=CASE WHEN $5='DONE' THEN COALESCE(completed_at,now()) ELSE NULL END,updated_at=now() WHERE id=$6`,[b.title??c.title,b.details===undefined?c.details:b.details,b.dueDate===undefined?c.due_date:b.dueDate,b.priority??c.priority,status,id]);return{data:{id}}});
  app.post('/patients/:patientId/labs',async(request,reply)=>{const{patientId}=patientParams.parse(request.params);const b=labBody.parse(request.body);const encounter=(await app.db.query('SELECT 1 FROM clinical_encounters WHERE id=$1 AND patient_id=$2',[b.encounterId,patientId])).rows[0];if(!encounter)return reply.code(400).send({error:'O atendimento não pertence ao paciente.'});const r=await app.db.query<{id:string}>(`INSERT INTO laboratory_results(encounter_id,patient_id,exam_date,marker,marker_key,value,numeric_value,unit,reference_value,status,observation) VALUES($1,$2,$3,$4,$5,$6,$7,$8,$9,$10,$11) RETURNING id`,[b.encounterId,patientId,b.examDate,b.marker,b.markerKey?.toLowerCase()||b.marker.toLowerCase(),b.value,b.numericValue,b.unit,b.referenceValue,b.status,b.observation]);return reply.code(201).send({data:{id:r.rows[0]!.id}})});
  app.get('/patients/:patientId/labs/history',async request=>{const{patientId}=patientParams.parse(request.params);const q=z.object({markerKey:z.string().trim().max(100).optional(),limit:z.coerce.number().int().min(1).max(200).default(100)}).parse(request.query);const r=await app.db.query(`SELECT id,exam_date AS "examDate",marker,marker_key AS "markerKey",value,numeric_value AS "numericValue",unit,reference_value AS "referenceValue",status,observation FROM laboratory_results WHERE patient_id=$1 AND ($2::text IS NULL OR marker_key=$2) ORDER BY exam_date DESC NULLS LAST,created_at DESC LIMIT $3`,[patientId,q.markerKey?.toLowerCase()||null,q.limit]);return{data:r.rows}});
  app.post('/patients/:patientId/alerts/:alertKey/dismiss',async(request,reply)=>{const{patientId,alertKey}=z.object({patientId:z.uuid(),alertKey:z.string().min(1).max(240)}).parse(request.params);if(!await patientExists(app,patientId))return notFound(reply);await app.db.query(`INSERT INTO clinical_alert_dismissals(patient_id,alert_key,dismissed_by) VALUES($1,$2,$3) ON CONFLICT(patient_id,alert_key) DO UPDATE SET dismissed_by=EXCLUDED.dismissed_by,dismissed_at=now()`,[patientId,alertKey,request.auth!.userId]);return reply.code(204).send()});
}
