import { createHash } from 'node:crypto';
import type { FastifyInstance, FastifyReply, FastifyRequest } from 'fastify';
import { z } from 'zod';
import { audit } from '../../shared/audit.js';
import { createOpaqueToken, hashToken } from '../../shared/crypto.js';

const key=z.string().trim().min(8).max(128).regex(/^[A-Za-z0-9._:-]+$/);
const tenantSchema=z.object({idempotencyKey:key,slug:z.string().trim().min(2).max(63).regex(/^[a-z0-9]+(?:-[a-z0-9]+)*$/),name:z.string().trim().min(2).max(160),contactEmail:z.string().trim().max(254).pipe(z.email()).transform(v=>v.toLowerCase())}).strict();
const jobSchema=z.object({idempotencyKey:key,operation:z.enum(['PROVISION_TENANT','REPAIR_TENANT']).default('PROVISION_TENANT'),request:z.object({databaseRegion:z.string().trim().min(2).max(40).optional(),hostingRegion:z.string().trim().min(2).max(40).optional()}).strict().default({})}).strict();
const completeSchema=z.object({outcome:z.enum(['SUCCEEDED','FAILED']),summary:z.object({message:z.string().trim().max(500).optional(),checks:z.array(z.string().trim().min(1).max(100)).max(30).optional()}).strict().default({})}).strict();
const idSchema=z.object({id:z.uuid()}).strict();
const tenantParams=z.object({tenantId:z.uuid()}).passthrough();
const onboardingSchema=z.object({idempotencyKey:key,clinicName:z.string().trim().min(2).max(160),professionalName:z.string().trim().min(2).max(160),contactEmail:z.string().trim().max(254).pipe(z.email()).transform(v=>v.toLowerCase()),ownerName:z.string().trim().min(2).max(160),ownerEmail:z.string().trim().max(254).pipe(z.email()).transform(v=>v.toLowerCase()),inviteExpiresInHours:z.number().int().min(1).max(168).default(48)}).strict();
const onboardingStep=z.enum(['clinic','vercel','supabase','identity','review']),clinicStep=z.object({name:z.string().trim().min(2).max(160),contactEmail:z.string().trim().max(254).pipe(z.email()).transform(v=>v.toLowerCase())}).strict(),vercelStep=z.object({projectName:z.string().regex(/^[a-z0-9](?:[a-z0-9-]{0,98}[a-z0-9])?$/)}).strict(),supabaseStep=z.object({projectRef:z.string().regex(/^[a-z0-9-]{6,40}$/),region:z.string().regex(/^[a-z0-9-]{2,40}$/)}).strict(),identityStep=z.object({brandName:z.string().trim().min(2).max(160),primaryColor:z.string().regex(/^#[0-9a-fA-F]{6}$/),ownerEmail:z.string().trim().max(254).pipe(z.email()).transform(v=>v.toLowerCase())}).strict();
const fingerprint=(value:unknown)=>createHash('sha256').update(JSON.stringify(value)).digest('hex');
async function onboardingState(app:FastifyInstance,tenantId:string){const [onboarding,connection,supabase,preview,activity]=await Promise.all([app.db.query<any>(`SELECT o.clinic_name AS "clinicName",o.contact_email AS "contactEmail",o.owner_email AS "ownerEmail",o.status,(SELECT j.request_payload->'identity' FROM provisioning_jobs j WHERE j.tenant_id=o.tenant_id AND j.request_payload ? 'identity' ORDER BY j.updated_at DESC LIMIT 1) AS identity FROM tenant_onboardings o WHERE o.tenant_id=$1`,[tenantId]),app.db.query<any>(`SELECT status,project_name AS "projectName" FROM tenant_provider_connections WHERE tenant_id=$1 AND provider='VERCEL'`,[tenantId]),app.db.query<any>(`SELECT result_summary->'supabase' AS value FROM provisioning_jobs WHERE tenant_id=$1 AND result_summary ? 'supabase' ORDER BY updated_at DESC LIMIT 1`,[tenantId]),app.db.query<any>(`SELECT id,status,progress,preview_url AS url,last_error_code AS "lastErrorCode" FROM tenant_preview_deployments WHERE tenant_id=$1 ORDER BY created_at DESC LIMIT 1`,[tenantId]),app.db.query<any>(`SELECT id,operation AS label,status,COALESCE(result_summary->>'message','') AS detail FROM provisioning_jobs WHERE tenant_id=$1 ORDER BY created_at`,[tenantId])]),o=onboarding.rows[0];if(!o)return null;const v=connection.rows[0],s=supabase.rows[0]?.value??{},p=preview.rows[0],identity=o.identity??{},vercelDone=v?.status==='CONNECTED'&&v.projectName,supabaseDone=s.verified===true,identityDone=Boolean(identity.brandName&&identity.primaryColor&&identity.ownerEmail),publishReady=p?.status==='KNOWN_GOOD',failed=p?.status==='FAILED_RETRYABLE'||p?.status==='FAILED_MANUAL',current=publishReady?'PUBLISH':!vercelDone?'VERCEL':!supabaseDone?'SUPABASE':!identityDone?'IDENTITY':'REVIEW';return{tenantId,currentStep:current,overallProgress:publishReady?100:p?.progress??(identityDone?65:supabaseDone?50:vercelDone?35:15),configured:true,steps:{CLINIC:'COMPLETED',VERCEL:vercelDone?'COMPLETED':'IN_PROGRESS',SUPABASE:supabaseDone?'COMPLETED':vercelDone?'IN_PROGRESS':'LOCKED',IDENTITY:identityDone?'COMPLETED':supabaseDone?'IN_PROGRESS':'LOCKED',REVIEW:identityDone?'COMPLETED':'LOCKED',PUBLISH:publishReady?'COMPLETED':failed?'FAILED':identityDone?'IN_PROGRESS':'LOCKED'},clinic:{name:o.clinicName,contactEmail:o.contactEmail},vercel:{projectName:v?.projectName??'',connected:v?.status==='CONNECTED'},supabase:{projectRef:s.projectRef??'',region:s.region??'sa-east-1',verified:supabaseDone},identity:{brandName:identity.brandName??o.clinicName,primaryColor:identity.primaryColor??'#183b2b',ownerEmail:identity.ownerEmail??o.ownerEmail},publication:{status:publishReady?'READY':p?.status==='ROLLED_BACK'?'ROLLED_BACK':failed?'FAILED':p?'RUNNING':'IDLE',...(p?.url?{url:p.url}:{}),...(p?.lastErrorCode?{message:p.lastErrorCode}: {})},activity:activity.rows.map((x:any)=>({...x,detail:x.detail||'Aguardando conclusão.'}))}}

export async function platformRoutes(app:FastifyInstance){
  const requirePlatform=async(request:FastifyRequest,reply:FastifyReply)=>{
    await app.authenticate(request,reply); if(reply.sent)return;
    const allowed=await app.db.query<{allowed:boolean}>(`SELECT EXISTS(SELECT 1 FROM user_roles ur JOIN roles r ON r.id=ur.role_id JOIN role_permissions rp ON rp.role_id=r.id JOIN permissions p ON p.id=rp.permission_id WHERE ur.user_id=$1 AND r.code='PLATFORM_ADMIN' AND p.code='platform:manage') AS allowed`,[request.auth!.userId]);
    if(allowed.rows[0]?.allowed!==true)return reply.code(403).send({error:'Acesso restrito à administração da plataforma.'});
  };
  app.addHook('preHandler',requirePlatform);

  app.get('/tenants',async()=>({data:(await app.db.query(`SELECT id,slug,name,contact_email AS "contactEmail",status,created_at AS "createdAt",updated_at AS "updatedAt" FROM platform_tenants ORDER BY created_at DESC LIMIT 200`)).rows}));
  app.get('/tenants/:tenantId/onboarding',async(request,reply)=>{const{tenantId}=tenantParams.parse(request.params);await app.db.query(`SELECT 1 FROM tenant_onboardings o WHERE o.tenant_id=$1`,[tenantId]);const state=await onboardingState(app,tenantId);return state?{data:state}:reply.code(404).send({error:'Onboarding não encontrado para este tenant.'})});
  app.put('/tenants/:tenantId/onboarding/steps/:step',async(request,reply)=>{const{tenantId}=tenantParams.parse(request.params),{step}=z.object({step:onboardingStep}).parse(request.params);if(step==='clinic'){const body=clinicStep.parse(request.body),row=(await app.db.query(`UPDATE tenant_onboardings SET clinic_name=$2,contact_email=$3,updated_at=now() WHERE tenant_id=$1 AND status='DRAFT' RETURNING id`,[tenantId,body.name,body.contactEmail])).rows[0];if(!row)return reply.code(409).send({error:'Etapa clínica não pode ser alterada.'})}else if(step==='vercel'){const body=vercelStep.parse(request.body),row=(await app.db.query(`SELECT 1 FROM tenant_provider_connections WHERE tenant_id=$1 AND provider='VERCEL' AND status='CONNECTED' AND project_name=$2`,[tenantId,body.projectName])).rows[0];if(!row)return reply.code(409).send({error:'Conecte e valide o projeto Vercel antes de concluir esta etapa.'})}else if(step==='supabase'){const body=supabaseStep.parse(request.body),row=(await app.db.query(`SELECT 1 FROM provisioning_jobs WHERE tenant_id=$1 AND (result_summary->'supabase'->>'verified')::boolean=true AND result_summary->'supabase'->>'projectRef'=$2 AND result_summary->'supabase'->>'region'=$3`,[tenantId,body.projectRef,body.region])).rows[0];if(!row)return reply.code(409).send({error:'A referência Supabase precisa estar verificada.'})}else if(step==='identity'){const body=identityStep.parse(request.body),row=(await app.db.query(`UPDATE tenant_onboardings SET clinic_name=$2,owner_email=$3,updated_at=now() WHERE tenant_id=$1 AND status='DRAFT' RETURNING id`,[tenantId,body.brandName,body.ownerEmail])).rows[0];if(!row)return reply.code(409).send({error:'Identidade não pode ser alterada.'});await app.db.query(`UPDATE provisioning_jobs SET request_payload=jsonb_set(request_payload,'{identity}',$2::jsonb,true),updated_at=now() WHERE id=(SELECT id FROM provisioning_jobs WHERE tenant_id=$1 ORDER BY created_at DESC LIMIT 1)`,[tenantId,JSON.stringify(body)])}else{const state=await onboardingState(app,tenantId);if(!state||state.steps.IDENTITY!=='COMPLETED')return reply.code(409).send({error:'Complete as etapas anteriores antes da revisão.'})}const state=await onboardingState(app,tenantId);return state?{data:state}:reply.code(404).send({error:'Onboarding não encontrado.'})});
  app.post('/tenants/:tenantId/onboarding',async(request,reply)=>{const{tenantId}=tenantParams.parse(request.params);const body=onboardingSchema.parse(request.body);const fp=fingerprint({clinicName:body.clinicName,professionalName:body.professionalName,contactEmail:body.contactEmail,ownerName:body.ownerName,ownerEmail:body.ownerEmail,inviteExpiresInHours:body.inviteExpiresInHours});const tokenHash=hashToken(createOpaqueToken());const result=await app.db.query<{id:string;status:string;idempotent:boolean}>(`INSERT INTO tenant_onboardings(tenant_id,clinic_name,professional_name,contact_email,owner_name,owner_email,owner_invite_token_hash,owner_invite_expires_at,idempotency_key,request_fingerprint,created_by) SELECT t.id,$2,$3,$4,$5,$6,$7,now()+($8::int*interval '1 hour'),$9,$10,$11 FROM platform_tenants t WHERE t.id=$1 AND t.status='DRAFT' ON CONFLICT(tenant_id) DO UPDATE SET idempotency_key=EXCLUDED.idempotency_key WHERE tenant_onboardings.idempotency_key=EXCLUDED.idempotency_key AND tenant_onboardings.request_fingerprint=EXCLUDED.request_fingerprint RETURNING id,status,(xmax<>0) AS idempotent`,[tenantId,body.clinicName,body.professionalName,body.contactEmail,body.ownerName,body.ownerEmail,tokenHash,body.inviteExpiresInHours,body.idempotencyKey,fp,request.auth!.userId]);const onboarding=result.rows[0];if(!onboarding)return reply.code(409).send({error:'Tenant indisponível ou chave de idempotência reutilizada com outros dados.'});if(!onboarding.idempotent)await audit(app.db,'TENANT_ONBOARDING_DRAFTED','tenant_onboarding',{actorUserId:request.auth!.userId,entityId:onboarding.id,metadata:{tenantId}});return reply.code(onboarding.idempotent?200:201).send({data:onboarding,message:'Onboarding e convite da proprietária preparados. Nenhum e-mail foi enviado.'})});
  app.post('/tenants',async(request,reply)=>{
    const body=tenantSchema.parse(request.body); const fp=fingerprint({slug:body.slug,name:body.name,contactEmail:body.contactEmail});
    const result=await app.db.query<{id:string;status:string;idempotent:boolean}>(`INSERT INTO platform_tenants(slug,name,contact_email,creation_key,creation_fingerprint,created_by) VALUES($1,$2,$3,$4,$5,$6) ON CONFLICT(creation_key) DO UPDATE SET creation_key=EXCLUDED.creation_key WHERE platform_tenants.creation_fingerprint=EXCLUDED.creation_fingerprint RETURNING id,status,(xmax<>0) AS idempotent`,[body.slug,body.name,body.contactEmail,body.idempotencyKey,fp,request.auth!.userId]);
    const tenant=result.rows[0];if(!tenant)return reply.code(409).send({error:'A chave de idempotência já foi usada com outros dados.'});
    if(!tenant.idempotent)await audit(app.db,'PLATFORM_TENANT_CREATED','platform_tenant',{actorUserId:request.auth!.userId,entityId:tenant.id,metadata:{slug:body.slug}});
    return reply.code(tenant.idempotent?200:201).send({data:tenant});
  });

  app.post('/tenants/:id/jobs',async(request,reply)=>{
    const{id}=idSchema.parse(request.params); const body=jobSchema.parse(request.body); const fp=fingerprint({operation:body.operation,request:body.request});
    const created=await app.db.query<{id:string;status:string;idempotent:boolean}>(`INSERT INTO provisioning_jobs(tenant_id,operation,idempotency_key,request_fingerprint,request_payload,requested_by) SELECT id,$2,$3,$4,$5,$6 FROM platform_tenants WHERE id=$1 AND status IN('DRAFT','READY','FAILED') ON CONFLICT(tenant_id,idempotency_key) DO UPDATE SET idempotency_key=EXCLUDED.idempotency_key WHERE provisioning_jobs.request_fingerprint=EXCLUDED.request_fingerprint RETURNING id,status,(xmax<>0) AS idempotent`,[id,body.operation,body.idempotencyKey,fp,body.request,request.auth!.userId]);
    const job=created.rows[0];if(!job)return reply.code(409).send({error:'Tenant indisponível ou chave de idempotência reutilizada com outro job.'});
    if(!job.idempotent)await audit(app.db,'PROVISIONING_JOB_QUEUED','provisioning_job',{actorUserId:request.auth!.userId,entityId:job.id,metadata:{tenantId:id,operation:body.operation}});return reply.code(job.idempotent?200:201).send({data:job});
  });

  app.get('/jobs',async()=>({data:(await app.db.query(`SELECT j.id,j.tenant_id AS "tenantId",t.slug,j.operation,j.status,j.attempt_count AS "attemptCount",j.available_at AS "availableAt",j.started_at AS "startedAt",j.completed_at AS "completedAt",j.result_summary AS "resultSummary",j.created_at AS "createdAt" FROM provisioning_jobs j JOIN platform_tenants t ON t.id=j.tenant_id ORDER BY j.created_at DESC LIMIT 200`)).rows}));
  app.post('/jobs/:id/start',async(request,reply)=>{
    const{id}=idSchema.parse(request.params);const row=(await app.db.query<{id:string;status:string}>(`WITH claimed AS (UPDATE provisioning_jobs SET status='RUNNING',started_by=$2,started_at=now(),attempt_count=attempt_count+1,updated_at=now() WHERE id=$1 AND status='PENDING' AND available_at<=now() RETURNING id,tenant_id,status) UPDATE platform_tenants t SET status='PROVISIONING',updated_at=now() FROM claimed c WHERE t.id=c.tenant_id RETURNING c.id,c.status`,[id,request.auth!.userId])).rows[0];
    if(!row)return reply.code(409).send({error:'Job inexistente, indisponível ou já iniciado.'});await audit(app.db,'PROVISIONING_JOB_STARTED','provisioning_job',{actorUserId:request.auth!.userId,entityId:id});return{data:row};
  });
  app.post('/jobs/:id/complete',async(request,reply)=>{
    const{id}=idSchema.parse(request.params);const body=completeSchema.parse(request.body);const row=(await app.db.query<{id:string;tenantId:string;status:string}>(`WITH finished AS (UPDATE provisioning_jobs SET status=$2,result_summary=$3,completed_by=$4,completed_at=now(),updated_at=now() WHERE id=$1 AND status='RUNNING' RETURNING id,tenant_id,status) UPDATE platform_tenants t SET status=$5,updated_at=now() FROM finished f WHERE t.id=f.tenant_id RETURNING f.id,f.tenant_id AS "tenantId",f.status`,[id,body.outcome,body.summary,request.auth!.userId,body.outcome==='SUCCEEDED'?'READY':'FAILED'])).rows[0];
    if(!row)return reply.code(409).send({error:'Job inexistente ou fora do estado RUNNING.'});await audit(app.db,'PROVISIONING_JOB_COMPLETED','provisioning_job',{actorUserId:request.auth!.userId,entityId:id,metadata:{tenantId:row.tenantId,outcome:body.outcome}});return{data:row};
  });
}
