import { createHash, randomBytes } from 'node:crypto';
import type { FastifyInstance, FastifyReply } from 'fastify';
import { z } from 'zod';
import type { GuidedSupabaseVerifier, SupabaseProvider } from '../../integrations/supabase-provider.js';
import { guidedSupabaseSetup } from '../../integrations/supabase-provider.js';
import { audit } from '../../shared/audit.js';
import { createOpaqueToken, hashToken } from '../../shared/crypto.js';
import { decryptSecret, encryptSecret } from '../../shared/secret.js';

const params=z.object({tenantId:z.uuid()}).strict(), ref=z.string().trim().regex(/^[a-z0-9-]{6,40}$/), slug=z.string().trim().regex(/^[a-z0-9-]{2,80}$/), region=z.string().trim().regex(/^[a-z0-9-]{2,40}$/), secret=z.string().trim().max(300).regex(/^vault:\/\/tenant\/[0-9a-f-]{36}\/[a-z0-9/_-]+$/);
const referenceSchema=z.object({projectRef:ref,organizationSlug:slug,region,databaseSecretRef:secret,migrationDatabaseSecretRef:secret}).strict();
const startSchema=z.object({organizationSlug:slug,projectName:z.string().trim().min(2).max(80),region:region.default('sa-east-1')}).strict();
const callbackSchema=z.object({state:z.string().min(32),code:z.string().min(1).max(2048)}).strict();
const tokenSchema=z.object({token:z.string().min(32).max(512)}).strict();
const belongs=(v:string,t:string)=>v.startsWith(`vault://tenant/${t}/`);
const challenge=(v:string)=>createHash('sha256').update(v).digest('base64url');
const isProvider=(v:GuidedSupabaseVerifier|SupabaseProvider):v is SupabaseProvider=>'mode' in v;
const configured=(a:FastifyInstance,p:GuidedSupabaseVerifier|SupabaseProvider)=>Boolean(isProvider(p)&&p.mode==='OAUTH'&&a.env.APP_ENCRYPTION_KEY&&a.env.SUPABASE_OAUTH_CLIENT_ID&&a.env.SUPABASE_OAUTH_CLIENT_SECRET&&a.env.SUPABASE_OAUTH_REDIRECT_URI&&a.env.ALLOW_EXTERNAL_PROVIDER_PROVISIONING===true);

function page(a:FastifyInstance,i:{status:'success'|'error';state:string;tenantId?:string}){const origin=new URL(a.env.FRONTEND_ORIGIN).origin,payload=JSON.stringify({type:'nutri:supabase-oauth',...i}).replaceAll('<','\\u003c');return`<!doctype html><html lang="pt-BR"><head><meta charset="utf-8"><meta name="viewport" content="width=device-width"><title>Conexão com o Supabase</title></head><body><main><h1>${i.status==='success'?'Banco conectado':'Conexão não concluída'}</h1><p>${i.status==='success'?'O projeto foi criado na conta da clínica. Esta janela será fechada.':'Volte à plataforma e tente novamente.'}</p></main><script>window.opener?.postMessage(${payload},${JSON.stringify(origin)});window.close();</script></body></html>`}
function send(a:FastifyInstance,r:FastifyReply,s:number,i:{status:'success'|'error';state:string;tenantId?:string}){return r.code(s).header('Content-Security-Policy',"default-src 'none'; script-src 'unsafe-inline'; style-src 'none'; img-src 'none'; connect-src 'none'; frame-ancestors 'none'; base-uri 'none'; form-action 'none'").header('Referrer-Policy','no-referrer').header('Cache-Control','no-store').type('text/html; charset=utf-8').send(page(a,i))}

export async function supabaseRoutes(app:FastifyInstance,integration:GuidedSupabaseVerifier|SupabaseProvider){
 const manage={preHandler:app.requireExplicitPermission('platform:manage')};
 app.get('/tenants/:tenantId',manage,async req=>{const{tenantId}=params.parse(req.params),connection=(await app.db.query<any>(`SELECT status,project_id AS "projectRef",project_name AS "projectName",organization_slug AS "organizationSlug",region FROM tenant_provider_connections WHERE tenant_id=$1 AND provider='SUPABASE'`,[tenantId])).rows[0],guided=(await app.db.query<any>(`SELECT j.result_summary->'supabase' AS supabase FROM provisioning_jobs j WHERE j.tenant_id=$1 AND j.result_summary ? 'supabase' ORDER BY j.updated_at DESC LIMIT 1`,[tenantId])).rows[0]?.supabase??null,ready=configured(app,integration);return{data:{configured:ready,mode:ready?'OAUTH':'GUIDED',guide:ready?null:guidedSupabaseSetup(),connection:connection?.status==='CONNECTED'?connection:null,reference:guided}}});

 app.post('/tenants/:tenantId/start',manage,async(req,reply)=>{
  if(!configured(app,integration)||!isProvider(integration))return reply.code(503).send({error:'Integração Supabase não configurada.'});
  const{tenantId}=params.parse(req.params),body=startSchema.parse(req.body);
  if(!(await app.db.query(`SELECT 1 FROM platform_tenants WHERE id=$1 AND status<>'ARCHIVED'`,[tenantId])).rows[0])return reply.code(404).send({error:'Tenant não encontrado.'});
  if(!(await app.db.query(`SELECT 1 FROM provisioning_jobs WHERE tenant_id=$1 AND operation='PROVISION_TENANT' AND status='RUNNING'`,[tenantId])).rows[0])return reply.code(409).send({error:'Inicie um job de provisionamento antes de conectar o Supabase.'});
  const previous=(await app.db.query<any>(`SELECT provider_secret_encrypted AS secret,request_payload AS payload FROM provider_oauth_states WHERE tenant_id=$1 AND provider='SUPABASE' AND consumed_at IS NULL AND expires_at>now() ORDER BY created_at DESC LIMIT 1`,[tenantId])).rows[0];
  const reusable=previous?.secret&&previous?.payload?.organizationSlug===body.organizationSlug&&previous?.payload?.projectName===body.projectName;
  const state=createOpaqueToken(),verifier=createOpaqueToken(),providerSecret=reusable?previous.secret:encryptSecret(randomBytes(30).toString('base64url'),app.env.APP_ENCRYPTION_KEY!);
  const authorizationUrl=await integration.authorizationUrl({state,codeChallenge:challenge(verifier),organizationSlug:body.organizationSlug});
  await app.db.query(`UPDATE provider_oauth_states SET consumed_at=now() WHERE tenant_id=$1 AND provider='SUPABASE' AND consumed_at IS NULL`,[tenantId]);
  await app.db.query(`INSERT INTO provider_oauth_states(tenant_id,provider,state_hash,pkce_verifier_encrypted,provider_secret_encrypted,requested_by,expires_at,request_payload) VALUES($1,'SUPABASE',$2,$3,$4,$5,now()+interval '10 minutes',$6::jsonb)`,[tenantId,hashToken(state),encryptSecret(verifier,app.env.APP_ENCRYPTION_KEY!),providerSecret,req.auth!.userId,JSON.stringify(body)]);
  return{data:{authorizationUrl}};
 });

 app.get('/callback',async(req,reply)=>{
  if(!configured(app,integration)||!isProvider(integration))return reply.code(503).send({error:'Integração Supabase não configurada.'});
  const q=callbackSchema.parse(req.query),client=await app.db.connect();let committed=false;
  try{
   await client.query('BEGIN');
   const state=(await client.query<any>(`SELECT tenant_id AS "tenantId",pkce_verifier_encrypted AS verifier,provider_secret_encrypted AS "providerSecret",requested_by AS "requestedBy",request_payload AS payload FROM provider_oauth_states WHERE provider='SUPABASE' AND state_hash=$1 AND consumed_at IS NULL AND expires_at>now() FOR UPDATE`,[hashToken(q.state)])).rows[0];
   if(!state){await client.query('ROLLBACK');return send(app,reply,400,{status:'error',state:q.state})}
   const tokens=await integration.exchangeCode({code:q.code,codeVerifier:decryptSecret(state.verifier,app.env.APP_ENCRYPTION_KEY!)});
   const password=decryptSecret(state.providerSecret,app.env.APP_ENCRYPTION_KEY!);
   const existing=integration.findProject?await integration.findProject({accessToken:tokens.accessToken,name:state.payload.projectName,organizationSlug:state.payload.organizationSlug}):null;
   const project=existing??await integration.createProject({accessToken:tokens.accessToken,name:state.payload.projectName,organizationSlug:state.payload.organizationSlug,dbPassword:password,regionSelection:state.payload.region});
   const url=`postgresql://postgres:${encodeURIComponent(password)}@db.${project.ref}.supabase.co:5432/postgres?sslmode=require`;
   await client.query(`INSERT INTO tenant_provider_connections(tenant_id,provider,status,access_token_encrypted,refresh_token_encrypted,token_expires_at,external_account_id,project_id,project_name,organization_slug,region,database_url_encrypted,migration_database_url_encrypted,connected_by,connected_at) VALUES($1,'SUPABASE','CONNECTED',$2,$3,now()+($4::text||' seconds')::interval,$5,$6,$7,$8,$9,$10,$11,$12,now()) ON CONFLICT(tenant_id,provider) DO UPDATE SET status='CONNECTED',access_token_encrypted=EXCLUDED.access_token_encrypted,refresh_token_encrypted=EXCLUDED.refresh_token_encrypted,token_expires_at=EXCLUDED.token_expires_at,external_account_id=EXCLUDED.external_account_id,project_id=EXCLUDED.project_id,project_name=EXCLUDED.project_name,organization_slug=EXCLUDED.organization_slug,region=EXCLUDED.region,database_url_encrypted=EXCLUDED.database_url_encrypted,migration_database_url_encrypted=EXCLUDED.migration_database_url_encrypted,connected_by=EXCLUDED.connected_by,connected_at=now(),revoked_at=NULL,updated_at=now()`,[state.tenantId,encryptSecret(tokens.accessToken,app.env.APP_ENCRYPTION_KEY!),tokens.refreshToken?encryptSecret(tokens.refreshToken,app.env.APP_ENCRYPTION_KEY!):null,tokens.expiresIn,project.organizationSlug,project.ref,project.name,project.organizationSlug,state.payload.region,encryptSecret(url,app.env.APP_ENCRYPTION_KEY!),encryptSecret(url,app.env.APP_ENCRYPTION_KEY!),state.requestedBy]);
   const safe={projectRef:project.ref,organizationSlug:project.organizationSlug,region:state.payload.region,databaseSecretRef:`vault://tenant/${state.tenantId}/database/runtime`,migrationDatabaseSecretRef:`vault://tenant/${state.tenantId}/database/migration`,verified:true,provisioned:true,recovered:Boolean(existing)};
   const job=(await client.query<any>(`UPDATE provisioning_jobs SET result_summary=jsonb_set(result_summary,'{supabase}',$2::jsonb,true),updated_at=now() WHERE id=(SELECT id FROM provisioning_jobs WHERE tenant_id=$1 AND operation='PROVISION_TENANT' AND status='RUNNING' ORDER BY started_at DESC LIMIT 1) RETURNING id`,[state.tenantId,JSON.stringify(safe)])).rows[0];
   if(!job)throw Object.assign(new Error('Job de provisionamento não está mais ativo.'),{code:'SUPABASE_JOB_NOT_RUNNING'});
   await client.query(`UPDATE provider_oauth_states SET consumed_at=now(),provider_secret_encrypted=NULL WHERE provider='SUPABASE' AND state_hash=$1 AND consumed_at IS NULL`,[hashToken(q.state)]);
   await client.query('COMMIT');committed=true;
   try{await audit(app.db,'SUPABASE_OAUTH_PROJECT_CONNECTED','tenant_provider_connection',{actorUserId:state.requestedBy,metadata:{tenantId:state.tenantId,projectRef:project.ref,recovered:Boolean(existing)}})}catch{app.log.error({tenantId:state.tenantId},'Falha ao auditar conexão Supabase')}
   return send(app,reply,200,{status:'success',state:q.state,tenantId:state.tenantId});
  }catch{if(!committed)await client.query('ROLLBACK');return send(app,reply,502,{status:'error',state:q.state})}finally{client.release()}
 });

 app.put('/tenants/:tenantId/reference',manage,async(req,reply)=>{const{tenantId}=params.parse(req.params),body=referenceSchema.parse(req.body);if(!belongs(body.databaseSecretRef,tenantId)||!belongs(body.migrationDatabaseSecretRef,tenantId))return reply.code(422).send({error:'As referências de secret devem pertencer ao tenant informado.'});if(isProvider(integration))return reply.code(409).send({error:'Use a autorização Supabase; segredos não são recebidos por esta tela.'});const check=await integration.verifyReference(body);if(!check.verified)return reply.code(422).send({error:'Referência Supabase não verificada.'});const safe={...body,verified:true},row=(await app.db.query<any>(`UPDATE provisioning_jobs SET result_summary=jsonb_set(result_summary,'{supabase}',$2::jsonb,true),updated_at=now() WHERE id=(SELECT id FROM provisioning_jobs WHERE tenant_id=$1 AND status='RUNNING' ORDER BY started_at DESC LIMIT 1) RETURNING id`,[tenantId,JSON.stringify(safe)])).rows[0];if(!row)return reply.code(409).send({error:'Inicie um job de provisionamento antes de vincular o Supabase.'});await audit(app.db,'SUPABASE_GUIDED_REFERENCE_LINKED','provisioning_job',{actorUserId:req.auth!.userId,entityId:row.id,metadata:{tenantId,projectRef:body.projectRef}});return{data:safe}});
 app.delete('/tenants/:tenantId',manage,async(req,reply)=>{const{tenantId}=params.parse(req.params),row=(await app.db.query<any>(`UPDATE tenant_provider_connections SET status='REVOKED',access_token_encrypted=NULL,refresh_token_encrypted=NULL,database_url_encrypted=NULL,migration_database_url_encrypted=NULL,revoked_at=now(),updated_at=now() WHERE tenant_id=$1 AND provider='SUPABASE' AND status='CONNECTED' RETURNING id`,[tenantId])).rows[0];if(!row)return reply.code(404).send({error:'Conexão Supabase ativa não encontrada.'});await audit(app.db,'SUPABASE_CONNECTION_REVOKED','tenant_provider_connection',{actorUserId:req.auth!.userId,entityId:row.id,metadata:{tenantId}});return reply.code(204).send()});
 app.post('/tenants/:tenantId/owner-invitation/release',manage,async(req,reply)=>{const{tenantId}=params.parse(req.params),row=(await app.db.query<any>(`UPDATE tenant_onboardings o SET status='OWNER_INVITED',updated_at=now() WHERE o.tenant_id=$1 AND o.status='DRAFT' AND o.owner_invite_status='PENDING' AND o.owner_invite_expires_at>now() AND EXISTS(SELECT 1 FROM provisioning_jobs j WHERE j.tenant_id=o.tenant_id AND j.status='SUCCEEDED' AND (j.result_summary->'supabase'->>'verified')::boolean=true) AND EXISTS(SELECT 1 FROM tenant_preview_deployments d WHERE d.tenant_id=o.tenant_id AND d.status='KNOWN_GOOD') RETURNING o.id,o.owner_email AS "ownerEmail",o.owner_invite_expires_at AS "expiresAt"`,[tenantId])).rows[0];if(!row)return reply.code(409).send({error:'Convite bloqueado: Supabase verificado, publicação known-good e convite válido são obrigatórios.'});await audit(app.db,'TENANT_OWNER_INVITATION_RELEASED','tenant_onboarding',{actorUserId:req.auth!.userId,entityId:row.id,metadata:{tenantId}});return{data:row,message:'Convite liberado para entrega por canal seguro.'}});
 app.post('/tenants/:tenantId/owner-invitation/accept',async(req,reply)=>{const{tenantId}=params.parse(req.params),body=tokenSchema.parse(req.body),row=(await app.db.query<any>(`WITH accepted AS (UPDATE tenant_onboardings SET owner_invite_status='ACCEPTED',status='READY',updated_at=now() WHERE tenant_id=$1 AND status='OWNER_INVITED' AND owner_invite_status='PENDING' AND owner_invite_expires_at>now() AND owner_invite_token_hash=$2 RETURNING id) UPDATE platform_tenants t SET status='ACTIVE',updated_at=now() FROM accepted a WHERE t.id=$1 RETURNING a.id,t.id AS "tenantId",t.status`,[tenantId,hashToken(body.token)])).rows[0];if(!row)return reply.code(400).send({error:'Convite inválido, expirado ou já utilizado.'});await audit(app.db,'TENANT_OWNER_INVITATION_ACCEPTED','tenant_onboarding',{entityId:row.id,metadata:{tenantId}});return{data:row}})
}
