import type{FastifyInstance}from'fastify';import{z}from'zod';import{audit}from'../../shared/audit.js';import{hashToken}from'../../shared/crypto.js';import{guidedSupabaseSetup,type GuidedSupabaseVerifier}from'../../integrations/supabase-provider.js';
const params=z.object({tenantId:z.uuid()}).strict(),ref=z.string().trim().regex(/^[a-z0-9-]{6,40}$/),slug=z.string().trim().regex(/^[a-z0-9-]{2,80}$/),region=z.string().trim().regex(/^[a-z0-9-]{2,40}$/),secret=z.string().trim().max(300).regex(/^vault:\/\/tenant\/[0-9a-f-]{36}\/[a-z0-9/_-]+$/);
const referenceSchema=z.object({projectRef:ref,organizationSlug:slug,region,databaseSecretRef:secret,migrationDatabaseSecretRef:secret}).strict();const tokenSchema=z.object({token:z.string().min(32).max(512)}).strict();
const belongs=(value:string,tenantId:string)=>value.startsWith(`vault://tenant/${tenantId}/`);
export async function supabaseRoutes(app:FastifyInstance,verifier:GuidedSupabaseVerifier){const manage={preHandler:app.requireExplicitPermission('platform:manage')};
 app.get('/tenants/:tenantId',manage,async(req,reply)=>{const{tenantId}=params.parse(req.params),row=(await app.db.query<any>(`SELECT j.result_summary->'supabase' AS supabase FROM provisioning_jobs j WHERE j.tenant_id=$1 AND j.result_summary ? 'supabase' ORDER BY j.updated_at DESC LIMIT 1`,[tenantId])).rows[0];return{data:{configured:true,mode:'GUIDED',guide:guidedSupabaseSetup(),reference:row?.supabase??null}}});
 app.put('/tenants/:tenantId/reference',manage,async(req,reply)=>{const{tenantId}=params.parse(req.params),body=referenceSchema.parse(req.body);if(!belongs(body.databaseSecretRef,tenantId)||!belongs(body.migrationDatabaseSecretRef,tenantId))return reply.code(422).send({error:'As referências de secret devem pertencer ao tenant informado.'});const check=await verifier.verifyReference(body);if(!check.verified)return reply.code(422).send({error:'Referência Supabase não verificada.'});const safe={projectRef:body.projectRef,organizationSlug:body.organizationSlug,region:body.region,databaseSecretRef:body.databaseSecretRef,migrationDatabaseSecretRef:body.migrationDatabaseSecretRef,verified:true};const row=(await app.db.query<any>(`UPDATE provisioning_jobs SET result_summary=jsonb_set(result_summary,'{supabase}',$2::jsonb,true),updated_at=now() WHERE id=(SELECT id FROM provisioning_jobs WHERE tenant_id=$1 AND status='RUNNING' ORDER BY started_at DESC LIMIT 1) RETURNING id`,[tenantId,JSON.stringify(safe)])).rows[0];if(!row)return reply.code(409).send({error:'Inicie um job de provisionamento antes de vincular o Supabase.'});await audit(app.db,'SUPABASE_GUIDED_REFERENCE_LINKED','provisioning_job',{actorUserId:req.auth!.userId,entityId:row.id,metadata:{tenantId,projectRef:body.projectRef}});return{data:safe}});
 app.post('/tenants/:tenantId/owner-invitation/release',manage,async(req,reply)=>{const{tenantId}=params.parse(req.params);const row=(await app.db.query<any>(`UPDATE tenant_onboardings o SET status='OWNER_INVITED',updated_at=now() WHERE o.tenant_id=$1 AND o.status='DRAFT' AND o.owner_invite_status='PENDING' AND o.owner_invite_expires_at>now() AND EXISTS(SELECT 1 FROM provisioning_jobs j WHERE j.tenant_id=o.tenant_id AND j.status='SUCCEEDED' AND (j.result_summary->'supabase'->>'verified')::boolean=true) AND EXISTS(SELECT 1 FROM tenant_preview_deployments d WHERE d.tenant_id=o.tenant_id AND d.status='KNOWN_GOOD') RETURNING o.id,o.owner_email AS "ownerEmail",o.owner_invite_expires_at AS "expiresAt"`,[tenantId])).rows[0];if(!row)return reply.code(409).send({error:'Convite bloqueado: Supabase verificado, publicação known-good e convite válido são obrigatórios.'});await audit(app.db,'TENANT_OWNER_INVITATION_RELEASED','tenant_onboarding',{actorUserId:req.auth!.userId,entityId:row.id,metadata:{tenantId}});return{data:row,message:'Convite liberado para entrega por canal seguro.'}});
 app.post('/tenants/:tenantId/owner-invitation/accept',async(req,reply)=>{const{tenantId}=params.parse(req.params),body=tokenSchema.parse(req.body),row=(await app.db.query<any>(`WITH accepted AS (UPDATE tenant_onboardings SET owner_invite_status='ACCEPTED',status='READY',updated_at=now() WHERE tenant_id=$1 AND status='OWNER_INVITED' AND owner_invite_status='PENDING' AND owner_invite_expires_at>now() AND owner_invite_token_hash=$2 RETURNING id) UPDATE platform_tenants t SET status='ACTIVE',updated_at=now() FROM accepted a WHERE t.id=$1 RETURNING a.id,t.id AS "tenantId",t.status`,[tenantId,hashToken(body.token)])).rows[0];if(!row)return reply.code(400).send({error:'Convite inválido, expirado ou já utilizado.'});await audit(app.db,'TENANT_OWNER_INVITATION_ACCEPTED','tenant_onboarding',{entityId:row.id,metadata:{tenantId}});return{data:row}})
}
