import type { FastifyInstance } from 'fastify';
import { z } from 'zod';
import { audit } from '../../shared/audit.js';
import { canTransitionPayment, normalizedPaidAt, type PaymentStatus } from '../../shared/payment-status.js';

const statusSchema=z.enum(['PENDING','PAID','CANCELLED','OVERDUE']);
const schema=z.object({patientId:z.uuid(),appointmentId:z.uuid().nullable().optional(),description:z.string().trim().min(2).max(200),amount:z.coerce.number().min(0),dueDate:z.iso.date(),paidAt:z.string().datetime().nullable().optional(),paymentMethod:z.string().trim().max(80).nullable().optional(),status:statusSchema.optional(),notes:z.string().trim().max(1000).nullable().optional()});

async function refreshOverdue(app:FastifyInstance){await app.db.query(`UPDATE financial_transactions SET status='OVERDUE',updated_at=now() WHERE status='PENDING' AND due_date<current_date`)}

export async function financeRoutes(app:FastifyInstance){
  app.addHook('preHandler',app.requireAdmin);
  app.get('/',async()=>{await refreshOverdue(app);const r=await app.db.query(`SELECT f.id,f.patient_id AS "patientId",p.name AS "patientName",f.appointment_id AS "appointmentId",f.description,f.amount,f.due_date AS "dueDate",f.paid_at AS "paidAt",f.payment_method AS "paymentMethod",f.status,f.notes,f.refunded_at AS "refundedAt",f.refund_reason AS "refundReason" FROM financial_transactions f JOIN patients p ON p.id=f.patient_id ORDER BY f.due_date DESC,f.created_at DESC LIMIT 200`);return{data:r.rows}});
  app.get('/summary',async()=>{await refreshOverdue(app);const r=await app.db.query(`SELECT COALESCE(sum(amount) FILTER(WHERE status='PAID' AND date_trunc('month',paid_at)=date_trunc('month',now())),0) AS "monthRevenue",COALESCE(sum(amount) FILTER(WHERE status IN('PENDING','OVERDUE')),0) AS "outstanding",count(*) FILTER(WHERE status='OVERDUE') AS overdue FROM financial_transactions`);const operational=await app.db.query(`SELECT (SELECT count(*) FROM patients WHERE active) AS patients,(SELECT count(*) FROM appointments WHERE appointment_date=current_date AND status NOT IN('CANCELLED','NO_SHOW')) AS "todayAppointments",(SELECT count(*) FROM clinical_encounters WHERE status='IN_PROGRESS') AS "openEncounters"`);return{data:{...r.rows[0],...operational.rows[0]}}});
  app.post('/',async(request,reply)=>{const b=schema.parse(request.body);const status=b.status??'PENDING';if(b.appointmentId){const linked=await app.db.query('SELECT id FROM appointments WHERE id=$1 AND patient_id=$2',[b.appointmentId,b.patientId]);if(!linked.rows[0])return reply.code(409).send({error:'A consulta informada não pertence ao paciente selecionado.'})}const paidAt=normalizedPaidAt(status,b.paidAt);const r=await app.db.query<{id:string}>(`INSERT INTO financial_transactions(patient_id,appointment_id,description,amount,due_date,paid_at,payment_method,status,notes,created_by) VALUES($1,$2,$3,$4,$5,$6,$7,$8,$9,$10) RETURNING id`,[b.patientId,b.appointmentId||null,b.description,b.amount,b.dueDate,paidAt,b.paymentMethod||null,status,b.notes||null,request.auth!.userId]);await audit(app.db,'FINANCIAL_TRANSACTION_CREATED','financial_transaction',{actorUserId:request.auth!.userId,entityId:r.rows[0]!.id,metadata:{status}});return reply.code(201).send({data:{id:r.rows[0]!.id}})});
  app.patch('/:id',async(request,reply)=>{const{id}=z.object({id:z.uuid()}).parse(request.params);const b=schema.partial().parse(request.body);const client=await app.db.connect();try{await client.query('BEGIN');const current=await client.query<Record<string,unknown>>('SELECT * FROM financial_transactions WHERE id=$1 FOR UPDATE',[id]);if(!current.rows[0]){await client.query('ROLLBACK');return reply.code(404).send({error:'Lançamento não encontrado.'})}const f=current.rows[0];const currentStatus=f.status as PaymentStatus;const nextStatus=(b.status??currentStatus) as PaymentStatus;if(!canTransitionPayment(currentStatus,nextStatus)){await client.query('ROLLBACK');return reply.code(409).send({error:'Alteração incompatível com o estado atual do pagamento. Pagamentos confirmados exigem um fluxo próprio de estorno.'})}const patientId=(b.patientId??f.patient_id) as string;const appointmentId=b.appointmentId===undefined?f.appointment_id:b.appointmentId;if(appointmentId){const linked=await client.query('SELECT id FROM appointments WHERE id=$1 AND patient_id=$2',[appointmentId,patientId]);if(!linked.rows[0]){await client.query('ROLLBACK');return reply.code(409).send({error:'A consulta informada não pertence ao paciente selecionado.'})}}const paidAt=normalizedPaidAt(nextStatus,b.paidAt===undefined?undefined:b.paidAt,f.paid_at);await client.query(`UPDATE financial_transactions SET patient_id=$1,appointment_id=$2,description=$3,amount=$4,due_date=$5,paid_at=$6,payment_method=$7,status=$8,notes=$9,updated_at=now() WHERE id=$10`,[patientId,appointmentId,b.description??f.description,b.amount??f.amount,b.dueDate??f.due_date,paidAt,b.paymentMethod===undefined?f.payment_method:b.paymentMethod,nextStatus,b.notes===undefined?f.notes:b.notes,id]);await audit(client,'FINANCIAL_TRANSACTION_UPDATED','financial_transaction',{actorUserId:request.auth!.userId,entityId:id,metadata:{fromStatus:currentStatus,toStatus:nextStatus,fields:Object.keys(b)}});await client.query('COMMIT');return{data:{id,status:nextStatus,paidAt}}}catch(error){await client.query('ROLLBACK');throw error}finally{client.release()}});
  app.post('/:id/refund',async(request,reply)=>{const{id}=z.object({id:z.uuid()}).parse(request.params);const{reason}=z.object({reason:z.string().trim().min(3).max(1000)}).parse(request.body);const client=await app.db.connect();try{await client.query('BEGIN');const current=await client.query<{status:PaymentStatus;patient_id:string;amount:string}>(`SELECT status,patient_id,amount FROM financial_transactions WHERE id=$1 FOR UPDATE`,[id]);if(!current.rows[0]){await client.query('ROLLBACK');return reply.code(404).send({error:'Lançamento não encontrado.'})}if(current.rows[0].status!=='PAID'){await client.query('ROLLBACK');return reply.code(409).send({error:'Somente um pagamento confirmado pode ser estornado.'})}await client.query(`UPDATE financial_transactions SET status='REFUNDED',refunded_at=now(),refund_reason=$2,refunded_by=$3,updated_at=now() WHERE id=$1`,[id,reason,request.auth!.userId]);await client.query(`INSERT INTO patient_notifications(patient_id,title,body,kind,priority,entity_type,entity_id,action_url,dedupe_key,expires_at) VALUES($1,'Pagamento estornado','Um pagamento foi marcado como estornado pelo consultório. Consulte o financeiro para conferir o registro.','FINANCE','NORMAL','financial_transaction',$2,'/portal?tab=financeiro','payment-refunded:'||$2,now()+interval '90 days') ON CONFLICT(patient_id,dedupe_key) WHERE dedupe_key IS NOT NULL AND status='ACTIVE' DO NOTHING`,[current.rows[0].patient_id,id]);await audit(client,'FINANCIAL_TRANSACTION_REFUNDED','financial_transaction',{actorUserId:request.auth!.userId,entityId:id,metadata:{previousStatus:'PAID',amount:current.rows[0].amount,reason}});await client.query('COMMIT');return{data:{id,status:'REFUNDED'}}}catch(error){await client.query('ROLLBACK');throw error}finally{client.release()}});
}
