import{encryptSecret,decryptSecret}from'../shared/secret.js';
export type SupabaseTokens={accessToken:string;refreshToken?:string;expiresIn:number};export type SupabaseProject={id:string;ref:string;name:string;organizationSlug:string};
export interface SupabaseProvider{mode:'DISABLED'|'GUIDED'|'OAUTH';authorizationUrl(input:{state:string;codeChallenge:string;organizationSlug?:string}):Promise<string>;exchangeCode(input:{code:string;codeVerifier:string}):Promise<SupabaseTokens>;createProject(input:{accessToken:string;name:string;organizationSlug:string;dbPassword:string;regionSelection?:string}):Promise<SupabaseProject>;getProject(input:{accessToken:string;projectRef:string}):Promise<SupabaseProject|null>}
const disabled=async()=>{throw Object.assign(new Error('Integração Supabase externa desativada.'),{code:'PROVIDER_DISABLED'})};
export const disabledSupabaseProvider:SupabaseProvider={mode:'DISABLED',authorizationUrl:disabled,exchangeCode:disabled,createProject:disabled,getProject:disabled};
export function guidedSupabaseSetup(){return{mode:'GUIDED' as const,steps:['Criar ou selecionar uma organização na conta da clínica.','Criar projeto exclusivo de homologação.','Copiar apenas project ref e organization slug.','Inserir a senha do banco diretamente no cofre da instalação.'],acceptsAccountPassword:false,acceptsDatabaseUrl:false}}
type Http=(url:string,init:RequestInit)=>Promise<Response>;
export function createSupabaseOAuthProvider(config:{clientId?:string;clientSecret?:string;redirectUri?:string;allowExternal:boolean;http?:Http}):SupabaseProvider{
  if(!config.allowExternal||!config.clientId||!config.clientSecret||!config.redirectUri||!config.http)return disabledSupabaseProvider;
  const http=config.http,request=async(url:string,init:RequestInit)=>{const response=await http(url,init);if(!response.ok)throw Object.assign(new Error('Supabase Management API indisponível.'),{code:`SUPABASE_HTTP_${response.status}`});return response.json() as Promise<any>};
  return{mode:'OAUTH',async authorizationUrl({state,codeChallenge,organizationSlug}){const u=new URL('https://api.supabase.com/v1/oauth/authorize');u.searchParams.set('client_id',config.clientId!);u.searchParams.set('redirect_uri',config.redirectUri!);u.searchParams.set('response_type','code');u.searchParams.set('state',state);u.searchParams.set('code_challenge',codeChallenge);u.searchParams.set('code_challenge_method','S256');if(organizationSlug)u.searchParams.set('organization_slug',organizationSlug);return u.toString()},async exchangeCode({code,codeVerifier}){const data=await request('https://api.supabase.com/v1/oauth/token',{method:'POST',headers:{'content-type':'application/x-www-form-urlencoded'},body:new URLSearchParams({grant_type:'authorization_code',code,code_verifier:codeVerifier,client_id:config.clientId!,client_secret:config.clientSecret!,redirect_uri:config.redirectUri!})});return{accessToken:data.access_token,refreshToken:data.refresh_token,expiresIn:data.expires_in}},async createProject(input){const data=await request('https://api.supabase.com/v1/projects',{method:'POST',headers:{authorization:`Bearer ${input.accessToken}`,'content-type':'application/json'},body:JSON.stringify({name:input.name,organization_slug:input.organizationSlug,db_pass:input.dbPassword,...(input.regionSelection?{region_selection:input.regionSelection}:{})})});return{id:data.id,ref:data.ref,name:data.name??input.name,organizationSlug:data.organization_slug??input.organizationSlug}},async getProject({accessToken,projectRef}){const response=await http(`https://api.supabase.com/v1/projects/${encodeURIComponent(projectRef)}`,{method:'GET',headers:{authorization:`Bearer ${accessToken}`}});if(response.status===404)return null;if(!response.ok)throw Object.assign(new Error('Supabase Management API indisponível.'),{code:`SUPABASE_HTTP_${response.status}`});const data:any=await response.json();return{id:data.id,ref:data.ref,name:data.name,organizationSlug:data.organization_slug}}}
}
export function sealSupabaseSecrets(input:{accessToken:string;refreshToken?:string;databaseUrl:string;migrationDatabaseUrl:string},encryptionKey:string){return{accessTokenEncrypted:encryptSecret(input.accessToken,encryptionKey),refreshTokenEncrypted:input.refreshToken?encryptSecret(input.refreshToken,encryptionKey):null,databaseUrlEncrypted:encryptSecret(input.databaseUrl,encryptionKey),migrationDatabaseUrlEncrypted:encryptSecret(input.migrationDatabaseUrl,encryptionKey)}}
export function openSupabaseSecret(ciphertext:string,encryptionKey:string){return decryptSecret(ciphertext,encryptionKey)}
export function createFakeSupabaseProvider():SupabaseProvider&{calls:string[]}{const calls:string[]=[];return{mode:'GUIDED',calls,async authorizationUrl(){calls.push('authorizationUrl');return'https://example.test/fake-supabase-consent'},async exchangeCode(){calls.push('exchangeCode');return{accessToken:'fake-access',refreshToken:'fake-refresh',expiresIn:3600}},async createProject(input){calls.push('createProject');return{id:'fake-id',ref:'demo-staging-ref',name:input.name,organizationSlug:input.organizationSlug}},async getProject(){calls.push('getProject');return null}}}
