import type{VercelDeployment,VercelProject,VercelProvider,VercelToken}from'./vercel-provider.js';
type Fetch=typeof fetch;export type VercelHttpConfig={clientId:string;clientSecret:string;redirectUri:string;authorizationUrl?:string;apiBase?:string;timeoutMs?:number};
export class VercelProviderError extends Error{constructor(public code:string,public status?:number){super('Falha na integração com a Vercel.');this.name='VercelProviderError'}}
export class VercelHttpProvider implements VercelProvider{constructor(private c:VercelHttpConfig,private f:Fetch=fetch){}private async call<T>(path:string,init:RequestInit={},token?:string):Promise<T>{const method=init.method??'GET',tries=method==='GET'?3:1;for(let n=1;n<=tries;n++){const controller=new AbortController(),timer=setTimeout(()=>controller.abort(),this.c.timeoutMs??10000);try{const r=await this.f(`${this.c.apiBase??'https://api.vercel.com'}${path}`,{...init,signal:controller.signal,headers:{accept:'application/json',...(init.body?{'content-type':'application/json'}:{}),...(token?{authorization:`Bearer ${token}`}:{ }),...init.headers}});if(r.ok)return await r.json() as T;if(r.status===404)throw new VercelProviderError('NOT_FOUND',404);if(n<tries&&(r.status===429||r.status>=500)){continue}throw new VercelProviderError(r.status===401||r.status===403?'AUTH_REJECTED':'API_REJECTED',r.status)}catch(e){if(e instanceof VercelProviderError)throw e;if(n===tries)throw new VercelProviderError('NETWORK_FAILURE')}finally{clearTimeout(timer)}}throw new VercelProviderError('NETWORK_FAILURE')}
 async authorizationUrl(i:{state:string;codeChallenge:string}){const u=new URL(this.c.authorizationUrl??'https://vercel.com/oauth/authorize');u.searchParams.set('client_id',this.c.clientId);u.searchParams.set('redirect_uri',this.c.redirectUri);u.searchParams.set('state',i.state);u.searchParams.set('code_challenge',i.codeChallenge);u.searchParams.set('code_challenge_method','S256');return u.toString()}
 async exchangeCode(i:{code:string;codeVerifier:string}):Promise<VercelToken>{const x=await this.call<any>('/v2/oauth/access_token',{method:'POST',body:JSON.stringify({client_id:this.c.clientId,client_secret:this.c.clientSecret,code:i.code,redirect_uri:this.c.redirectUri,code_verifier:i.codeVerifier})});if(!x.access_token||!x.user_id)throw new VercelProviderError('INVALID_RESPONSE');return{accessToken:x.access_token,accountId:x.user_id}}
 async getAccount(i:{accessToken:string}){const x=await this.call<any>('/v2/user',{},i.accessToken);return{id:x.user?.id??x.id,email:x.user?.email??x.email}}
 async checkProjectName(i:{accessToken:string;name:string}){try{await this.getProject({accessToken:i.accessToken,projectId:i.name});return false}catch(e){if(e instanceof VercelProviderError&&e.code==='NOT_FOUND')return true;throw e}}
 async createProject(i:{accessToken:string;name:string}){const x=await this.call<any>('/v11/projects',{method:'POST',body:JSON.stringify({name:i.name})},i.accessToken);return{id:x.id,name:x.name}}
 async getProject(i:{accessToken:string;projectId:string}):Promise<VercelProject|null>{try{const x=await this.call<any>(`/v9/projects/${encodeURIComponent(i.projectId)}`,{},i.accessToken);return{id:x.id,name:x.name}}catch(e){if(e instanceof VercelProviderError&&e.code==='NOT_FOUND')return null;throw e}}
 async setEnvironmentVariables(i:{accessToken:string;projectId:string;variables:Array<{key:string;value:string;target:Array<'production'|'preview'|'development'>}>}){await this.call(`/v9/projects/${encodeURIComponent(i.projectId)}/env?upsert=true`,{method:'POST',body:JSON.stringify(i.variables.map(v=>({...v,type:'encrypted'})))},i.accessToken)}
 async createPrebuiltDeployment(i:{accessToken:string;projectId:string;name:string;files:Array<{file:string;sha:string}>;target?:'production'|'preview'}):Promise<VercelDeployment>{const x=await this.call<any>('/v13/deployments',{method:'POST',body:JSON.stringify({name:i.name,project:i.projectId,files:i.files,target:i.target==='production'?'production':undefined})},i.accessToken);return{id:x.id,url:x.url,status:x.readyState??x.status}}
 async getDeployment(i:{accessToken:string;deploymentId:string}){try{const x=await this.call<any>(`/v13/deployments/${encodeURIComponent(i.deploymentId)}`,{},i.accessToken);return{id:x.id,url:x.url,status:x.readyState??x.status}}catch(e){if(e instanceof VercelProviderError&&e.code==='NOT_FOUND')return null;throw e}}
 async addDomain(i:{accessToken:string;projectId:string;domain:string}){return this.call<{name:string;verified:boolean}>(`/v10/projects/${encodeURIComponent(i.projectId)}/domains`,{method:'POST',body:JSON.stringify({name:i.domain})},i.accessToken)}
 async rollback(i:{accessToken:string;projectId:string;deploymentId:string}){await this.call(`/v10/projects/${encodeURIComponent(i.projectId)}/promote/${encodeURIComponent(i.deploymentId)}`,{method:'POST',body:'{}'},i.accessToken)}
 async revoke(i:{accessToken:string}){await this.call('/v2/oauth/access_token',{method:'DELETE'},i.accessToken)} }
