import type { FastifyInstance } from 'fastify';
import { z } from 'zod';
import { examStorage } from '../../integrations/storage.js';
import { audit } from '../../shared/audit.js';

const params=z.object({id:z.uuid()});
const clinicalReference=z.object({
  encounterId:z.uuid(),
  interpretation:z.string().trim().min(2).max(3000),
  marker:z.object({name:z.string().trim().min(1).max(160),value:z.string().trim().min(1).max(100),unit:z.string().trim().max(50).optional(),referenceValue:z.string().trim().max(160).optional(),status:z.string().trim().max(50).optional()}).optional()
});

export async function patientExamRoutes(app:FastifyInstance){
  app.addHook('preHandler',app.requireAdmin);
  app.get('/',async request=>{const q=z.object({status:z.enum(['SENT','REVIEWED']).optional(),patientId:z.uuid().optional()}).parse(request.query);const result=await app.db.query(`SELECT e.id,e.patient_id AS "patientId",p.name AS "patientName",p.email,e.title,e.exam_date AS "examDate",e.notes,e.status,e.mime_type AS "mimeType",e.file_size AS "fileSize",e.created_at AS "createdAt",e.encounter_id AS "encounterId",e.clinical_interpretation AS "clinicalInterpretation",e.reviewed_at AS "reviewedAt",e.file_path IS NOT NULL OR e.file_url IS NOT NULL AS "hasFile" FROM patient_exam_uploads e JOIN patients p ON p.id=e.patient_id WHERE ($1::text IS NULL OR e.status=$1) AND ($2::uuid IS NULL OR e.patient_id=$2) ORDER BY CASE WHEN e.status='SENT' THEN 0 ELSE 1 END,e.created_at DESC`,[q.status||null,q.patientId||null]);return{data:result.rows}});
  app.get('/:id/url',async(request,reply)=>{const{id}=params.parse(request.params);const row=(await app.db.query<{file_path:string|null;file_url:string|null}>('SELECT file_path,file_url FROM patient_exam_uploads WHERE id=$1',[id])).rows[0];if(!row)return reply.code(404).send({error:'Exame não encontrado.'});if(row.file_path){const{data,error}=await examStorage(app.env).createSignedUrl(row.file_path,300);if(error)throw error;return{data:{url:data.signedUrl}}}if(row.file_url)return{data:{url:row.file_url}};return reply.code(404).send({error:'Arquivo do exame não encontrado.'})});
  app.patch('/:id/review',async(request,reply)=>{const{id}=params.parse(request.params);const result=await app.db.query<{patientId:string}>(`UPDATE patient_exam_uploads SET status='REVIEWED' WHERE id=$1 RETURNING patient_id AS "patientId"`,[id]);if(!result.rows[0])return reply.code(404).send({error:'Exame não encontrado.'});await audit(app.db,'PATIENT_EXAM_REVIEWED','patient_exam_upload',{actorUserId:request.auth!.userId,entityId:id,metadata:{patientId:result.rows[0].patientId}});return{message:'Exame marcado como revisado.'}});
  app.patch('/:id/clinical-reference',async(request,reply)=>{const{id}=params.parse(request.params);const b=clinicalReference.parse(request.body);const exam=(await app.db.query<{patientId:string;examDate:string|null}>('SELECT patient_id AS "patientId",exam_date AS "examDate" FROM patient_exam_uploads WHERE id=$1',[id])).rows[0];if(!exam)return reply.code(404).send({error:'Exame não encontrado.'});const encounter=(await app.db.query<{status:string}>('SELECT status FROM clinical_encounters WHERE id=$1 AND patient_id=$2',[b.encounterId,exam.patientId])).rows[0];if(!encounter)return reply.code(400).send({error:'O atendimento selecionado não pertence ao paciente.'});if(b.marker&&encounter.status!=='IN_PROGRESS')return reply.code(409).send({error:'Marcadores só podem ser incluídos em atendimento em andamento.'});const client=await app.db.connect();try{await client.query('BEGIN');await client.query(`UPDATE patient_exam_uploads SET encounter_id=$1,clinical_interpretation=$2,status='REVIEWED',reviewed_at=now(),reviewed_by=$3 WHERE id=$4`,[b.encounterId,b.interpretation,request.auth!.userId,id]);if(b.marker)await client.query(`INSERT INTO laboratory_results(encounter_id,patient_id,exam_date,marker,value,unit,reference_value,status,observation) VALUES($1,$2,$3,$4,$5,$6,$7,$8,$9)`,[b.encounterId,exam.patientId,exam.examDate,b.marker.name,b.marker.value,b.marker.unit||null,b.marker.referenceValue||null,b.marker.status||null,`Origem: exame enviado pelo paciente. ${b.interpretation}`]);await client.query('COMMIT')}catch(error){await client.query('ROLLBACK');throw error}finally{client.release()}await audit(app.db,'PATIENT_EXAM_LINKED','patient_exam_upload',{actorUserId:request.auth!.userId,entityId:id,metadata:{patientId:exam.patientId,encounterId:b.encounterId,structuredMarker:Boolean(b.marker)}});return{message:b.marker?'Exame vinculado e marcador registrado.':'Exame vinculado ao prontuário.'}});
}
