const base=(process.env.SMOKE_BASE_URL||'').replace(/\/$/,'');
if(!base)throw new Error('Defina SMOKE_BASE_URL com a URL publicada.');
async function request(path,{expected=200,cookie,method='GET',body}={}){const response=await fetch(`${base}${path}`,{method,redirect:'manual',headers:{accept:'application/json',...(cookie?{cookie}:{}),...(body?{'content-type':'application/json'}:{})},body:body?JSON.stringify(body):undefined});const type=response.headers.get('content-type')||'';const payload=type.includes('application/json')?await response.json():await response.text();if(response.status!==expected){const detail=payload?.schema?.requiredMigration?` Migração exigida: ${payload.schema.requiredMigration}.`:payload?.error?` ${payload.error}`:'';throw new Error(`${method} ${path}: esperado ${expected}, recebido ${response.status}.${detail}`)}return{response,payload,type}}
console.log(`Homologando ${base}`);
const home=await request('/');if(!home.type.includes('text/html')||!String(home.payload).includes('id="root"'))throw new Error('A aplicação React não foi entregue corretamente.');console.log('✓ Aplicação React');
const health=await request('/health');if(health.payload?.status!=='ok'||health.payload?.schema?.ready!==true)throw new Error('Banco conectado, mas a estrutura ainda não está pronta.');console.log('✓ API, banco e migrações');
const identity=await request('/api/settings/public');if(!identity.payload?.data?.clinicName)throw new Error('Identidade pública do consultório incompleta.');console.log('✓ Identidade do consultório');
await request('/api/auth/me',{expected:401});console.log('✓ Proteção de sessão anônima');
const identifier=process.env.SMOKE_ADMIN_IDENTIFIER,password=process.env.SMOKE_ADMIN_PASSWORD;
if(identifier&&password){const login=await request('/api/auth/login',{method:'POST',body:{identifier,password}});const cookie=(login.response.headers.get('set-cookie')||'').split(';')[0];if(!cookie)throw new Error('Login não criou uma sessão segura.');await request('/api/auth/me',{cookie});await request('/api/settings/readiness',{cookie});await request('/api/patients',{cookie});await request('/api/finance/summary',{cookie});const today=new Date().toISOString().slice(0,10);await request(`/api/appointments?from=${today}&to=${today}`,{cookie});await request('/api/auth/logout',{cookie,method:'POST'});console.log('✓ Sessão profissional e módulos essenciais (somente leitura)')}else console.log('• Credenciais de homologação ausentes; etapa autenticada ignorada.');
console.log('Homologação concluída sem falhas.');
