import test from 'node:test';import assert from 'node:assert/strict';import{loadEnv}from'../src/config/env.js';
const base={NODE_ENV:'test',DATABASE_URL:'postgres://test:test@localhost/test',FRONTEND_ORIGIN:'http://localhost:5173',APP_URL:'http://localhost:5173',SMTP_FROM:'Nutri <teste@example.com>'};
test('environment applies secure operational defaults',()=>{const env=loadEnv(base);assert.equal(env.SESSION_TTL_HOURS,6);assert.equal(env.PASSWORD_RESET_TTL_MINUTES,30);assert.equal(env.PATIENT_INVITATION_TTL_HOURS,24);assert.equal(env.SESSION_COOKIE_NAME,'nutri_session');assert.equal(env.DB_POOL_MAX,2);assert.equal(env.DB_CONNECTION_TIMEOUT_MS,10000);assert.equal(env.DB_IDLE_TIMEOUT_MS,10000)});
test('environment rejects incomplete configuration',()=>{assert.throws(()=>loadEnv({NODE_ENV:'test'}),/DATABASE_URL/)});
test('environment rejects invalid public origins',()=>{assert.throws(()=>loadEnv({...base,FRONTEND_ORIGIN:'not-a-url'}),/FRONTEND_ORIGIN/)});
test('environment validates every legacy origin',()=>{assert.equal(loadEnv({...base,LEGACY_APP_ORIGINS:'https://old.example.com'}).LEGACY_APP_ORIGINS,'https://old.example.com');assert.throws(()=>loadEnv({...base,LEGACY_APP_ORIGINS:'https://old.example.com/path'}),/LEGACY_APP_ORIGINS/)});
test('environment accepts only a bare Vercel deployment hostname',()=>{assert.equal(loadEnv({...base,VERCEL_URL:'preview.example.vercel.app'}).VERCEL_URL,'preview.example.vercel.app');assert.throws(()=>loadEnv({...base,VERCEL_URL:'https://preview.example.vercel.app/path'}),/VERCEL_URL/)});
test('environment treats an empty optional cron secret as unconfigured',()=>{const env=loadEnv({...base,CRON_SECRET:''});assert.equal(env.CRON_SECRET,undefined)});
test('Vercel integration requires its complete credential set including slug',()=>{assert.throws(()=>loadEnv({...base,VERCEL_OAUTH_CLIENT_ID:'client',VERCEL_OAUTH_CLIENT_SECRET:'secret-secret',VERCEL_OAUTH_REDIRECT_URI:'https://central.example/callback'}),/VERCEL_OAUTH_CLIENT_ID/);assert.equal(loadEnv({...base,VERCEL_OAUTH_CLIENT_ID:'client',VERCEL_OAUTH_CLIENT_SECRET:'secret-secret',VERCEL_OAUTH_REDIRECT_URI:'https://central.example/callback',VERCEL_INTEGRATION_SLUG:'nutri-platform'}).VERCEL_INTEGRATION_SLUG,'nutri-platform')});
