import test from'node:test';import assert from'node:assert/strict';import{createHash,generateKeyPairSync,sign}from'node:crypto';import{deploySignedPreview,type ArtifactEntry,type PreviewUploadCapability,type SignedArtifactBundle}from'../src/modules/platform/preview-deployment-service.js';import type{VercelProvider}from'../src/integrations/vercel-provider.js';
const hash=(a:string,d:Uint8Array)=>createHash(a).update(d).digest('hex');const{privateKey,publicKey}=generateKeyPairSync('ed25519');
function bundle(entries:ArtifactEntry[]):SignedArtifactBundle{const manifest={version:1 as const,releaseId:'release-1',sourceCommit:'a'.repeat(40),files:entries.map(x=>({path:x.path,size:x.data.byteLength,sha256:hash('sha256',x.data)}))};const body=Buffer.from(JSON.stringify(manifest));return{manifest,digest:hash('sha256',body),signature:sign(null,body,privateKey).toString('base64url')}}
function fake(){const calls:any[]=[];const provider={uploadFile:async(x:any)=>{calls.push(['upload',x])},createPreviewDeployment:async(x:any)=>{calls.push(['preview',x]);return{id:'dpl_1',url:'preview.test',status:'QUEUED'}}}as unknown as VercelProvider&PreviewUploadCapability;return{provider,calls}}
const bytes=(x:string)=>Buffer.from(x);
test('validates, deduplicates content uploads and creates preview references',async()=>{const entries=[{path:'index.html',data:bytes('same')},{path:'copy.html',data:bytes('same')},{path:'assets/app.js',data:bytes('safe code')}],f=fake();const result=await deploySignedPreview({accessToken:'token',teamId:'team_1',projectId:'prj_1',projectName:'demo',bundle:bundle(entries),entries,publicKey},{provider:f.provider});assert.equal(result.uploadedFiles,2);assert.equal(result.referencedFiles,3);assert.equal(f.calls.filter(x=>x[0]==='upload').length,2);const preview=f.calls.at(-1);assert.equal(preview[0],'preview');assert.equal(preview[1].files.length,3);assert.equal(preview[1].teamId,'team_1');assert.equal('target'in preview[1],false);assert.equal(preview[1].files[0].sha,hash('sha1',entries[0]!.data))});
test('invalid signature or integrity fails before provider calls',async()=>{const entries=[{path:'index.html',data:bytes('safe')}];const badSignature=fake(),signed=bundle(entries);await assert.rejects(()=>deploySignedPreview({accessToken:'t',projectId:'p',projectName:'n',bundle:{...signed,signature:'invalid'},entries,publicKey},{provider:badSignature.provider}));assert.equal(badSignature.calls.length,0);const changed=fake();await assert.rejects(()=>deploySignedPreview({accessToken:'t',projectId:'p',projectName:'n',bundle:signed,entries:[{path:'index.html',data:bytes('changed')}],publicKey},{provider:changed.provider}));assert.equal(changed.calls.length,0)});
test('rejects forbidden paths, secrets, duplicates and limits before upload',async()=>{const cases:ArtifactEntry[][]=[[{path:'../x',data:bytes('x')}],[{path:'.env',data:bytes('x')}],[{path:'config.txt',data:bytes('password=very-secret-value')}],[{path:'a',data:bytes('x')},{path:'a',data:bytes('x')}]];for(const entries of cases){const f=fake();await assert.rejects(()=>deploySignedPreview({accessToken:'t',projectId:'p',projectName:'n',bundle:bundle(entries),entries,publicKey},{provider:f.provider}));assert.equal(f.calls.length,0)}const entries=[{path:'big.bin',data:bytes('1234')}],f=fake();await assert.rejects(()=>deploySignedPreview({accessToken:'t',projectId:'p',projectName:'n',bundle:bundle(entries),entries,publicKey,limits:{maxFileBytes:3}},{provider:f.provider}),/ARTIFACT_SIZE_LIMIT/);assert.equal(f.calls.length,0)});
test('partial upload failure prevents preview creation',async()=>{const entries=[{path:'a.txt',data:bytes('a')},{path:'b.txt',data:bytes('b')}],calls:any[]=[];const provider={uploadFile:async(x:any)=>{calls.push(['upload',x]);if(calls.length===2)throw new Error('upload failed')},createPreviewDeployment:async(x:any)=>calls.push(['preview',x])}as unknown as VercelProvider&PreviewUploadCapability;await assert.rejects(()=>deploySignedPreview({accessToken:'t',projectId:'p',projectName:'n',bundle:bundle(entries),entries,publicKey},{provider}));assert.equal(calls.some(x=>x[0]==='preview'),false)});
