import { CalendarDays, ChevronLeft, ChevronRight, Clock3, ExternalLink, Plus, UserRound, Video, X } from 'lucide-react';
import { useCallback, useEffect, useMemo, useState, type FormEvent } from 'react';
import { Link } from 'react-router-dom';
import { api } from '../lib/api';

type Patient = { id: string; name: string };
type AppointmentStatus = 'CONFIRMED'|'WAITING'|'IN_PROGRESS'|'COMPLETED'|'CANCELLED'|'NO_SHOW';
type Appointment = { id:string; patientId:string; patientName:string; whatsapp?:string|null; date:string; time:string; durationMinutes:number; type:string; price?:number|null; status:AppointmentStatus; notes?:string|null; meetingUrl?:string|null; patientResponse:'PENDING'|'CONFIRMED'|'RESCHEDULE_REQUESTED'; patientResponseNote?:string|null };
type FormState = { patientId:string; date:string; time:string; durationMinutes:string; type:string; price:string; status:AppointmentStatus; notes:string; meetingUrl:string };
type AppointmentRequest={id:string;patientId:string;patientName:string;preferredDate:string;preferredPeriod:'MORNING'|'AFTERNOON'|'EVENING';appointmentType:string;notes?:string|null;status:'PENDING'};
const statusLabels: Record<AppointmentStatus,string> = { CONFIRMED:'Confirmado', WAITING:'Aguardando', IN_PROGRESS:'Em atendimento', COMPLETED:'Concluído', CANCELLED:'Cancelado', NO_SHOW:'Não compareceu' };
const statusTransitions:Record<AppointmentStatus,AppointmentStatus[]>={
  CONFIRMED:['CONFIRMED','WAITING','IN_PROGRESS','COMPLETED','CANCELLED','NO_SHOW'],
  WAITING:['WAITING','CONFIRMED','IN_PROGRESS','COMPLETED','CANCELLED','NO_SHOW'],
  IN_PROGRESS:['IN_PROGRESS','COMPLETED'],
  COMPLETED:['COMPLETED'],
  CANCELLED:['CANCELLED'],
  NO_SHOW:['NO_SHOW']
};
const newAppointmentStatuses:AppointmentStatus[]=['CONFIRMED','WAITING'];
const types = ['Avaliação Inicial','Presencial','Online (Teleconsulta)','Retorno de Avaliação','Retorno Online'];
const pad = (value:number) => String(value).padStart(2,'0');
const isoDate = (date:Date) => `${date.getFullYear()}-${pad(date.getMonth()+1)}-${pad(date.getDate())}`;
const todayIso = isoDate(new Date());
const initialForm = (date=todayIso):FormState => ({ patientId:'', date, time:'09:00', durationMinutes:'60', type:types[0], price:'250', status:'CONFIRMED', notes:'', meetingUrl:'' });

export function AgendaPage() {
  const [month,setMonth]=useState(() => new Date(new Date().getFullYear(),new Date().getMonth(),1)); const [selected,setSelected]=useState(todayIso);
  const [appointments,setAppointments]=useState<Appointment[]>([]); const [patients,setPatients]=useState<Patient[]>([]); const [loading,setLoading]=useState(true); const [error,setError]=useState('');const[notice,setNotice]=useState('');
  const[requests,setRequests]=useState<AppointmentRequest[]>([]);const[requestId,setRequestId]=useState<string|null>(null);const[editingId,setEditingId]=useState<string|null>(null);const[rebooking,setRebooking]=useState(false);
  const [open,setOpen]=useState(false); const [form,setForm]=useState<FormState>(()=>initialForm()); const [saving,setSaving]=useState(false);
  const range=useMemo(()=>({from:isoDate(new Date(month.getFullYear(),month.getMonth(),1)),to:isoDate(new Date(month.getFullYear(),month.getMonth()+1,0))}),[month]);
  const load=useCallback(async()=>{setLoading(true);setError('');try{const[result,pending]=await Promise.all([api<{data:Appointment[]}>(`/api/appointments?from=${range.from}&to=${range.to}`),api<{data:AppointmentRequest[]}>('/api/appointments/requests')]);setAppointments(result.data);setRequests(pending.data)}catch(cause){setError(cause instanceof Error?cause.message:'Erro ao carregar agenda.')}finally{setLoading(false)}},[range]);
  useEffect(()=>{void load()},[load]);
  useEffect(()=>{api<{data:Patient[]}>('/api/patients').then(r=>setPatients(r.data)).catch(()=>undefined)},[]);
  const selectedItems=appointments.filter(item=>item.date.slice(0,10)===selected);
  const editingAppointment=editingId?appointments.find(item=>item.id===editingId):undefined;
  const scheduleChanged=Boolean(editingAppointment&&(form.date!==editingAppointment.date.slice(0,10)||form.time!==editingAppointment.time.slice(0,5)));
  const formStatuses=editingAppointment
    ? [...new Set([...statusTransitions[editingAppointment.status],...(scheduleChanged&&['CANCELLED','NO_SHOW'].includes(editingAppointment.status)?newAppointmentStatuses:[])])]
    : newAppointmentStatuses;
  const cells=useMemo(()=>{const first=new Date(month.getFullYear(),month.getMonth(),1);const start=new Date(first);start.setDate(1-first.getDay());return Array.from({length:42},(_,i)=>{const date=new Date(start);date.setDate(start.getDate()+i);return date})},[month]);
  function showCreate(date=selected){setRequestId(null);setEditingId(null);setRebooking(false);setForm(initialForm(date));setOpen(true)}
  function showEdit(item:Appointment){setRequestId(null);setEditingId(item.id);setRebooking(item.patientResponse==='RESCHEDULE_REQUESTED');setForm({patientId:item.patientId,date:item.date.slice(0,10),time:item.time.slice(0,5),durationMinutes:String(item.durationMinutes),type:item.type,price:item.price==null?'':String(item.price),status:item.status,notes:item.notes||'',meetingUrl:item.meetingUrl||''});setOpen(true)}
  function approveRequest(item:AppointmentRequest){const time={MORNING:'09:00',AFTERNOON:'14:00',EVENING:'18:00'}[item.preferredPeriod];setRequestId(item.id);setEditingId(null);setRebooking(false);setForm({...initialForm(item.preferredDate),patientId:item.patientId,time,type:item.appointmentType,notes:item.notes||''});setSelected(item.preferredDate);setMonth(new Date(`${item.preferredDate}T12:00:00`));setOpen(true)}
  async function declineRequest(item:AppointmentRequest){if(!window.confirm(`Recusar a solicitação de ${item.patientName}?`))return;try{await api(`/api/appointments/requests/${item.id}`,{method:'PATCH',body:JSON.stringify({status:'DECLINED'})});setNotice('Solicitação atualizada e paciente notificado no portal.');await load()}catch(cause){setError(cause instanceof Error?cause.message:'Não foi possível atualizar a solicitação.')}}
  async function save(event:FormEvent){event.preventDefault();setSaving(true);setError('');setNotice('');try{const payload={patientId:form.patientId,date:form.date,time:form.time,durationMinutes:Number(form.durationMinutes),type:form.type,price:form.price?Number(form.price):undefined,status:form.status,notes:form.notes||undefined,meetingUrl:form.meetingUrl||undefined,...(!editingId&&requestId?{requestId}:{})};if(editingId){const result=await api<{data:{emailSent:boolean|null;warning?:string|null}}>(`/api/appointments/${editingId}`,{method:'PATCH',body:JSON.stringify(payload)});setNotice(result.data.emailSent?'Consulta atualizada e paciente avisado por e-mail e no portal.':result.data.warning||'Consulta atualizada e paciente notificado no portal.')}else{const result=await api<{data:{emailSent:boolean;warning?:string|null}}>('/api/appointments',{method:'POST',body:JSON.stringify(payload)});setNotice(result.data.emailSent?'Consulta criada e confirmação enviada por e-mail.':result.data.warning||'Consulta criada.')}setOpen(false);setRequestId(null);setEditingId(null);setSelected(form.date);await load()}catch(cause){setError(cause instanceof Error?cause.message:'Não foi possível salvar a consulta.')}finally{setSaving(false)}}
  async function updateStatus(item:Appointment,status:AppointmentStatus){try{const result=await api<{data:{emailSent:boolean|null;warning?:string|null}}>(`/api/appointments/${item.id}`,{method:'PATCH',body:JSON.stringify({status})});if(status==='CANCELLED')setNotice(result.data.emailSent?'Consulta cancelada e paciente avisado por e-mail e no portal.':result.data.warning||'Consulta cancelada e paciente notificado no portal.');await load()}catch(cause){setError(cause instanceof Error?cause.message:'Não foi possível alterar o status.')}}
  return <div><div className="page-intro"><div><p>Organize consultas e inicie o atendimento a partir de uma visão única.</p></div><button className="primary-button" onClick={()=>showCreate()}><Plus size={18}/> Nova consulta</button></div>{error&&<div className="form-error" role="alert">{error}</div>}{notice&&<div className="form-success">{notice}</div>}{requests.length>0&&<section className="panel appointment-requests"><div className="panel-heading"><div><span className="eyebrow">Portal do paciente</span><h3>Solicitações pendentes</h3></div><strong>{requests.length}</strong></div><div>{requests.map(item=><article key={item.id}><CalendarDays/><div><strong>{item.patientName}</strong><span>{new Date(`${item.preferredDate}T12:00:00`).toLocaleDateString('pt-BR')} · {{MORNING:'Manhã',AFTERNOON:'Tarde',EVENING:'Noite'}[item.preferredPeriod]} · {item.appointmentType}</span>{item.notes&&<small>{item.notes}</small>}</div><button className="secondary-button" onClick={()=>void declineRequest(item)}>Recusar</button><button className="primary-button" onClick={()=>approveRequest(item)}>Agendar</button></article>)}</div></section>}
    <div className="agenda-layout"><section className="panel calendar-panel"><div className="calendar-heading"><button className="icon-button" onClick={()=>setMonth(new Date(month.getFullYear(),month.getMonth()-1,1))}><ChevronLeft size={19}/></button><h2>{month.toLocaleDateString('pt-BR',{month:'long',year:'numeric'})}</h2><button className="icon-button" onClick={()=>setMonth(new Date(month.getFullYear(),month.getMonth()+1,1))}><ChevronRight size={19}/></button></div><div className="calendar-weekdays">{['Dom','Seg','Ter','Qua','Qui','Sex','Sáb'].map(day=><span key={day}>{day}</span>)}</div><div className="calendar-grid">{cells.map(date=>{const value=isoDate(date);const count=appointments.filter(a=>a.date.slice(0,10)===value).length;return <button key={value} className={`${date.getMonth()!==month.getMonth()?'outside ':''}${value===selected?'selected ':''}${value===todayIso?'today':''}`} onClick={()=>setSelected(value)}><span>{date.getDate()}</span>{count>0&&<small>{count}</small>}</button>})}</div><div className="calendar-legend"><span><i/> Dia com consulta</span><button className="text-link" onClick={()=>{const now=new Date();setMonth(new Date(now.getFullYear(),now.getMonth(),1));setSelected(todayIso)}}>Ir para hoje</button></div></section>
      <section className="panel day-panel"><div className="panel-heading"><div><span className="eyebrow">Agenda do dia</span><h3>{new Date(`${selected}T12:00:00`).toLocaleDateString('pt-BR',{weekday:'long',day:'numeric',month:'long'})}</h3></div><button className="icon-button" onClick={()=>showCreate(selected)} aria-label="Agendar neste dia"><Plus size={20}/></button></div>{loading?<div className="empty-state"><span className="spinner"/><strong>Carregando agenda...</strong></div>:selectedItems.length===0?<div className="empty-state"><CalendarDays size={32}/><strong>Nenhuma consulta neste dia</strong><p>Escolha outro dia ou adicione um novo horário.</p><button className="secondary-button" onClick={()=>showCreate(selected)}><Plus size={17}/> Agendar consulta</button></div>:<div className="appointment-list">{selectedItems.map(item=><article className={`appointment-card response-${item.patientResponse.toLowerCase()}`} key={item.id}><div className="appointment-time"><strong>{item.time}</strong><small>{item.durationMinutes} min</small></div><div className="appointment-info"><strong>{item.patientName}</strong><span>{item.type}</span><small>{item.patientResponse==='RESCHEDULE_REQUESTED'?`Reagendamento: ${item.patientResponseNote}`:item.patientResponse==='CONFIRMED'?'Paciente confirmou presença':'Aguardando confirmação do paciente'}</small></div><select className={`appointment-status status-${item.status.toLowerCase()}`} value={item.status} onChange={e=>void updateStatus(item,e.target.value as AppointmentStatus)}>{statusTransitions[item.status].map(value=><option key={value} value={value}>{statusLabels[value]}</option>)}</select><div className="appointment-actions">{item.patientResponse==='RESCHEDULE_REQUESTED'&&<button className="secondary-button" onClick={()=>showEdit(item)}>Reagendar</button>}{item.meetingUrl&&<a className="icon-button" href={item.meetingUrl} target="_blank" rel="noreferrer" title="Abrir teleconsulta"><Video size={17}/></a>}<Link className="start-care" to={`/atendimentos?paciente=${item.patientId}&agendamento=${item.id}`}>Atender <ChevronRight size={16}/></Link></div></article>)}</div>}</section></div>
    {open&&<div className="modal-backdrop" onMouseDown={e=>{if(e.target===e.currentTarget)setOpen(false)}}><section className="modal" role="dialog" aria-modal="true" aria-labelledby="appointment-title"><div className="modal-heading"><div><span className="eyebrow">Agenda clínica</span><h2 id="appointment-title">{rebooking?'Reagendar consulta':editingId?'Editar consulta':'Nova consulta'}</h2></div><button className="icon-button" onClick={()=>setOpen(false)}><X size={20}/></button></div><form onSubmit={save}><div className="form-grid"><label className="full">Paciente<select value={form.patientId} onChange={e=>setForm({...form,patientId:e.target.value})} required><option value="">Selecione um paciente</option>{patients.map(patient=><option value={patient.id} key={patient.id}>{patient.name}</option>)}</select></label><label>Data<input type="date" value={form.date} onChange={e=>setForm({...form,date:e.target.value})} required/></label><label>Horário<input type="time" value={form.time} onChange={e=>setForm({...form,time:e.target.value})} required/></label><label>Tipo<select value={form.type} onChange={e=>setForm({...form,type:e.target.value})}>{types.map(type=><option key={type}>{type}</option>)}</select></label><label>Duração<select value={form.durationMinutes} onChange={e=>setForm({...form,durationMinutes:e.target.value})}><option value="30">30 minutos</option><option value="45">45 minutos</option><option value="60">60 minutos</option><option value="90">90 minutos</option></select></label><label>Valor (R$)<input type="number" min="0" step="0.01" value={form.price} onChange={e=>setForm({...form,price:e.target.value})}/></label><label>Status<select value={form.status} onChange={e=>setForm({...form,status:e.target.value as AppointmentStatus})}>{formStatuses.map(value=><option key={value} value={value}>{statusLabels[value]}</option>)}</select></label>{form.type.toLowerCase().includes('online')&&<label className="full">Link da teleconsulta<div className="input-with-icon"><Video size={17}/><input type="url" value={form.meetingUrl} onChange={e=>setForm({...form,meetingUrl:e.target.value})} placeholder="https://..."/></div></label>}<label className="full">Observações<textarea rows={3} value={form.notes} onChange={e=>setForm({...form,notes:e.target.value})} placeholder="Ex.: trazer exames laboratoriais"/></label></div>{patients.length===0&&<div className="inline-guidance"><UserRound size={18}/><span>Cadastre um paciente antes de criar a consulta.</span><Link to="/pacientes">Ir para pacientes <ExternalLink size={14}/></Link></div>}<div className="modal-actions"><button type="button" className="secondary-button" onClick={()=>setOpen(false)}>Cancelar</button><button className="primary-button" disabled={saving||patients.length===0}>{saving?'Salvando...':<><Clock3 size={17}/> {rebooking?'Confirmar reagendamento':editingId?'Salvar consulta':'Confirmar consulta'}</>}</button></div></form></section></div>}</div>;
}
