import { AlertTriangle, CheckCircle2, ClipboardCheck, FlaskConical, HeartPulse, Pill, Plus, X } from 'lucide-react';
import { useCallback, useEffect, useState } from 'react';
import { useParams } from 'react-router-dom';
import { api } from '../lib/api';
import '../clinical-overview.css';

type Problem={id:string;title:string;status:'ACTIVE'|'MONITORING'|'CONTROLLED'|'RESOLVED';onsetDate?:string;conduct?:string;notes?:string};
type Therapy={id:string;kind:'MEDICATION'|'SUPPLEMENT';name:string;dosage?:string;schedule?:string;indication?:string;status:'ACTIVE'|'PAUSED'|'FINISHED'};
type Task={id:string;title:string;details?:string;dueDate?:string;priority:'LOW'|'NORMAL'|'HIGH';status:'OPEN'|'DONE'|'CANCELLED'};
type Lab={id:string;examDate?:string;marker:string;value:string;unit?:string;status?:string};
type Alert={key:string;severity:'INFO'|'WARNING'|'HIGH';title:string;detail:string};
type Summary={patient:{id:string;name:string;objective?:string;birthDate?:string};clinicalContext:{allergies?:string;medications?:string;diagnosticImpression?:string;goals?:string;lastSavedAt?:string};problems:Problem[];therapies:Therapy[];tasks:Task[];labs:Lab[];alerts:Alert[]};

const statusLabel:Record<string,string>={ACTIVE:'Ativo',MONITORING:'Em acompanhamento',CONTROLLED:'Controlado',RESOLVED:'Resolvido',PAUSED:'Pausado',FINISHED:'Finalizado',OPEN:'Pendente',DONE:'Concluída',CANCELLED:'Cancelada'};
export function ClinicalOverviewPage(){
 const {patientId}=useParams(); const [data,setData]=useState<Summary|null>(null);const[error,setError]=useState('');const[busy,setBusy]=useState(true);const[dialog,setDialog]=useState<'problem'|'therapy'|'task'|null>(null);
 const load=useCallback(async()=>{if(!patientId)return;setBusy(true);try{setData((await api<{data:Summary}>(`/api/clinical/patients/${patientId}/summary`)).data);setError('')}catch(e){setError(e instanceof Error?e.message:'Não foi possível carregar o resumo clínico.')}finally{setBusy(false)}},[patientId]);useEffect(()=>{void load()},[load]);
 async function patch(path:string,body:object){await api(`/api/clinical/patients/${patientId}/${path}`,{method:'PATCH',body:JSON.stringify(body)});await load()}
 async function dismiss(key:string){await api(`/api/clinical/patients/${patientId}/alerts/${encodeURIComponent(key)}/dismiss`,{method:'POST'});await load()}
 if(busy&&!data)return <div className="clinical-overview-state">Carregando visão clínica…</div>;if(error&&!data)return <div className="clinical-overview-state error">{error}</div>;if(!data)return null;
 const activeProblems=data.problems.filter(x=>x.status!=='RESOLVED'),activeTherapies=data.therapies.filter(x=>x.status==='ACTIVE'),openTasks=data.tasks.filter(x=>x.status==='OPEN');
 return <main className="clinical-overview">
  <header className="clinical-hero"><div><span>RESUMO CLÍNICO VIVO</span><h1>{data.patient.name}</h1><p>{data.patient.objective||'Objetivo terapêutico ainda não registrado.'}</p></div><div className="clinical-counts"><strong>{activeProblems.length}</strong><small>problemas ativos</small><strong>{openTasks.length}</strong><small>pendências</small></div></header>
  {data.alerts.length>0&&<section className="clinical-alerts" aria-label="Alertas clÃ­nicos"><h2><AlertTriangle/> AtenÃ§Ã£o antes da conduta</h2>{data.alerts.map(a=><article key={a.key} className={`alert-${a.severity.toLowerCase()}`}><div><strong>{a.title}</strong><p>{a.detail}</p></div><button aria-label="Dispensar alerta" onClick={()=>void dismiss(a.key)}><X/></button></article>)}</section>}
  <section className="clinical-snapshot" aria-label="Contexto clÃ­nico essencial"><div><span>Alergias e intolerÃ¢ncias</span><strong>{data.clinicalContext.allergies||'NÃ£o registradas'}</strong></div><div><span>Medicamentos relatados</span><strong>{data.clinicalContext.medications||'NÃ£o registrados'}</strong></div><div><span>ImpressÃ£o diagnÃ³stica</span><strong>{data.clinicalContext.diagnosticImpression||'NÃ£o registrada'}</strong></div><div><span>Metas acordadas</span><strong>{data.clinicalContext.goals||'NÃ£o registradas'}</strong></div></section>
  <div className="clinical-grid">
   <ClinicalCard icon={<HeartPulse/>} title="Problemas longitudinais" action={()=>setDialog('problem')}>{data.problems.length?data.problems.map(p=><article className="clinical-row" key={p.id}><div><strong>{p.title}</strong><p>{p.conduct||'Conduta ainda nÃ£o descrita'}</p></div><select aria-label={`Estado de ${p.title}`} value={p.status} onChange={e=>void patch(`problems/${p.id}`,{status:e.target.value})}>{['ACTIVE','MONITORING','CONTROLLED','RESOLVED'].map(s=><option key={s} value={s}>{statusLabel[s]}</option>)}</select></article>):<Empty text="Nenhum problema registrado"/>}</ClinicalCard>
   <ClinicalCard icon={<Pill/>} title="Medicamentos e suplementos" action={()=>setDialog('therapy')}>{activeTherapies.length?activeTherapies.map(t=><article className="clinical-row" key={t.id}><div><span className="clinical-tag">{t.kind==='MEDICATION'?'Medicamento':'Suplemento'}</span><strong>{t.name} {t.dosage&&`Â· ${t.dosage}`}</strong><p>{t.schedule||t.indication||'Posologia nÃ£o informada'}</p></div><button className="text-button" onClick={()=>void patch(`therapies/${t.id}`,{status:'FINISHED'})}>Finalizar</button></article>):<Empty text="Nenhuma terapia ativa"/>}</ClinicalCard>
   <ClinicalCard icon={<ClipboardCheck/>} title="Plano de acompanhamento" action={()=>setDialog('task')}>{openTasks.length?openTasks.map(t=><article className={`clinical-row priority-${t.priority.toLowerCase()}`} key={t.id}><div><strong>{t.title}</strong><p>{t.dueDate?`Prazo: ${new Date(`${t.dueDate}T12:00:00`).toLocaleDateString('pt-BR')}`:'Sem prazo definido'}</p></div><button className="complete-button" onClick={()=>void patch(`tasks/${t.id}`,{status:'DONE'})}><CheckCircle2/> Concluir</button></article>):<Empty text="Nenhuma pendÃªncia aberta"/>}</ClinicalCard>
   <ClinicalCard icon={<FlaskConical/>} title="Exames recentes">{data.labs.length?data.labs.slice(0,8).map(l=><article className="clinical-row" key={l.id}><div><strong>{l.marker}</strong><p>{l.examDate?new Date(`${l.examDate}T12:00:00`).toLocaleDateString('pt-BR'):'Sem data'}</p></div><div className="lab-result"><strong>{l.value} {l.unit}</strong>{l.status&&<span>{l.status}</span>}</div></article>):<Empty text="Nenhum resultado estruturado"/>}</ClinicalCard>
  </div>
  {dialog&&<QuickCreate kind={dialog} patientId={patientId!} close={()=>setDialog(null)} saved={async()=>{setDialog(null);await load()}}/>}
 </main>
}
function ClinicalCard({icon,title,action,children}:{icon:React.ReactNode;title:string;action?:()=>void;children:React.ReactNode}){return <section className="clinical-card"><header><h2>{icon}{title}</h2>{action&&<button onClick={action}><Plus/>Adicionar</button>}</header><div>{children}</div></section>}
function Empty({text}:{text:string}){return <div className="clinical-empty">{text}</div>}
function QuickCreate({kind,patientId,close,saved}:{kind:'problem'|'therapy'|'task';patientId:string;close:()=>void;saved:()=>void}){const[title,setTitle]=useState('');const[extra,setExtra]=useState('');const[type,setType]=useState('SUPPLEMENT');const[date,setDate]=useState('');const[busy,setBusy]=useState(false);const labels={problem:'Novo problema clÃ­nico',therapy:'Novo medicamento ou suplemento',task:'Nova pendÃªncia'};async function submit(e:React.FormEvent){e.preventDefault();setBusy(true);const endpoint=kind==='problem'?'problems':kind==='therapy'?'therapies':'tasks';const body=kind==='problem'?{title,conduct:extra}:kind==='therapy'?{name:title,kind:type,dosage:extra}:{title,details:extra,dueDate:date||null};try{await api(`/api/clinical/patients/${patientId}/${endpoint}`,{method:'POST',body:JSON.stringify(body)});await saved()}finally{setBusy(false)}}return <div className="clinical-dialog-backdrop" role="presentation" onMouseDown={e=>{if(e.currentTarget===e.target)close()}}><form className="clinical-dialog" onSubmit={e=>void submit(e)}><header><h2>{labels[kind]}</h2><button type="button" onClick={close}><X/></button></header>{kind==='therapy'&&<label>Tipo<select value={type} onChange={e=>setType(e.target.value)}><option value="SUPPLEMENT">Suplemento</option><option value="MEDICATION">Medicamento</option></select></label>}<label>{kind==='therapy'?'Nome':'TÃ­tulo'}<input autoFocus required minLength={2} value={title} onChange={e=>setTitle(e.target.value)}/></label><label>{kind==='problem'?'Conduta':kind==='therapy'?'Dose':'Detalhes'}<textarea value={extra} onChange={e=>setExtra(e.target.value)}/></label>{kind==='task'&&<label>Prazo<input type="date" value={date} onChange={e=>setDate(e.target.value)}/></label>}<button className="save-clinical" disabled={busy}>{busy?'Salvandoâ€¦':'Salvar registro'}</button></form></div>}
