import { Check, CheckCircle2, ChevronLeft, ChevronRight, ClipboardList, FileCheck2, LockKeyhole, Plus, Save, UserRound, UtensilsCrossed, Video } from 'lucide-react';
import { useCallback, useEffect, useMemo, useState } from 'react';
import { useSearchParams } from 'react-router-dom';
import { VideoConsultation } from '../components/VideoConsultation';
import { LabsList, SupplementsList, type Lab, type Supplement } from '../components/ClinicalLists';
import { PatientHistory } from '../components/PatientHistory';
import { api } from '../lib/api';

type SectionKey='context'|'anamnesis'|'recall24h'|'followup'|'assessment'|'exams'|'conduct'|'plan'|'supplements'|'notes';
type Value=string|number|boolean|null;
type SectionData=Record<string,Value>;
type Patient={id:string;name:string;objective?:string|null};
type Checkin={id:string;answers:Record<string,unknown>;status:'PENDING_REVIEW'|'REVIEWED';submittedAt:string;reviewedAt?:string|null};
type Encounter={id:string;patientId:string;patientName:string;objective?:string|null;appointmentId?:string|null;videoRoomToken?:string|null;status:'IN_PROGRESS'|'COMPLETED';startedAt:string;sections:Partial<Record<SectionKey,{data:SectionData;savedAt:string}>>;labs:Lab[];supplements:Supplement[];checkins:Checkin[]};
type Field={key:string;label:string;type?:'text'|'textarea'|'number'|'select'|'date'|'time';placeholder?:string;options?:string[];suffix?:string;profiles?:string[]};
type Step={key:SectionKey|'review';label:string;description:string;fields?:Field[]};

const yesNo=['Não','Sim'];
const steps:Step[]=[
 {key:'context',label:'Contexto',description:'Identificação social e motivo da consulta',fields:[
  {key:'mainComplaint',label:'Queixa principal',type:'textarea',placeholder:'O que trouxe o paciente à consulta?'},{key:'expectations',label:'Expectativas',type:'textarea'},{key:'consultationType',label:'Tipo de atendimento',type:'select',options:['Primeira consulta','Retorno','Reavaliação','Intercorrência']},
  {key:'education',label:'Escolaridade'},{key:'profession',label:'Profissão'},{key:'maritalStatus',label:'Estado civil'},{key:'income',label:'Renda familiar'},{key:'dependents',label:'Dependentes',type:'number'}]},
 {key:'anamnesis',label:'Anamnese',description:'História clínica, hábitos e alimentação',fields:[
  {key:'clinicalHistory',label:'Histórico de saúde',type:'textarea'},{key:'medications',label:'Medicamentos em uso',type:'textarea'},{key:'familyHistory',label:'Histórico familiar',type:'textarea'},{key:'allergies',label:'Alergias e intolerâncias',type:'textarea'},
  {key:'smoking',label:'Tabagismo',type:'select',options:yesNo},{key:'alcohol',label:'Consumo de álcool',type:'select',options:['Não','Socialmente','Frequentemente']},{key:'waterIntake',label:'Consumo de água',placeholder:'Ex.: 2 litros/dia'},{key:'bowelFunction',label:'Função intestinal',type:'select',options:['Regular','Constipação','Diarreia','Alternado']},
  {key:'emotionalSymptoms',label:'Sintomas emocionais'},{key:'foodPreferences',label:'Preferências e aversões',type:'textarea'},{key:'foodRoutine',label:'Rotina alimentar atual',type:'textarea'},{key:'sleep',label:'Sono'},{key:'physicalActivity',label:'Atividade física',type:'textarea'},{key:'objective',label:'Objetivo do acompanhamento',type:'textarea'}]},
 {key:'recall24h',label:'Recordatório 24h',description:'Consumo alimentar do dia anterior',fields:[
  {key:'wakeTime',label:'Horário que acordou',type:'time'},{key:'breakfast',label:'Café da manhã',type:'textarea',placeholder:'Horário, alimentos e quantidades'},{key:'morningSnack',label:'Lanche da manhã',type:'textarea'},{key:'lunch',label:'Almoço',type:'textarea'},{key:'afternoonSnack',label:'Lanche da tarde',type:'textarea'},{key:'dinner',label:'Jantar',type:'textarea'},{key:'supper',label:'Ceia',type:'textarea'},{key:'otherIntake',label:'Outros consumos e observações',type:'textarea'}]},
 {key:'assessment',label:'Avaliação corporal',description:'Antropometria, bioimpedância e energia',fields:[
  {key:'clinicalProfile',label:'Perfil de avaliação',type:'select',options:['Adulto','Gestante','Pediatria']},{key:'assessmentDate',label:'Data da avaliação',type:'date'},{key:'sex',label:'Sexo para cálculo energético',type:'select',options:['Feminino','Masculino']},{key:'age',label:'Idade',type:'number',suffix:'anos'},{key:'weight',label:'Peso',type:'number',suffix:'kg'},{key:'height',label:'Altura',type:'number',suffix:'cm'},
  {key:'prePregnancyWeight',label:'Peso pré-gestacional',type:'number',suffix:'kg',profiles:['Gestante']},{key:'gestationalWeek',label:'Semana gestacional',type:'number',suffix:'sem',profiles:['Gestante']},{key:'pregnancyNumber',label:'Número de gestações',type:'number',profiles:['Gestante']},{key:'pregnancySymptoms',label:'Sintomas e intercorrências gestacionais',type:'textarea',profiles:['Gestante']},
  {key:'birthWeight',label:'Peso ao nascer',type:'number',suffix:'kg',profiles:['Pediatria']},{key:'gestationalAgeAtBirth',label:'Idade gestacional ao nascer',type:'number',suffix:'sem',profiles:['Pediatria']},{key:'headCircumference',label:'Perímetro cefálico',type:'number',suffix:'cm',profiles:['Pediatria']},{key:'caregiver',label:'Responsável e vínculo',profiles:['Pediatria']},{key:'breastfeeding',label:'Aleitamento',type:'select',options:['Exclusivo','Misto','Encerrado','Não realizado'],profiles:['Pediatria']},{key:'foodIntroduction',label:'Introdução alimentar e desenvolvimento',type:'textarea',profiles:['Pediatria']},
  {key:'bodyFat',label:'Gordura corporal',type:'number',suffix:'%'},{key:'leanMass',label:'Massa magra',type:'number',suffix:'kg'},{key:'muscleMass',label:'Massa muscular',type:'number',suffix:'kg'},{key:'visceralFat',label:'Gordura visceral',type:'number'},{key:'bodyWater',label:'Água corporal',type:'number',suffix:'%'},{key:'metabolicAge',label:'Idade metabólica',type:'number'},
  {key:'arm',label:'Braço',type:'number',suffix:'cm'},{key:'chest',label:'Tórax',type:'number',suffix:'cm'},{key:'waist',label:'Cintura',type:'number',suffix:'cm'},{key:'abdomen',label:'Abdômen',type:'number',suffix:'cm'},{key:'hip',label:'Quadril',type:'number',suffix:'cm'},{key:'calf',label:'Panturrilha',type:'number',suffix:'cm'},
  {key:'activityFactor',label:'Fator de atividade',type:'select',options:['1.2 - Sedentário','1.375 - Leve','1.55 - Moderado','1.725 - Intenso','1.9 - Extremamente ativo']},{key:'bicipitalFold',label:'Dobra bicipital',type:'number',suffix:'mm'},{key:'tricipitalFold',label:'Dobra tricipital',type:'number',suffix:'mm'},{key:'suprailiacFold',label:'Dobra suprailíaca',type:'number',suffix:'mm'},{key:'subscapularFold',label:'Dobra subescapular',type:'number',suffix:'mm'},{key:'assessmentNotes',label:'Observações da avaliação',type:'textarea'}]},
 {key:'exams',label:'Exames',description:'Resultados e interpretação laboratorial',fields:[{key:'examDate',label:'Data dos exames',type:'date'},{key:'markers',label:'Marcadores e resultados',type:'textarea',placeholder:'Ex.: Glicemia 92 mg/dL; Ferritina 45 ng/mL'},{key:'referenceRanges',label:'Valores de referência',type:'textarea'},{key:'interpretation',label:'Interpretação clínica',type:'textarea'},{key:'pendingExams',label:'Exames a solicitar ou acompanhar',type:'textarea'}]},
 {key:'conduct',label:'Conduta',description:'Diagnóstico nutricional e próximos passos',fields:[{key:'diagnosticImpression',label:'Impressão diagnóstica nutricional',type:'textarea'},{key:'goals',label:'Metas acordadas',type:'textarea'},{key:'guidance',label:'Orientações e estratégia alimentar',type:'textarea'},{key:'followUp',label:'Prazo e plano de acompanhamento',type:'textarea'}]},
 {key:'plan',label:'Plano alimentar',description:'Refeições, TACO, receitas e macros'},
 {key:'supplements',label:'Suplementação',description:'Prescrição e orientações',fields:[{key:'prescription',label:'Suplementos e fitoterápicos',type:'textarea',placeholder:'Nome, dose, forma e posologia'},{key:'supplementGuidance',label:'Orientações adicionais',type:'textarea'}]},
 {key:'notes',label:'Anotações',description:'Evolução e registro clínico livre',fields:[{key:'evolution',label:'Evolução e conduta',type:'textarea'},{key:'privateNotes',label:'Anotações profissionais',type:'textarea'}]},
 {key:'followup',label:'Retorno',description:'Adesão, evolução e dificuldades',fields:[
  {key:'dietRating',label:'Avaliação da alimentação',type:'select',options:['Muito boa','Boa','Regular','Ruim']},{key:'planAdherence',label:'Seguimento do plano',type:'select',options:['Integral','Parcial','Não seguiu']},{key:'routineChanged',label:'Mudança de rotina',type:'select',options:yesNo},{key:'routineChangeDetails',label:'Qual mudança?'},
  {key:'difficultMeals',label:'Refeições com maior dificuldade'},{key:'hungerLevel',label:'Fome e saciedade'},{key:'bingeEating',label:'Compulsão ou exageros',type:'select',options:yesNo},{key:'bingeContext',label:'Situações de compulsão'},{key:'dailyWater',label:'Água diária'},{key:'alcoholUse',label:'Consumo de álcool',type:'select',options:yesNo},{key:'alcoholFrequency',label:'Frequência do álcool'},
  {key:'energy',label:'Energia e disposição'},{key:'sleepChanges',label:'Alterações no sono'},{key:'newMedication',label:'Novo medicamento',type:'select',options:yesNo},{key:'newMedicationDetails',label:'Qual medicamento?'},{key:'activityStatus',label:'Atividade física',type:'select',options:['Não pratica','Iniciou','Manteve','Aumentou','Reduziu']},{key:'activityFrequency',label:'Frequência de atividade'},{key:'trainingPerformance',label:'Desempenho no treino'},
  {key:'perceivedWeightChange',label:'Mudança corporal percebida',type:'textarea'},{key:'positiveResults',label:'Resultados positivos',type:'textarea'},{key:'mainDifficulties',label:'Maiores dificuldades',type:'textarea'},{key:'nextGoal',label:'Meta para o próximo período',type:'textarea'},{key:'desiredPlanAdjustment',label:'Ajustes desejados no plano',type:'textarea'},{key:'additionalNotes',label:'Observações do retorno',type:'textarea'}]},
 {key:'review',label:'Revisão',description:'Conferência e finalização'}
];

function missingClinicalCore(sections:Encounter['sections']){
 const missing:string[]=[];
 if(!sections.context)missing.push('Contexto');
 if(!sections.anamnesis&&!sections.followup)missing.push('Anamnese ou Retorno');
 if(!sections.conduct)missing.push('Conduta');
 return missing;
}

export function EncounterPage(){
 const[params,setParams]=useSearchParams();const patientParam=params.get('paciente')||'';const appointmentParam=params.get('agendamento')||'';const videoParam=params.get('video')==='true';
 const[patients,setPatients]=useState<Patient[]>([]);const[patientId,setPatientId]=useState(patientParam);const[encounter,setEncounter]=useState<Encounter|null>(null);const[active,setActive]=useState(0);const[drafts,setDrafts]=useState<Partial<Record<SectionKey,SectionData>>>({});const[dirtyKeys,setDirtyKeys]=useState<Set<SectionKey>>(new Set());const[loading,setLoading]=useState(false);const[saving,setSaving]=useState(false);const[error,setError]=useState('');const[notice,setNotice]=useState('');const[videoOpen,setVideoOpen]=useState(videoParam);
 useEffect(()=>{api<{data:Patient[]}>('/api/patients').then(r=>setPatients(r.data)).catch(c=>setError(c instanceof Error?c.message:'Erro ao carregar pacientes.'))},[]);
 const loadEncounter=useCallback(async(id:string)=>{setLoading(true);try{const r=await api<{data:Encounter}>(`/api/encounters/${id}`);setEncounter(r.data);const loaded:Partial<Record<SectionKey,SectionData>>={};for(const key of steps.map(s=>s.key).filter(k=>k!=='review') as SectionKey[])loaded[key]=r.data.sections[key]?.data||{};setDrafts(loaded);setDirtyKeys(new Set())}catch(c){setError(c instanceof Error?c.message:'Erro ao abrir atendimento.')}finally{setLoading(false)}},[]);
 useEffect(()=>{const warn=(event:BeforeUnloadEvent)=>{if(dirtyKeys.size){event.preventDefault();event.returnValue=''}};window.addEventListener('beforeunload',warn);return()=>window.removeEventListener('beforeunload',warn)},[dirtyKeys]);
 useEffect(()=>{const id=params.get('id');if(id)void loadEncounter(id)},[params,loadEncounter]);
 useEffect(()=>{
  window.scrollTo({ top: 0, behavior: 'smooth' });
  const stepper = document.querySelector('.clinical-stepper') || document.querySelector('.encounter-page');
  if (stepper) {
    stepper.scrollIntoView({ behavior: 'smooth', block: 'start' });
  }
 },[active]);
 useEffect(()=>{if(!patientParam||!appointmentParam||params.get('id'))return;let cancelled=false;setLoading(true);api<{data:{id:string}}>('/api/encounters',{method:'POST',body:JSON.stringify({patientId:patientParam,appointmentId:appointmentParam})}).then(r=>{if(!cancelled){setParams({id:r.data.id});void loadEncounter(r.data.id)}}).catch(c=>setError(c instanceof Error?c.message:'Erro ao iniciar atendimento.')).finally(()=>setLoading(false));return()=>{cancelled=true}},[patientParam,appointmentParam,params,setParams,loadEncounter]);
 async function start(){if(!patientId)return;setLoading(true);setError('');try{const r=await api<{data:{id:string}}>('/api/encounters',{method:'POST',body:JSON.stringify({patientId})});setParams({id:r.data.id});await loadEncounter(r.data.id)}catch(c){setError(c instanceof Error?c.message:'Não foi possível iniciar.')}finally{setLoading(false)}}
 const current=steps[active];const savedKeys=useMemo(()=>new Set(Object.keys(encounter?.sections||{})),[encounter]);
 function change(key:SectionKey,field:string,value:string){setDrafts(d=>({...d,[key]:{...(d[key]||{}),[field]:value}}));setDirtyKeys(keys=>new Set(keys).add(key));setNotice('')}
 async function saveSection(){if(!encounter||current.key==='review')return;setSaving(true);setError('');try{await api(`/api/encounters/${encounter.id}/sections/${current.key}`,{method:'PUT',body:JSON.stringify({data:drafts[current.key]||{},expectedSavedAt:encounter.sections[current.key]?.savedAt||null})});await loadEncounter(encounter.id);setNotice('Etapa salva com segurança.');if(active<steps.length-1)setActive(active+1)}catch(c){setError(c instanceof Error?c.message:'Não foi possível salvar a etapa.')}finally{setSaving(false)}}
 async function finalize(){if(!encounter)return;if(dirtyKeys.size){setError('Salve todas as alterações antes de finalizar o atendimento.');return}const missing=missingClinicalCore(encounter.sections);if(missing.length){setError(`Preencha e salve os requisitos obrigatórios: ${missing.join(', ')}.`);return}setSaving(true);setError('');try{await api(`/api/encounters/${encounter.id}/finalize`,{method:'POST'});await loadEncounter(encounter.id);setNotice('Atendimento finalizado.')}catch(c){setError(c instanceof Error?c.message:'Não foi possível finalizar.')}finally{setSaving(false)}}
 if(!encounter)return <section className="panel encounter-start"><div className="encounter-start-icon"><ClipboardList size={30}/></div><span className="eyebrow">Atendimento privado</span><h2>Iniciar atendimento clínico</h2><p>Selecione o paciente. As informações serão salvas por etapas e poderão ser retomadas.</p>{error&&<div className="form-error">{error}</div>}<label>Paciente<select value={patientId} onChange={e=>setPatientId(e.target.value)}><option value="">Selecione um paciente</option>{patients.map(p=><option key={p.id} value={p.id}>{p.name}</option>)}</select></label><button className="primary-button" onClick={()=>void start()} disabled={!patientId||loading}>{loading?'Abrindo...':'Começar atendimento'}</button><div className="privacy-note"><LockKeyhole size={15}/> Anamnese disponível apenas na área profissional autenticada.</div></section>;
 const key=current.key as SectionKey;const assessment=drafts.assessment||{};const profile=String(assessment.clinicalProfile||'Adulto');const weight=Number(assessment.weight);const height=Number(assessment.height);const age=Number(assessment.age);const bmi=weight>0&&height>0?(weight/(height/100)**2).toFixed(1):null;const whr=Number(assessment.waist)>0&&Number(assessment.hip)>0?(Number(assessment.waist)/Number(assessment.hip)).toFixed(2):null;const activityFactor=parseFloat(String(assessment.activityFactor||'1.375'))||1.375;const bmr=weight>0&&height>0&&age>0?10*weight+6.25*height-5*age+(assessment.sex==='Masculino'?5:-161):null;const totalEnergy=bmr?Math.round(bmr*activityFactor):null;const gestationalGain=profile==='Gestante'&&Number(assessment.prePregnancyWeight)>0?(weight-Number(assessment.prePregnancyWeight)).toFixed(1):null;
 const roomToken=encounter.videoRoomToken||encounter.id;
 return <div className={`virtual-office ${videoOpen?'with-video':''}`}>{videoOpen&&<VideoConsultation appointmentId={encounter.appointmentId} roomToken={roomToken} patientName={encounter.patientName} onClose={()=>setVideoOpen(false)}/>}<div className="encounter-page"><section className="encounter-header"><div className="patient-avatar large">{encounter.patientName.charAt(0)}</div><div><span className="eyebrow">Atendimento em andamento</span><h2>{encounter.patientName}</h2><p>{encounter.objective||'Objetivo não informado'} · iniciado em {new Date(encounter.startedAt).toLocaleDateString('pt-BR')}</p></div><div className="encounter-header-actions">{encounter.status!=='COMPLETED'&&<button className={`secondary-button video-toggle-btn ${videoOpen?'active':''}`} onClick={()=>setVideoOpen(v=>!v)}><Video size={17}/> {videoOpen?'Ocultar split':'Teleconsulta (Split)'}</button>}<span className={`encounter-state ${encounter.status==='COMPLETED'?'done':''}`}>{encounter.status==='COMPLETED'?<><CheckCircle2 size={15}/> Finalizado</>:'Em andamento'}</span></div></section>
 <nav className="clinical-stepper" aria-label="Etapas do atendimento">{steps.map((step,index)=><button key={step.key} className={`${active===index?'active ':''}${step.key!=='review'&&savedKeys.has(step.key)?'saved':''}`} onClick={()=>setActive(index)}><span>{step.key!=='review'&&savedKeys.has(step.key)?<Check size={15}/>:index+1}</span><div><strong>{step.label}</strong><small>{step.description}</small></div></button>)}</nav>
 {error&&<div className="form-error">{error}</div>}{notice&&<div className="form-success"><CheckCircle2 size={17}/>{notice}</div>}
 <ClinicalSnapshot encounter={encounter} reload={()=>void loadEncounter(encounter.id)}/>
 <details className="history-drawer"><summary>Histórico e evolução do paciente</summary><PatientHistory patientId={encounter.patientId}/></details>
 <section className="panel clinical-workspace"><div className="clinical-title"><div><span className="eyebrow">Etapa {active+1} de {steps.length}</span><h2>{current.label}</h2><p>{current.description}</p></div>{current.key!=='review'&&<span className={`save-indicator ${savedKeys.has(current.key)&&!dirtyKeys.has(current.key)?'saved':''}`}>{dirtyKeys.has(current.key)?'Alterações não salvas':savedKeys.has(current.key)?<><Check size={14}/> Salvo</>:'Ainda não salvo'}</span>}</div>
 {current.key==='review'?<Review encounter={encounter} dirty={dirtyKeys.size>0} onFinalize={finalize} saving={saving}/>:current.key==='plan'?<EncounterPlan encounterId={encounter.id} planId={String(encounter.sections.plan?.data.planId||'')} onCreated={()=>void loadEncounter(encounter.id)}/>:current.key==='exams'?<LabsList encounterId={encounter.id} initial={encounter.labs||[]} locked={encounter.status==='COMPLETED'} reload={()=>void loadEncounter(encounter.id)}/>:current.key==='supplements'?<SupplementsList encounterId={encounter.id} initial={encounter.supplements||[]} locked={encounter.status==='COMPLETED'} reload={()=>void loadEncounter(encounter.id)}/>:<div className="clinical-form">{current.fields?.filter(field=>!field.profiles||field.profiles.includes(profile)).map(field=><label key={field.key} className={field.type==='textarea'?'wide':''}>{field.label}<div className={field.suffix?'field-suffix':''}>{field.type==='textarea'?<textarea rows={4} value={String(drafts[key]?.[field.key]||'')} onChange={e=>change(key,field.key,e.target.value)} placeholder={field.placeholder}/>:field.type==='select'?<select value={String(drafts[key]?.[field.key]||'')} onChange={e=>change(key,field.key,e.target.value)}><option value="">Selecione</option>{field.options?.map(option=><option key={option}>{option}</option>)}</select>:<input type={field.type||'text'} step={field.type==='number'?'0.1':undefined} value={String(drafts[key]?.[field.key]||'')} onChange={e=>change(key,field.key,e.target.value)} placeholder={field.placeholder}/>} {field.suffix&&<span>{field.suffix}</span>}</div></label>)}{current.key==='assessment'&&(bmi||whr||bmr)&&<div className="bmi-result assessment-results"><span>Indicadores calculados · {profile}</span><div>{bmi&&<strong>IMC {bmi}</strong>}{whr&&<strong>RCQ {whr}</strong>}{bmr&&<strong>TMB {Math.round(bmr)} kcal</strong>}{totalEnergy&&<strong>VET {totalEnergy} kcal</strong>}{gestationalGain&&<strong>Ganho gestacional {gestationalGain} kg</strong>}</div><small>Indicadores de apoio; a interpretação depende do perfil, idade e contexto clínico.</small></div>}</div>}
 <div className="clinical-footer"><button className="secondary-button" onClick={()=>setActive(Math.max(0,active-1))} disabled={active===0}><ChevronLeft size={17}/> Anterior</button>{current.key!=='review'&&current.key!=='plan'&&<div><button className="ghost-button" onClick={()=>setActive(Math.min(steps.length-1,active+1))}>Avançar sem salvar</button><button className="primary-button" onClick={()=>void saveSection()} disabled={saving||encounter.status==='COMPLETED'}><Save size={17}/>{saving?'Salvando...':'Salvar e continuar'}<ChevronRight size={16}/></button></div>}</div></section></div></div>;
}

const checkinLabels:Record<string,string>={improvements:'O que melhorou',mainDifficulty:'Principal dificuldade',medicationChanges:'Mudanças de medicamentos',newSymptoms:'Sintomas novos',adherence:'Adesão percebida (0–10)',examsCompleted:'Exames realizados',discussionTopics:'Assuntos para a consulta'};
function ClinicalSnapshot({encounter,reload}:{encounter:Encounter;reload:()=>void}){const anamnesis=encounter.sections.anamnesis?.data||{};const conduct=encounter.sections.conduct?.data||{};const exams=encounter.sections.exams?.data||{};const assessment=encounter.sections.assessment?.data||{};const pending=encounter.checkins?.filter(item=>item.status==='PENDING_REVIEW')||[];const cards=[['Objetivo',encounter.objective],['Alergias e intolerâncias',anamnesis.allergies],['Medicamentos em uso',anamnesis.medications],['Peso atual',assessment.weight?`${assessment.weight} kg`:null],['Próximo acompanhamento',conduct.followUp],['Exames pendentes',exams.pendingExams]].filter(([,value])=>String(value||'').trim());const[selected,setSelected]=useState<Record<string,string[]>>({});async function review(id:string){await api(`/api/encounters/${encounter.id}/checkins/${id}/review`,{method:'PATCH'});reload()}function toggle(id:string,key:string){setSelected(current=>{const fields=current[id]||[];return{...current,[id]:fields.includes(key)?fields.filter(x=>x!==key):[...fields,key]}})}async function incorporate(id:string){const fields=selected[id]||[];if(!fields.length)return;await api(`/api/encounters/${encounter.id}/import-clinical`,{method:'POST',body:JSON.stringify({sourceType:'CHECKIN',sourceId:id,fields})});await review(id)}return <section className="clinical-snapshot"><header><div><span className="eyebrow">Resumo clínico vivo</span><h3>Essencial para esta decisão</h3></div>{pending.length>0&&<strong>{pending.length} check-in{pending.length>1?'s':''} para revisar</strong>}</header><div className="snapshot-grid">{cards.length?cards.map(([label,value])=><article key={String(label)}><small>{label}</small><p>{String(value)}</p></article>):<p className="snapshot-empty">O resumo será formado conforme as etapas forem salvas.</p>}</div>{pending.map(item=><details className="checkin-review" key={item.id} open><summary>Check-in enviado em {new Date(item.submittedAt).toLocaleDateString('pt-BR')}</summary><div>{Object.entries(item.answers).filter(([,value])=>String(value||'').trim()).map(([key,value])=><article key={key}><label className="check"><input type="checkbox" checked={(selected[item.id]||[]).includes(key)} onChange={()=>toggle(item.id,key)}/><strong>{checkinLabels[key]||key}</strong></label><p>{String(value)}</p></article>)}</div><button className="primary-button" type="button" disabled={!(selected[item.id]||[]).length} onClick={()=>void incorporate(item.id)}><Check size={15}/> Incorporar selecionados à evolução</button><button className="secondary-button" type="button" onClick={()=>void review(item.id)}>Apenas marcar como revisado</button><small>Somente os itens selecionados entram nas Anotações, com registro de auditoria.</small></details>)}</section>}

function EncounterPlan({encounterId,planId,onCreated}:{encounterId:string;planId:string;onCreated:()=>void}){const[creating,setCreating]=useState(false);const[error,setError]=useState('');async function open(){setCreating(true);setError('');try{await api('/api/nutrition/plans/for-encounter',{method:'POST',body:JSON.stringify({encounterId})});onCreated()}catch(c){setError(c instanceof Error?c.message:'Não foi possível preparar o plano.')}finally{setCreating(false)}}if(!planId)return <div className="encounter-plan-empty"><UtensilsCrossed size={34}/><h3>Plano alimentar deste atendimento</h3><p>Crie um rascunho vinculado ao paciente e use TACO e receitas sem sair da videochamada.</p>{error&&<div className="form-error">{error}</div>}<button className="primary-button" onClick={()=>void open()} disabled={creating}>{creating?'Preparando editor...':<><Plus size={17}/> Criar plano para este paciente</>}</button></div>;return <iframe className="embedded-plan-editor" src={`/embed/planos/${planId}`} title="Editor do plano alimentar"/>}

function Review({encounter,dirty,onFinalize,saving}:{encounter:Encounter;dirty:boolean;onFinalize:()=>void;saving:boolean}){const requirements=[{label:'Contexto',saved:Boolean(encounter.sections.context)},{label:'Conduta',saved:Boolean(encounter.sections.conduct)},{label:'Anamnese ou Retorno',saved:Boolean(encounter.sections.anamnesis||encounter.sections.followup)}];const missing=requirements.filter(item=>!item.saved);return <div className="review-content"><div className="review-summary"><FileCheck2 size={28}/><div><strong>{requirements.length-missing.length} de {requirements.length} requisitos obrigatórios salvos</strong><p>Para finalizar, salve Contexto, Conduta e Anamnese ou Retorno. Depois da finalização, o atendimento ficará somente para leitura.</p></div></div><div className="review-sections">{requirements.map(item=><article key={item.label}><span className={item.saved?'complete':''}>{item.saved?<Check size={14}/>:<UserRound size={14}/>}</span><div><strong>{item.label}</strong><small>{item.saved?'Requisito salvo':'Requisito pendente'}</small></div></article>)}</div><button className="primary-button finalize-button" onClick={onFinalize} disabled={saving||encounter.status==='COMPLETED'||missing.length>0||dirty}>{encounter.status==='COMPLETED'?'Atendimento finalizado':saving?'Finalizando...':'Revisar e finalizar atendimento'}</button>{encounter.status!=='COMPLETED'&&dirty&&<small className="finalize-hint">Salve todas as alterações antes de finalizar.</small>}{encounter.status!=='COMPLETED'&&!dirty&&missing.length>0&&<small className="finalize-hint">Requisitos pendentes: {missing.map(item=>item.label).join(', ')}.</small>}</div>}
