import { ArrowRight, Check, ChevronRight, HeartPulse, Leaf, Menu, MessageCircle, ShieldCheck, Sparkles, Stethoscope, X } from 'lucide-react';
import { useState } from 'react';
import { Link } from 'react-router-dom';
import { ClinicMark, useClinic } from '../contexts/ClinicContext';
import portrait from '../../../assets/silvia-foto-oficial.webp';
import fullBody from '../../../assets/silvia-fullbody.png';
import consultation from '../../../assets/silvia-consultation.webp';

const digits=(value?:string|null)=>(value||'').replace(/\D/g,'');

export function HomePage(){
  const clinic=useClinic();const[menu,setMenu]=useState(false);
  const whatsapp=digits(clinic.phone)||'5521987385146';
  const message=encodeURIComponent(`Olá, ${clinic.professionalName}! Gostaria de conhecer melhor o acompanhamento nutricional.`);
  const contact=`https://wa.me/${whatsapp}?text=${message}`;
  return <main className="public-home">
    <header className="public-header"><a className="public-brand" href="#inicio"><ClinicMark/><span><strong>{clinic.clinicName}</strong><small>{clinic.specialty}</small></span></a><nav className={menu?'open':''}><a href="#sobre" onClick={()=>setMenu(false)}>Sobre</a><a href="#acompanhamento" onClick={()=>setMenu(false)}>Acompanhamento</a><a href="#como-funciona" onClick={()=>setMenu(false)}>Como funciona</a><a href="#contato" onClick={()=>setMenu(false)}>Contato</a><Link to="/login">Área do paciente</Link></nav><button className="home-menu" onClick={()=>setMenu(!menu)} aria-label="Abrir menu">{menu?<X/>:<Menu/>}</button><a className="home-cta header-cta" href={contact} target="_blank" rel="noreferrer">Agendar consulta</a></header>
    <section className="home-hero" id="inicio"><div className="hero-copy"><span className="home-kicker"><Leaf/> Nutrição com ciência e acolhimento</span><h1>Alimentação consciente.<br/><em>Resultados reais.</em></h1><p>Um acompanhamento individualizado para transformar sua relação com a comida, respeitando sua rotina, seus objetivos e a sua história.</p><div className="hero-actions"><a className="home-cta" href={contact} target="_blank" rel="noreferrer"><MessageCircle/> Quero agendar <ArrowRight/></a><a className="home-link" href="#sobre">Conheça meu trabalho <ChevronRight/></a></div><div className="hero-trust"><span><ShieldCheck/> Atendimento individualizado</span><span><HeartPulse/> Clínica e esportiva</span></div></div><div className="hero-visual"><div className="hero-orbit"/><img src={portrait} alt={`${clinic.professionalName}, nutricionista`}/><aside><Sparkles/><div><strong>{clinic.professionalName}</strong><span>{clinic.crn}</span></div></aside></div></section>
    <section className="home-about" id="sobre"><div className="about-photo"><div/><img src={fullBody} alt={`${clinic.professionalName} em seu consultório`}/></div><div className="about-copy"><span className="home-kicker">Sobre mim</span><h2>Ciência, acolhimento e nutrição possível.</h2><p>Sou <strong>{clinic.professionalName}</strong>, nutricionista especializada em {clinic.specialty}. Meu propósito é ajudar você a alcançar seus objetivos estéticos e de saúde de forma leve, estratégica e sustentável.</p><p>Acredito que o alimento não deve ser fonte de culpa ou ansiedade. Construímos juntos um planejamento que cabe na vida real, com orientações claras e acompanhamento próximo.</p><div className="about-signature"><span>{clinic.crn}</span><span>{clinic.city||'Atendimento presencial e online'}</span></div><a className="home-cta dark" href={contact} target="_blank" rel="noreferrer">Conversar com a Silvia <ArrowRight/></a></div></section>
    <section className="home-services" id="acompanhamento"><div className="section-heading"><span className="home-kicker">Acompanhamento completo</span><h2>Cuidado pensado para a sua realidade</h2><p>Mais do que entregar um cardápio: compreender, planejar e acompanhar.</p></div><div className="service-grid"><Service icon={<HeartPulse/>} number="01" title="Nutrição clínica" text="Estratégias para saúde metabólica, emagrecimento, qualidade de vida e prevenção."/><Service icon={<Stethoscope/>} number="02" title="Avaliação individual" text="Histórico, rotina, preferências, exames e objetivos reunidos em uma conduta personalizada."/><Service icon={<Sparkles/>} number="03" title="Nutrição esportiva" text="Planejamento alimentar alinhado ao treino, à performance e à composição corporal."/></div></section>
    <section className="home-process" id="como-funciona"><div className="process-image"><img src={consultation} alt="Consulta nutricional individualizada"/></div><div><span className="home-kicker">Como funciona</span><h2>Uma jornada clara, do primeiro encontro à evolução.</h2><ol><li><b>1</b><span><strong>Escuta e avaliação</strong><small>Entendemos seu momento, sua rotina e o que você deseja alcançar.</small></span></li><li><b>2</b><span><strong>Estratégia personalizada</strong><small>Você recebe um plano alimentar prático, individual e acessível pelo portal.</small></span></li><li><b>3</b><span><strong>Acompanhamento contínuo</strong><small>Ajustamos a conduta conforme seus resultados e desafios reais.</small></span></li></ol></div></section>
    <section className="home-banner" id="contato"><Leaf/><span>Seu próximo passo pode começar hoje.</span><h2>Vamos construir uma alimentação que faça sentido para você?</h2><a className="home-cta light" href={contact} target="_blank" rel="noreferrer"><MessageCircle/> Falar pelo WhatsApp</a></section>
    <footer className="home-footer"><div className="public-brand"><ClinicMark/><span><strong>{clinic.clinicName}</strong><small>{clinic.specialty}</small></span></div><p>{clinic.crn} · {clinic.city}</p><div><Link to="/login">Acessar portal</Link>{clinic.email&&<a href={`mailto:${clinic.email}`}>{clinic.email}</a>}</div></footer>
  </main>
}
function Service({icon,number,title,text}:{icon:React.ReactNode;number:string;title:string;text:string}){return <article><div className="service-icon">{icon}</div><span>{number}</span><h3>{title}</h3><p>{text}</p><Check/></article>}
