import { ArrowRight, CalendarCheck, Check, ChevronRight, CircleHelp, Clock3, HeartPulse, Laptop, Leaf, MapPin, Menu, MessageCircle, MonitorSmartphone, Salad, ShieldCheck, Sparkles, Stethoscope, Target, UserRoundCheck, X } from 'lucide-react';
import { useEffect, useState } from 'react';
import { Link } from 'react-router-dom';
import { ClinicMark, useClinic } from '../contexts/ClinicContext';
import portrait from '../../../assets/silvia-foto-oficial.webp';
import fullBody from '../../../assets/silvia-fullbody.png';
import consultation from '../../../assets/silvia-consultation.webp';

const digits=(value?:string|null)=>(value||'').replace(/\D/g,'');

export function HomePage(){
  const clinic=useClinic(); const[menu,setMenu]=useState(false);
  const professionalFirstName=clinic.professionalName.replace(/^(Dra\.?|Nutricionista)\s*/i,'').trim().split(/\s+/)[0]||'a nutricionista';
  const whatsapp=digits(clinic.phone);
  const message=encodeURIComponent(`Olá, ${clinic.professionalName}! Gostaria de conhecer melhor o acompanhamento nutricional e consultar horários disponíveis.`);
  const contact=`https://wa.me/${whatsapp}?text=${message}`;
  useEffect(()=>{
    const previous=document.title;
    document.title=`Nutricionista ${clinic.professionalName.replace(/^Dra\.\s*/,'')} | Nutrição Clínica e Esportiva em ${clinic.city||'atendimento online'}`;
    let meta=document.querySelector<HTMLMetaElement>('meta[name="description"]');
    if(!meta){meta=document.createElement('meta');meta.name='description';document.head.appendChild(meta)}
    meta.content='Acompanhamento nutricional individualizado em nutrição clínica, esportiva, emagrecimento e saúde metabólica, com consultas presenciais e online.';
    return()=>{document.title=previous};
  },[clinic.city,clinic.professionalName]);

  return <main className="public-home">
    <header className="public-header">
      <a className="public-brand" href="#inicio" aria-label={`${clinic.clinicName} — início`}><ClinicMark/><span><strong>{clinic.clinicName}</strong><small>{clinic.specialty}</small></span></a>
      <nav id="public-navigation" className={menu?'open':''} aria-label="Navegação principal"><a href="#sobre" onClick={()=>setMenu(false)}>Sobre</a><a href="#acompanhamento" onClick={()=>setMenu(false)}>Acompanhamento</a><a href="#como-funciona" onClick={()=>setMenu(false)}>Como funciona</a><a href="#duvidas" onClick={()=>setMenu(false)}>Dúvidas</a><Link to="/login">Área do paciente</Link></nav>
      <button className="home-menu" onClick={()=>setMenu(!menu)} aria-label={menu?'Fechar menu':'Abrir menu'} aria-expanded={menu} aria-controls="public-navigation">{menu?<X/>:<Menu/>}</button>
      <a className="home-cta header-cta" href={contact} target="_blank" rel="noreferrer">Consultar horários</a>
    </header>

    <section className="home-hero" id="inicio"><div className="hero-copy"><span className="home-kicker"><Leaf/> Nutrição com ciência e acolhimento</span><h1>Um plano possível.<br/><em>Para a sua vida real.</em></h1><p>Acompanhamento em nutrição clínica, esportiva e emagrecimento, com estratégia individual, escuta cuidadosa e evolução acompanhada de perto.</p><div className="hero-actions"><a className="home-cta" href={contact} target="_blank" rel="noreferrer"><MessageCircle/> Consultar horários <ArrowRight/></a><Link className="home-link" to="/login">Já sou paciente <ChevronRight/></Link></div><div className="hero-trust"><span><ShieldCheck/> Atendimento individualizado</span><span><Laptop/> Presencial e online</span><span><MapPin/> {clinic.city||'Consulte a localização'}</span></div></div><div className="hero-visual"><div className="hero-orbit"/><img src={portrait} alt={`${clinic.professionalName}, nutricionista`} width="650" height="760" fetchPriority="high"/><aside><Sparkles/><div><strong>{clinic.professionalName}</strong><span>{clinic.crn}</span></div></aside></div></section>

    <section className="home-proof" aria-label="Diferenciais do acompanhamento"><span><UserRoundCheck/><b>Conduta individual</b><small>Baseada na sua história e rotina</small></span><span><MonitorSmartphone/><b>Portal do paciente</b><small>Plano, evolução e materiais em um só lugar</small></span><span><CalendarCheck/><b>Acompanhamento contínuo</b><small>Ajustes conforme sua evolução</small></span></section>

    <section className="home-about" id="sobre"><div className="about-photo"><div/><img src={fullBody} alt={`${clinic.professionalName}, nutricionista`} width="180" height="489" loading="lazy"/></div><div className="about-copy"><span className="home-kicker">Sobre a nutricionista</span><h2>Ciência, acolhimento e nutrição possível.</h2><p>Sou <strong>{clinic.professionalName}</strong>, nutricionista especializada em {clinic.specialty}. Meu propósito é transformar objetivos de saúde em uma estratégia clara, sustentável e aplicável à rotina.</p><p>Sem cardápios genéricos ou culpa. Avaliamos histórico, preferências, exames, movimento, sono e contexto para construir uma conduta verdadeiramente individual.</p><div className="about-signature"><span>{clinic.crn}</span><span>{clinic.city||'Atendimento presencial e online'}</span></div>{whatsapp&&<a className="home-cta dark" href={contact} target="_blank" rel="noreferrer">Conversar com {professionalFirstName} <ArrowRight/></a>}</div></section>

    <section className="home-services" id="acompanhamento"><div className="section-heading"><span className="home-kicker">Para quem é</span><h2>Cuidado pensado para diferentes objetivos</h2><p>A conduta é adaptada ao seu momento clínico, às suas preferências e ao que é possível manter.</p></div><div className="service-grid"><Service icon={<HeartPulse/>} number="01" title="Saúde e emagrecimento" text="Estratégias para composição corporal, saúde metabólica e construção de hábitos sustentáveis."/><Service icon={<Stethoscope/>} number="02" title="Nutrição clínica" text="Avaliação integrada de histórico, sintomas, exames, rotina e necessidades nutricionais."/><Service icon={<Target/>} number="03" title="Nutrição esportiva" text="Planejamento alimentar alinhado ao treino, à recuperação, à performance e aos seus objetivos."/></div></section>

    <section className="home-included"><div className="included-copy"><span className="home-kicker">O que você recebe</span><h2>Mais do que uma consulta isolada</h2><p>Uma experiência organizada para você entender a estratégia e acompanhar cada etapa.</p></div><div className="included-grid"><Included title="Avaliação completa" text="Histórico, rotina, sinais clínicos, medidas e exames quando disponíveis."/><Included title="Plano individualizado" text="Refeições e orientações adequadas às preferências e à realidade do paciente."/><Included title="Materiais educativos" text="Lâminas ilustradas e referências confiáveis para apoiar as decisões."/><Included title="Portal exclusivo" text="Plano alimentar, documentos, metas, mensagens e evolução acessíveis online."/></div></section>

    <section className="home-process" id="como-funciona"><div className="process-image"><img src={consultation} alt="Consulta nutricional individualizada" width="720" height="720" loading="lazy"/></div><div><span className="home-kicker">Como funciona</span><h2>Uma jornada clara, do primeiro contato à evolução.</h2><ol><li><b>1</b><span><strong>Agendamento</strong><small>Você consulta os horários e recebe as orientações para a primeira consulta.</small></span></li><li><b>2</b><span><strong>Escuta e avaliação</strong><small>Entendemos seu momento, histórico, rotina e objetivos.</small></span></li><li><b>3</b><span><strong>Estratégia personalizada</strong><small>O plano e os materiais ficam disponíveis no portal do paciente.</small></span></li><li><b>4</b><span><strong>Acompanhamento</strong><small>A conduta é ajustada conforme resultados, dificuldades e novas necessidades.</small></span></li></ol></div></section>

    <section className="home-portal-showcase"><div><span className="home-kicker">Tecnologia a favor do cuidado</span><h2>Seu acompanhamento continua depois da consulta.</h2><p>No portal, você encontra o que precisa sem depender de mensagens perdidas: plano alimentar, consultas, metas, documentos e materiais educativos.</p><ul><li><Check/> Plano e orientações sempre acessíveis</li><li><Check/> Histórico de evolução organizado</li><li><Check/> Teleconsulta integrada e segura</li><li><Check/> Comunicação vinculada ao acompanhamento</li></ul><Link className="home-link portal-link" to="/login">Acessar área do paciente <ArrowRight/></Link></div><div className="portal-mockup" aria-label="Prévia ilustrativa do portal do paciente"><div className="mockup-bar"><i/><i/><i/></div><span>Olá, seja bem-vindo(a)</span><h3>Seu cuidado em um só lugar</h3><div className="mockup-card"><Salad/><div><b>Plano alimentar</b><small>Orientações atualizadas</small></div></div><div className="mockup-row"><div><CalendarCheck/><small>Consultas</small></div><div><Target/><small>Metas</small></div><div><MessageCircle/><small>Mensagens</small></div></div></div></section>

    <section className="home-faq" id="duvidas"><div className="section-heading"><span className="home-kicker"><CircleHelp/> Dúvidas frequentes</span><h2>Antes de agendar</h2></div><div className="faq-list"><Faq question="O atendimento pode ser online?" answer="Sim. Há atendimento por teleconsulta e, conforme disponibilidade, atendimento presencial. Consulte a modalidade desejada no agendamento."/><Faq question="O plano alimentar é personalizado?" answer="Sim. A estratégia considera necessidades clínicas, preferências, rotina, objetivo e condições de acesso aos alimentos."/><Faq question="Como recebo o plano e os materiais?" answer="Após a consulta, os conteúdos liberados ficam organizados no portal do paciente, acessível pelo celular ou computador."/><Faq question="Qual é a duração e o valor da consulta?" answer="Duração, valores, retornos e formas de pagamento podem variar conforme o tipo de acompanhamento. Solicite as informações atualizadas pelo WhatsApp."/><Faq question="Atende plano de saúde?" answer="Consulte a modalidade de atendimento e a possibilidade de emissão de documento para solicitação de reembolso."/></div></section>

    <section className="home-banner" id="contato"><Leaf/><span>Seu próximo passo pode começar hoje</span><h2>Vamos construir uma alimentação que faça sentido para você?</h2><p>Fale diretamente com a equipe para consultar modalidades, valores e horários disponíveis.</p><a className="home-cta light" href={contact} target="_blank" rel="noreferrer"><MessageCircle/> Consultar horários pelo WhatsApp</a><small><Clock3/> O tempo de resposta pode variar conforme o horário de atendimento.</small></section>
    <section className="home-privacy" id="privacidade"><ShieldCheck/><div><strong>Privacidade faz parte do cuidado</strong><p>As informações enviadas pelo portal são tratadas dentro do fluxo clínico e conforme as solicitações do titular. Evite compartilhar dados de saúde por canais não autorizados.</p><Link to="/privacidade">Ler o aviso de privacidade completo</Link></div></section>
    <footer className="home-footer"><div className="public-brand"><ClinicMark/><span><strong>{clinic.clinicName}</strong><small>{clinic.specialty}</small></span></div><p>{clinic.crn} · {clinic.city}</p><div><Link to="/login">Acessar portal</Link><Link to="/privacidade">Privacidade</Link>{clinic.email&&<a href={`mailto:${clinic.email}`}>{clinic.email}</a>}</div></footer>
    <a className="mobile-contact-cta" href={contact} target="_blank" rel="noreferrer"><MessageCircle/> Consultar horários</a>
  </main>
}

function Service({icon,number,title,text}:{icon:React.ReactNode;number:string;title:string;text:string}){return <article><div className="service-icon">{icon}</div><span>{number}</span><h3>{title}</h3><p>{text}</p><Check/></article>}
function Included({title,text}:{title:string;text:string}){return <article><Check/><div><h3>{title}</h3><p>{text}</p></div></article>}
function Faq({question,answer}:{question:string;answer:string}){return <details><summary>{question}<ChevronRight/></summary><p>{answer}</p></details>}
