import { ArrowRight, CheckCircle2, Leaf, LockKeyhole } from 'lucide-react';
import { useState, type FormEvent } from 'react';
import { Link, Navigate, useLocation, useNavigate } from 'react-router-dom';
import { useAuth } from '../contexts/AuthContext';
import { ClinicMark, useClinic } from '../contexts/ClinicContext';

export function LoginPage(){
  const{user,login}=useAuth();const clinic=useClinic();const navigate=useNavigate();const location=useLocation();
  const[identifier,setIdentifier]=useState('');const[password,setPassword]=useState('');const[error,setError]=useState('');const[submitting,setSubmitting]=useState(false);
  if(user)return <Navigate to={user.role==='PATIENT'?'/portal':'/painel'} replace/>;
  async function submit(event:FormEvent){event.preventDefault();setError('');setSubmitting(true);try{await login(identifier,password);navigate((location.state as{from?:string}|null)?.from??'/painel',{replace:true})}catch(c){setError(c instanceof Error?c.message:'Não foi possível entrar.')}finally{setSubmitting(false)}}
  return <main className="login-page"><section className="login-story"><div className="story-glow"/><div className="story-content"><div className="brand light"><ClinicMark/><div><strong>{clinic.clinicName}</strong><span>{clinic.specialty}</span></div></div><div className="story-copy"><span className="eyebrow light-text">Cuidado que se organiza</span><h1>Mais presença no atendimento.<br/>Menos ruído na rotina.</h1><p>Um espaço clínico pensado para acompanhar cada paciente com clareza, contexto e continuidade.</p><div className="story-points"><span><CheckCircle2/> Jornada clínica em um só lugar</span><span><CheckCircle2/> Dados protegidos e acessíveis</span></div></div><div className="story-quote"><Leaf/><p>“Cuidar bem também é tornar o complexo mais simples.”</p></div></div></section><section className="login-panel"><form className="login-card" onSubmit={submit}><div className="mobile-login-brand"><ClinicMark/><strong>{clinic.clinicName}</strong></div><span className="eyebrow">Bem-vinda de volta</span><h2>Acesse seu espaço</h2><p className="muted">Use seu e-mail ou CPF e sua senha para continuar.</p><label>E-mail ou CPF<input value={identifier} onChange={e=>setIdentifier(e.target.value)} autoComplete="username" required/></label><label>Senha<input type="password" value={password} onChange={e=>setPassword(e.target.value)} autoComplete="current-password" required/></label>{error&&<div className="form-error">{error}</div>}<button className="primary-button login-submit" disabled={submitting}>{submitting?'Entrando...':<>Entrar <ArrowRight/></>}</button><Link className="auth-back" to="/recuperar-senha">Esqueci minha senha</Link><div className="security-note"><LockKeyhole/> Acesso protegido e sessão segura.</div></form></section></main>
}
