import { CheckCircle2, MessageCircle, RefreshCw, Search, Send } from 'lucide-react';
import { useCallback, useEffect, useMemo, useState, type FormEvent } from 'react';
import { api } from '../lib/api';

type Conversation={patientId:string;patientName:string;email?:string;whatsapp?:string;lastMessage:string;lastSenderRole:'PATIENT'|'ADMIN';lastMessageAt:string;unreadCount:number};
type Message={id:string;senderRole:'PATIENT'|'ADMIN';body:string;readAt?:string|null;createdAt:string};
type Thread={patient:{id:string;name:string};messages:Message[]};
const clean=(body:string)=>body.replace(/^\[[^\]]+\]\s*/,'');
const category=(body:string)=>body.match(/^\[([^\]]+)\]\s*/)?.[1];

export function MessagesPage(){const[conversations,setConversations]=useState<Conversation[]>([]);const[selected,setSelected]=useState<string|null>(null);const[thread,setThread]=useState<Thread|null>(null);const[query,setQuery]=useState('');const[loading,setLoading]=useState(true);const[sending,setSending]=useState(false);const[error,setError]=useState('');const[notice,setNotice]=useState('');
 const loadList=useCallback(async()=>{setLoading(true);try{const result=await api<{data:Conversation[]}>('/api/messages');setConversations(result.data);setSelected(current=>current||result.data[0]?.patientId||null)}catch(c){setError(c instanceof Error?c.message:'Não foi possível carregar as mensagens.')}finally{setLoading(false)}},[]);
 const loadThread=useCallback(async(patientId:string)=>{try{const result=await api<{data:Thread}>(`/api/messages/${patientId}`);setThread(result.data);setConversations(current=>current.map(item=>item.patientId===patientId?{...item,unreadCount:0}:item))}catch(c){setError(c instanceof Error?c.message:'Não foi possível abrir a conversa.')}},[]);
 useEffect(()=>{void loadList()},[loadList]);useEffect(()=>{if(selected)void loadThread(selected)},[selected,loadThread]);
 const filtered=useMemo(()=>conversations.filter(item=>item.patientName.toLowerCase().includes(query.toLowerCase())||item.email?.toLowerCase().includes(query.toLowerCase())),[conversations,query]);
 async function send(event:FormEvent<HTMLFormElement>){event.preventDefault();if(!selected)return;const form=event.currentTarget;const data=new FormData(form);setSending(true);setError('');setNotice('');try{await api(`/api/messages/${selected}`,{method:'POST',body:JSON.stringify({body:String(data.get('body')||'')})});form.reset();setNotice('Resposta enviada e disponibilizada no portal do paciente.');await Promise.all([loadThread(selected),loadList()])}catch(c){setError(c instanceof Error?c.message:'Não foi possível enviar a resposta.')}finally{setSending(false)}}
 return <section className="professional-messages"><header className="messages-page-intro"><div><p>Converse com seus pacientes pelo canal protegido do portal.</p></div><button className="secondary-button" onClick={()=>void loadList()} disabled={loading}><RefreshCw/> Atualizar</button></header>{error&&<div className="form-error">{error}</div>}{notice&&<div className="form-success"><CheckCircle2/>{notice}</div>}<div className="messages-workspace"><aside className="panel conversation-list"><label><Search/><input value={query} onChange={event=>setQuery(event.target.value)} placeholder="Buscar paciente"/></label>{loading?<div className="empty-state"><span className="spinner"/></div>:filtered.length?filtered.map(item=><button key={item.patientId} className={selected===item.patientId?'active':''} onClick={()=>setSelected(item.patientId)}><span className="conversation-avatar">{item.patientName.charAt(0)}</span><span><strong>{item.patientName}</strong><small>{clean(item.lastMessage)}</small><time>{new Date(item.lastMessageAt).toLocaleString('pt-BR')}</time></span>{item.unreadCount>0&&<b>{item.unreadCount}</b>}</button>):<div className="empty-state"><MessageCircle/><strong>Nenhuma conversa</strong><p>As mensagens enviadas pelos pacientes aparecerão aqui.</p></div>}</aside><main className="panel professional-thread">{thread?<><header><div className="conversation-avatar">{thread.patient.name.charAt(0)}</div><div><strong>{thread.patient.name}</strong><span>Canal seguro do paciente</span></div></header><div className="thread-history">{thread.messages.map(message=><article className={message.senderRole==='ADMIN'?'mine':''} key={message.id}>{category(message.body)&&<span>{category(message.body)}</span>}<strong>{message.senderRole==='ADMIN'?'Você':'Paciente'}</strong><p>{clean(message.body)}</p><time>{new Date(message.createdAt).toLocaleString('pt-BR')}</time></article>)}</div><form onSubmit={send}><label htmlFor="professional-reply">Responder ao paciente</label><textarea id="professional-reply" name="body" required maxLength={2000} placeholder="Escreva uma orientação ou resposta..."/><button className="primary-button" disabled={sending}><Send/> {sending?'Enviando...':'Enviar resposta'}</button></form></>:<div className="empty-state"><MessageCircle/><strong>Selecione uma conversa</strong></div>}</main></div></section>}
