import { Check, ExternalLink, FileSearch, RefreshCw, Search } from 'lucide-react';
import { useCallback, useEffect, useMemo, useState } from 'react';
import { api } from '../lib/api';

type Exam={id:string;patientId:string;patientName:string;email?:string;title:string;examDate?:string|null;notes?:string|null;status:'SENT'|'REVIEWED';mimeType?:string|null;fileSize?:number|null;createdAt:string;hasFile:boolean};
const date=(value?:string|null)=>value?new Date(`${value.slice(0,10)}T12:00:00`).toLocaleDateString('pt-BR'):'Sem data informada';

export function PatientExamsPage(){const[rows,setRows]=useState<Exam[]>([]);const[filter,setFilter]=useState<'SENT'|'ALL'>('SENT');const[query,setQuery]=useState('');const[loading,setLoading]=useState(true);const[busy,setBusy]=useState('');const[error,setError]=useState('');
 const load=useCallback(async()=>{setLoading(true);setError('');try{const result=await api<{data:Exam[]}>(`/api/patient-exams${filter==='SENT'?'?status=SENT':''}`);setRows(result.data)}catch(c){setError(c instanceof Error?c.message:'Não foi possível carregar os exames.')}finally{setLoading(false)}},[filter]);useEffect(()=>{void load()},[load]);
 const visible=useMemo(()=>rows.filter(item=>`${item.patientName} ${item.title} ${item.email||''}`.toLowerCase().includes(query.toLowerCase())),[rows,query]);
 async function open(id:string){setBusy(id);setError('');try{const result=await api<{data:{url:string}}>(`/api/patient-exams/${id}/url`);window.open(result.data.url,'_blank','noopener,noreferrer')}catch(c){setError(c instanceof Error?c.message:'Não foi possível abrir o arquivo.')}finally{setBusy('')}}
 async function review(id:string){setBusy(id);setError('');try{await api(`/api/patient-exams/${id}/review`,{method:'PATCH'});await load()}catch(c){setError(c instanceof Error?c.message:'Não foi possível revisar o exame.')}finally{setBusy('')}}
 return <section className="exam-center"><header className="exam-center-intro"><div><p>Arquivos enviados pelos pacientes para análise profissional.</p><strong>{rows.filter(row=>row.status==='SENT').length} pendente(s)</strong></div><button className="secondary-button" onClick={()=>void load()} disabled={loading}><RefreshCw/> Atualizar</button></header>{error&&<div className="form-error">{error}</div>}<div className="panel exam-toolbar"><label><Search/><input value={query} onChange={event=>setQuery(event.target.value)} placeholder="Buscar paciente ou exame"/></label><div><button className={filter==='SENT'?'active':''} onClick={()=>setFilter('SENT')}>Pendentes</button><button className={filter==='ALL'?'active':''} onClick={()=>setFilter('ALL')}>Todos</button></div></div><div className="exam-list">{loading?<div className="panel empty-state"><span className="spinner"/></div>:visible.length?visible.map(item=><article className="panel exam-card" key={item.id}><div className="exam-file"><FileSearch/><div><span>{item.status==='SENT'?'Aguardando revisão':'Revisado'}</span><h2>{item.title}</h2><strong>{item.patientName}</strong><small>{date(item.examDate)} · enviado em {new Date(item.createdAt).toLocaleDateString('pt-BR')}</small></div></div>{item.notes&&<p>{item.notes}</p>}<footer><button className="secondary-button" disabled={busy===item.id||!item.hasFile} onClick={()=>void open(item.id)}><ExternalLink/> Abrir arquivo</button>{item.status==='SENT'&&<button className="primary-button" disabled={busy===item.id} onClick={()=>void review(item.id)}><Check/> Marcar revisado</button>}</footer></article>):<div className="panel empty-state"><FileSearch/><strong>Nenhum exame encontrado</strong><p>Os novos envios aparecerão aqui.</p></div>}</div></section>}
