import { ArrowLeft, CheckCircle2, Download, FileWarning, ShieldCheck } from 'lucide-react';
import { useCallback, useEffect, useState, type FormEvent } from 'react';
import { Link } from 'react-router-dom';
import { api } from '../lib/api';
type Notice={notice:{version:string;title:string;summary:string};acknowledged:boolean;acknowledgedAt?:string|null};
type RequestItem={id:string;type:string;details?:string;status:string;resolutionNotes?:string;createdAt:string};
const status:Record<string,string>={OPEN:'Recebida',IN_REVIEW:'Em análise',COMPLETED:'Concluída',REJECTED:'Não atendida',CANCELLED:'Cancelada'};
const type:Record<string,string>={ACCESS:'Acesso',CORRECTION:'Correção',DELETION:'Análise de eliminação',PORTABILITY:'Portabilidade',INFORMATION:'Informações sobre o tratamento',REVOCATION:'Revogação de consentimento',OBJECTION:'Oposição'};
export function PrivacyPage(){
 const[data,setData]=useState<Notice|null>(null);const[requests,setRequests]=useState<RequestItem[]>([]);const[error,setError]=useState('');const[notice,setNotice]=useState('');const[busy,setBusy]=useState(false);
 const loadRequests=useCallback(()=>api<{data:RequestItem[]}>('/api/privacy/my-requests').then(r=>setRequests(r.data)).catch(()=>setRequests([])),[]);
 useEffect(()=>{api<{data:Notice}>('/api/privacy/notice').then(r=>setData(r.data)).catch(c=>setError(c instanceof Error?c.message:'Não foi possível abrir a área de privacidade.'));void loadRequests()},[loadRequests]);
 async function acknowledge(){setBusy(true);try{await api('/api/privacy/acknowledge',{method:'POST'});setData(x=>x?{...x,acknowledged:true,acknowledgedAt:new Date().toISOString()}:x)}finally{setBusy(false)}}
 async function download(){setBusy(true);try{const response=await fetch('/api/privacy/export',{credentials:'include'});if(!response.ok)throw new Error('Não foi possível preparar a exportação.');const blob=await response.blob(),url=URL.createObjectURL(blob),anchor=document.createElement('a');anchor.href=url;anchor.download=`meus-dados-${new Date().toISOString().slice(0,10)}.json`;anchor.click();URL.revokeObjectURL(url)}catch(c){setError(c instanceof Error?c.message:'Falha na exportação.')}finally{setBusy(false)}}
 async function submit(event:FormEvent<HTMLFormElement>){event.preventDefault();setBusy(true);setError('');setNotice('');const form=event.currentTarget,d=new FormData(form);try{await api('/api/privacy/requests',{method:'POST',body:JSON.stringify({type:String(d.get('type')),details:String(d.get('details')||'')})});form.reset();setNotice('Solicitação enviada para análise do consultório.');await loadRequests()}catch(c){setError(c instanceof Error?c.message:'Não foi possível enviar a solicitação.')}finally{setBusy(false)}}
 return <main className="patient-portal privacy-page"><header className="privacy-header"><Link className="ghost-button" to="/portal"><ArrowLeft/> Voltar ao portal</Link><span><ShieldCheck/> Privacidade e seus dados</span></header>{error&&<div className="form-error" role="alert">{error}</div>}{notice&&<div className="form-success" role="status"><CheckCircle2/>{notice}</div>}{data&&<div className="privacy-layout"><section className="panel privacy-notice"><span>Versão {data.notice.version}</span><h1>{data.notice.title}</h1><p>{data.notice.summary}</p>{data.acknowledged?<div className="privacy-ack"><CheckCircle2/> Ciência registrada</div>:<button className="primary-button" onClick={()=>void acknowledge()} disabled={busy}><ShieldCheck/> Li e estou ciente</button>}</section><section className="panel privacy-actions"><h2>Acessar meus dados</h2><p>Baixe uma cópia estruturada dos dados mantidos no portal.</p><button className="secondary-button" onClick={()=>void download()} disabled={busy}><Download/> Baixar meus dados</button></section><form className="panel privacy-request" onSubmit={submit}><div className="privacy-request-intro"><FileWarning/><div><h2>Solicitar análise</h2><p>Pedidos são avaliados conforme as obrigações de conservação do prontuário.</p></div></div><label>Direito que deseja exercer<select name="type" required><option value="ACCESS">Acessar meus dados</option><option value="CORRECTION">Corrigir dados incompletos ou incorretos</option><option value="INFORMATION">Saber como meus dados são usados e compartilhados</option><option value="PORTABILITY">Solicitar portabilidade, quando aplicável</option><option value="DELETION">Solicitar análise de anonimização, bloqueio ou eliminação</option><option value="REVOCATION">Revogar um consentimento específico</option><option value="OBJECTION">Registrar oposição a um tratamento</option></select></label><label>Explique sua solicitação<textarea name="details" maxLength={2000} required placeholder="Inclua somente as informações necessárias para identificarmos e analisarmos o pedido."/></label><button className="primary-button" disabled={busy}>Enviar solicitação</button></form><section className="panel privacy-history"><h2>Minhas solicitações</h2>{requests.length?requests.map(item=><article key={item.id}><div><strong>{type[item.type]||item.type}</strong><span>{new Date(item.createdAt).toLocaleDateString('pt-BR')}</span></div><b>{status[item.status]||item.status}</b><p>{item.resolutionNotes||item.details||'Aguardando retorno do consultório.'}</p></article>):<p className="muted">Nenhuma solicitação enviada.</p>}</section></div>}</main>
}
