import type { NutritionalLamina } from './nutritionalLaminas';

const item=(id:string,title:string,category:NutritionalLamina['category'],categoryLabel:string,summary:string,icon:string,tips:string[]):NutritionalLamina=>({id,title,category,categoryLabel,summary,icon,tips});

export const EXPANDED_NUTRITIONAL_LAMINAS:NutritionalLamina[]=[
 item('grupos-alimentares','Conhecendo os Grupos Alimentares','PRATICA','Educação Alimentar','Reconheça a função dos principais grupos e combine variedade ao longo do dia.','Salad',['Proteínas contribuem para manutenção e reparo dos tecidos.','Carboidratos são fontes importantes de energia.','Frutas, verduras e legumes oferecem fibras e micronutrientes.','Leites, leguminosas, gorduras e temperos têm papéis distintos no plano individual.']),
 item('pratos-saudaveis-semana','Ideias de Pratos Saudáveis para a Semana','PRATICA','Alimentação Prática','Combinações simples para variar as refeições sem perder o equilíbrio.','Salad',['Combine proteína, cereal ou tubérculo, leguminosa e vegetais.','Varie cores e modos de preparo durante a semana.','Use sobras seguras em novas combinações.','Ajuste quantidades ao plano e aos sinais de fome e saciedade.']),
 item('lanches-saudaveis-semana','Ideias de Lanches para a Semana','PRATICA','Alimentação Prática','Sugestões de combinações práticas com fibras, proteínas e alimentos in natura.','Boxes',['Fruta com iogurte natural e aveia.','Pão integral com ovo ou pasta de leguminosas.','Iogurte com fruta e sementes.','Escolha o lanche conforme rotina, fome e necessidades individuais.']),
 item('ervas-especiarias','Ervas e Especiarias na Cozinha','PRATICA','Culinária Saudável','Use aromas e sabores naturais para variar preparações e reduzir temperos ultraprocessados.','Sparkles',['Orégano e manjericão combinam com molhos, legumes e ovos.','Cúrcuma, páprica e cominho ampliam sabor e cor.','Alecrim e tomilho funcionam bem em assados.','A quantidade deve respeitar tolerância, preferência e condições clínicas.']),
 item('legumes-verduras','Como Incluir Mais Legumes e Verduras','PRATICA','Alimentação Prática','Estratégias graduais para aumentar variedade, aceitação e frequência.','Salad',['Comece com pequenas porções e alimentos já conhecidos.','Teste assados, refogados, sopas, molhos e preparações cruas.','Inclua cores diferentes ao longo da semana.','Repetir a exposição ajuda a construir familiaridade com novos sabores.']),
 item('cafe-manha-equilibrado','Como Montar um Café da Manhã Equilibrado','PRATICA','Alimentação Prática','Combine energia, proteína, fibras e gorduras conforme sua rotina matinal.','Boxes',['Escolha uma fonte de carboidrato, como pão, aveia, fruta ou raiz.','Inclua proteína com ovos, iogurte, queijo ou opção vegetal.','Acrescente fruta, sementes ou oleaginosas quando apropriado.','Não existe combinação única: respeite preferências e orientação individual.']),
 item('frutas-acompanhamentos','Acompanhamentos para Comer com Frutas','PRATICA','Alimentação Prática','Ideias para transformar frutas em refeições ou lanches mais completos.','Salad',['Iogurte natural acrescenta proteína e cremosidade.','Aveia, chia e linhaça contribuem com fibras.','Castanhas e pastas de oleaginosas aumentam densidade energética.','Granola e mel pedem atenção à porção e ao teor de açúcar.']),
 item('alimentos-estacao','Frutas, Legumes e Verduras da Estação','PRATICA','Planejamento Alimentar','Aproveite sazonalidade para variar sabores, disponibilidade e custo.','Leaf',['Observe a oferta regional, pois a sazonalidade varia pelo país.','Alimentos da estação costumam ter melhor preço e qualidade.','Alterne cores e famílias vegetais.','Congelar alimentos adequadamente pode ajudar a reduzir desperdício.']),
 item('anti-inflamatorios','Padrão Alimentar Anti-inflamatório','PRATICA','Nutrição Funcional','Priorize um conjunto de hábitos alimentares associado à saúde metabólica.','HeartPulse',['Baseie a rotina em alimentos in natura e minimamente processados.','Inclua vegetais, frutas, leguminosas, cereais integrais e gorduras insaturadas.','Reduza ultraprocessados, excesso de açúcar, álcool e gorduras trans.','Nenhum alimento isolado trata inflamação; o padrão global é o mais importante.']),
 item('molhos-saudaveis','Molhos Caseiros para Saladas','PRATICA','Culinária Saudável','Prepare molhos simples e ajuste sabor, gordura e sódio conscientemente.','Sparkles',['Iogurte natural, limão e ervas formam uma base cremosa.','Azeite, mostarda e limão criam uma emulsão rápida.','Frutas cítricas podem trazer acidez e aroma.','Prepare pequenas quantidades e mantenha refrigerado em recipiente limpo.']),
 item('tipos-acucares','Tipos de Açúcares: O que Realmente Muda','ROTULOS','Educação Alimentar','Compare diferentes açúcares sem confundir origem ou cor com consumo livre.','Tags',['Mascavo, demerara, cristal e refinado continuam sendo açúcares livres.','Pequenas diferenças de micronutrientes não anulam o impacto da quantidade.','Açúcar de coco, mel e xaropes também devem ser moderados.','Observe açúcares adicionados no rótulo e a frequência de consumo.']),
 item('deficit-calorico','Déficit Calórico com Segurança','COMPORTAMENTO','Emagrecimento','Entenda a redução energética planejada sem dietas extremas ou compensações.','Scale',['O déficit deve ser individualizado e compatível com saúde e rotina.','Proteínas, fibras e volume alimentar ajudam na saciedade.','Restrições excessivas podem aumentar fome, fadiga e perda de adesão.','Peso é apenas um indicador; composição corporal e bem-estar também importam.']),
 item('bebidas-alcoolicas','Bebidas Alcoólicas e Consumo Consciente','ROTULOS','Escolhas Conscientes','Entenda que álcool fornece energia e pode afetar sono, apetite e decisões alimentares.','Tags',['A quantidade de álcool e o tamanho da dose mudam o valor energético.','Drinks com xaropes, açúcar e cremes concentram mais calorias.','Intercale com água e evite beber em jejum.','Para algumas pessoas e condições clínicas, a recomendação é não consumir.']),
 item('bebidas-baixa-caloria','Escolhas de Bebidas no Emagrecimento','SUBSTITUICAO','Escolhas Conscientes','Compare opções sem transformar bebidas zero em obrigação ou solução isolada.','Repeat',['Água continua sendo a principal bebida de hidratação.','Café e chá sem açúcar podem compor a rotina conforme tolerância.','Bebidas zero podem ser transição, mas não substituem água ou alimentação adequada.','Álcool, sucos e bebidas adoçadas devem entrar no planejamento individual.']),
 item('azeites-cozinha','Como Escolher Azeite para Cozinhar','ROTULOS','Culinária Saudável','Entenda tipos, armazenamento e uso culinário do azeite.','Tags',['Azeite extravirgem pode ser usado em preparações frias e culinária doméstica.','Guarde longe de luz, calor e ar, com a embalagem bem fechada.','Observe origem, validade e integridade da embalagem.','Evite reutilizar óleo e não deixe qualquer gordura queimar.']),
 item('pre-treino','O que Comer Antes do Treino','PRATICA','Nutrição Esportiva','Organize a refeição pré-treino conforme horário, intensidade e tolerância digestiva.','Zap',['Quanto mais perto do treino, mais simples e fácil de digerir deve ser a refeição.','Carboidratos podem apoiar disponibilidade de energia.','Proteína pode ser incluída conforme intervalo e objetivo.','Teste estratégias durante treinos, nunca apenas no dia de competição.']),
 item('constipacao-intestinal','Estratégias para Constipação Intestinal','PRATICA','Saúde Intestinal','Apoie o trânsito intestinal com fibras, líquidos, rotina e avaliação dos sintomas.','Boxes',['Aumente fibras gradualmente com frutas, verduras, leguminosas e integrais.','Associe fibras a ingestão hídrica adequada.','Movimento e horário tranquilo para evacuar podem ajudar.','Dor intensa, sangue, perda de peso ou mudança persistente exigem avaliação.']),
 item('porcoes-maos','Porções com Medidas das Mãos','PRATICA','Educação Alimentar','Use a mão como referência prática quando balança e utensílios não estiverem disponíveis.','Scale',['A palma pode estimar uma porção de proteína.','O punho pode servir de referência para alguns carboidratos.','Mãos em concha ajudam a visualizar vegetais e frutas.','É uma estimativa, não substitui a prescrição individual quando necessária.']),
 item('whey-protein','Whey Protein: Tipos e Uso','ROTULOS','Suplementação','Conheça diferenças gerais e quando um suplemento proteico pode ser útil.','Tags',['Concentrado, isolado e hidrolisado diferem em processamento e composição.','A escolha depende de tolerância, objetivo, custo e alimentação habitual.','Whey não é obrigatório para ganhar massa muscular.','Dose e uso devem considerar proteína total, saúde renal e orientação profissional.']),
 item('superavit-calorico','Superávit Calórico Planejado','PRATICA','Ganho de Peso','Entenda o aumento energético gradual para ganho de peso ou massa corporal.','Scale',['O excedente deve ser moderado e acompanhado ao longo do tempo.','Distribua energia em refeições e lanches que sejam bem tolerados.','Priorize alimentos nutritivos e fontes adequadas de proteína.','Treino, sono e progressão individual influenciam o resultado.']),
 item('ganho-peso-saudavel','Estratégias para Ganho de Peso Saudável','PRATICA','Ganho de Peso','Aumente densidade energética sem depender apenas de ultraprocessados.','HeartPulse',['Acrescente azeite, abacate, castanhas e pastas de oleaginosas.','Use vitaminas, iogurtes e lanches quando grandes volumes forem difíceis.','Inclua carboidratos e proteínas nas principais refeições.','Perda de peso involuntária ou falta de apetite persistente requer investigação.']),
 item('equilibrio-fim-semana','Como Equilibrar o Fim de Semana','COMPORTAMENTO','Comportamento Alimentar','Mantenha flexibilidade sem alternar restrição rígida e exagero.','Brain',['Preserve refeições básicas e hidratação ao longo do dia.','Escolha experiências alimentares importantes sem tentar compensar depois.','Coma com atenção aos sinais de satisfação.','Retome a rotina na refeição seguinte, sem culpa ou punição.']),
 item('erros-emagrecimento','Erros Comuns que Dificultam o Emagrecimento','COMPORTAMENTO','Emagrecimento','Reconheça padrões que prejudicam adesão, recuperação e consistência.','Brain',['Dormir pouco pode afetar apetite, disposição e planejamento.','Restringir demais aumenta o risco de fome intensa e desistência.','Pouca proteína, fibras e água pode reduzir saciedade.','Resultados sustentáveis dependem de hábitos, não de promessas rápidas.']),
 item('refeicao-livre','Como Funciona uma Refeição Flexível','COMPORTAMENTO','Comportamento Alimentar','Inclua escolhas prazerosas sem transformar a refeição em prêmio ou descontrole.','Smile',['Planeje uma refeição, não um dia inteiro de excessos.','Escolha o que realmente deseja e coma sem pressa.','Observe saciedade e evite compensações antes ou depois.','Flexibilidade bem planejada faz parte de uma relação saudável com a comida.']),
 item('medidas-caseiras','Entendendo Medidas Caseiras','PRATICA','Educação Alimentar','Use copos, xícaras e colheres de forma consistente para seguir o plano.','Scale',['Colheres e xícaras variam; use o utensílio indicado no plano.','Nivele ingredientes secos quando a medida pedir uma colher rasa.','Observe se a orientação descreve alimento cru, cozido, cheio ou picado.','Na dúvida, compare uma vez com balança para conhecer seu utensílio.']),
 item('pao-tapioca','Pão ou Tapioca: Como Escolher','SUBSTITUICAO','Escolhas Conscientes','Compare opções pelo contexto completo, não apenas pelas calorias.','Repeat',['Ambos fornecem principalmente carboidratos e a porção faz diferença.','Pães integrais podem oferecer mais fibras, conforme a composição.','Tapioca pode receber recheios com proteína e vegetais.','A melhor escolha depende de preferência, tolerância, objetivo e combinação.']),
];
