import { api } from './api';
export type TenantStatus='DRAFT'|'READY'|'PROVISIONING'|'ACTIVE'|'SUSPENDED'|'FAILED'|'ARCHIVED';
export type JobStatus='PENDING'|'RUNNING'|'SUCCEEDED'|'FAILED'; export type JobOperation='PROVISION_TENANT'|'REPAIR_TENANT';
export type TenantSummary={id:string;slug:string;displayName:string;contactEmail:string;status:TenantStatus;plan:string;region:string;appVersion:string|null;health:'healthy'|'attention'|'unknown';createdAt:string;updatedAt:string};
export type ProvisioningJob={id:string;tenantId:string;operation:JobOperation;status:JobStatus;attemptCount:number;availableAt:string;startedAt:string|null;completedAt:string|null;createdAt:string;resultSummary:{message?:string;checks?:string[]}};
export type TenantDetail=TenantSummary&{jobs:ProvisioningJob[]}; export type CreateTenantInput={slug:string;name:string;contactEmail:string}; export type QueueJobInput={operation:JobOperation;databaseRegion?:string;hostingRegion?:string};
export interface PlatformApiClient{listTenants(signal?:AbortSignal):Promise<TenantSummary[]>;getTenant(id:string,signal?:AbortSignal):Promise<TenantDetail>;createTenant(input:CreateTenantInput):Promise<{id:string;status:TenantStatus}>;queueJob(id:string,input:QueueJobInput):Promise<{id:string;status:JobStatus}>;startJob(id:string):Promise<void>;completeJob(id:string,outcome:'SUCCEEDED'|'FAILED',message?:string):Promise<void>}
type ApiTenant={id:string;slug:string;name:string;contactEmail:string;status:TenantStatus;createdAt:string;updatedAt:string}; type ApiJob={id:string;tenantId:string;operation:JobOperation;status:JobStatus;attemptCount:number;availableAt:string;startedAt:string|null;completedAt:string|null;createdAt:string;resultSummary?:{message?:string;checks?:string[]}};
const key=(prefix:string)=>`${prefix}:${Date.now()}:${crypto.randomUUID()}`; const mapTenant=(x:ApiTenant):TenantSummary=>({...x,displayName:x.name,plan:'A definir',region:'A definir',appVersion:null,health:x.status==='FAILED'?'attention':x.status==='ACTIVE'?'healthy':'unknown'});
export const remotePlatformApi:PlatformApiClient={
 async listTenants(signal){return(await api<{data:ApiTenant[]}>('/api/platform/tenants',{signal})).data.map(mapTenant)},
 async getTenant(id,signal){const[t,j]=await Promise.all([api<{data:ApiTenant[]}>('/api/platform/tenants',{signal}),api<{data:ApiJob[]}>('/api/platform/jobs',{signal})]);const tenant=t.data.find(x=>x.id===id);if(!tenant)throw new Error('Tenant não encontrado.');return{...mapTenant(tenant),jobs:j.data.filter(x=>x.tenantId===id).map(x=>({...x,resultSummary:x.resultSummary??{}}))}},
 async createTenant(input){return(await api<{data:{id:string;status:TenantStatus}}>('/api/platform/tenants',{method:'POST',body:JSON.stringify({...input,idempotencyKey:key('tenant:create')})})).data},
 async queueJob(id,input){const{operation,...request}=input;return(await api<{data:{id:string;status:JobStatus}}>(`/api/platform/tenants/${id}/jobs`,{method:'POST',body:JSON.stringify({operation,request,idempotencyKey:key('job:create')})})).data},
 async startJob(id){await api(`/api/platform/jobs/${id}/start`,{method:'POST'})},async completeJob(id,outcome,message){await api(`/api/platform/jobs/${id}/complete`,{method:'POST',body:JSON.stringify({outcome,summary:message?{message}:{}})})}
};
const now='2026-08-27T13:42:00Z';let mockTenants:TenantSummary[]=[{id:'tenant-aurora',slug:'clinica-aurora-a19c',displayName:'Clínica Aurora',contactEmail:'marina@example.test',status:'ACTIVE',plan:'Profissional',region:'São Paulo',appVersion:'1.0.0',health:'healthy',createdAt:now,updatedAt:now},{id:'tenant-horizonte',slug:'nutri-horizonte-75fe',displayName:'Nutri Horizonte',contactEmail:'paula@example.test',status:'PROVISIONING',plan:'Essencial',region:'São Paulo',appVersion:null,health:'unknown',createdAt:now,updatedAt:now}];let mockJobs:ProvisioningJob[]=[{id:'job-a2',tenantId:'tenant-aurora',operation:'PROVISION_TENANT',status:'SUCCEEDED',attemptCount:1,availableAt:now,startedAt:now,completedAt:now,createdAt:now,resultSummary:{message:'Release validada e promovida.'}}];const wait=()=>new Promise<void>(r=>window.setTimeout(r,180));const mode=()=>new URLSearchParams(location.search).get('mockState');
export const localPlatformApi:PlatformApiClient={async listTenants(){await wait();if(mode()==='error')throw new Error('A central local não respondeu. Tente novamente.');return mode()==='empty'?[]:mockTenants},async getTenant(id){await wait();if(mode()==='error')throw new Error('Não foi possível carregar este tenant.');const t=mockTenants.find(x=>x.id===id);if(!t)throw new Error('Tenant não encontrado.');return{...t,jobs:mockJobs.filter(x=>x.tenantId===id)}},async createTenant(input){await wait();const t:TenantSummary={id:crypto.randomUUID(),slug:input.slug,displayName:input.name,contactEmail:input.contactEmail,status:'DRAFT',plan:'A definir',region:'A definir',appVersion:null,health:'unknown',createdAt:new Date().toISOString(),updatedAt:new Date().toISOString()};mockTenants=[t,...mockTenants];return{id:t.id,status:t.status}},async queueJob(tenantId,input){const j:ProvisioningJob={id:crypto.randomUUID(),tenantId,operation:input.operation,status:'PENDING',attemptCount:0,availableAt:new Date().toISOString(),startedAt:null,completedAt:null,createdAt:new Date().toISOString(),resultSummary:{}};mockJobs=[j,...mockJobs];return{id:j.id,status:j.status}},async startJob(id){const j=mockJobs.find(x=>x.id===id);if(!j||j.status!=='PENDING')throw new Error('Job indisponível.');j.status='RUNNING';j.startedAt=new Date().toISOString();j.attemptCount++},async completeJob(id,outcome,message){const j=mockJobs.find(x=>x.id===id);if(!j||j.status!=='RUNNING')throw new Error('Job fora do estado RUNNING.');j.status=outcome;j.completedAt=new Date().toISOString();j.resultSummary={message}}};
export const platformApi:PlatformApiClient=import.meta.env.DEV&&import.meta.env.VITE_PLATFORM_USE_MOCK==='true'?localPlatformApi:remotePlatformApi;
