import{api,ApiError}from'./api';
export type OnboardingStep='CLINIC'|'VERCEL'|'SUPABASE'|'IDENTITY'|'REVIEW'|'PUBLISH';export type StepState='LOCKED'|'PENDING'|'IN_PROGRESS'|'COMPLETED'|'FAILED'|'UNAVAILABLE';
export type Activity={id:string;label:string;status:'PENDING'|'RUNNING'|'SUCCEEDED'|'FAILED'|'ROLLED_BACK';detail:string};
export type OnboardingState={tenantId:string;currentStep:OnboardingStep;overallProgress:number;steps:Record<OnboardingStep,StepState>;configured:boolean;message?:string;clinic:{name:string;contactEmail:string};vercel:{projectName:string;connected:boolean};supabase:{projectRef:string;region:string;verified:boolean};identity:{brandName:string;primaryColor:string;ownerEmail:string};publication:{status:'IDLE'|'RUNNING'|'FAILED'|'READY'|'ROLLED_BACK';url?:string;message?:string;failedStage?:string};activity:Activity[]};
export type StepPayload={CLINIC:{name:string;contactEmail:string};VERCEL:{projectName:string};SUPABASE:{projectRef:string;region:string};IDENTITY:{brandName:string;primaryColor:string;ownerEmail:string};REVIEW:Record<string,never>;PUBLISH:Record<string,never>};
export type InitializeOnboardingInput={clinicName:string;professionalName:string;contactEmail:string;ownerName:string;ownerEmail:string};
export interface PlatformOnboardingApi{get(id:string,signal?:AbortSignal):Promise<OnboardingState>;initialize(id:string,input:InitializeOnboardingInput):Promise<void>;save<K extends OnboardingStep>(id:string,step:K,payload:StepPayload[K]):Promise<OnboardingState>;publish(id:string):Promise<OnboardingState>;retry(id:string):Promise<OnboardingState>;rollback(id:string):Promise<OnboardingState>}
const emptyActivity=():Activity[]=>['Preparar configuração','Validar artefato assinado','Resolver referências seguras','Criar preview fake','Executar smoke fake'].map((label,index)=>({id:['prepare','artifact','environment','preview','smoke'][index]!,label,status:'PENDING',detail:'Aguardando etapa anterior.'}));
const closed=(id:string):OnboardingState=>({tenantId:id,currentStep:'CLINIC',overallProgress:0,configured:false,message:'O orquestrador de onboarding não está configurado neste ambiente. Nenhum recurso externo será alterado.',steps:{CLINIC:'UNAVAILABLE',VERCEL:'LOCKED',SUPABASE:'LOCKED',IDENTITY:'LOCKED',REVIEW:'LOCKED',PUBLISH:'LOCKED'},clinic:{name:'',contactEmail:''},vercel:{projectName:'',connected:false},supabase:{projectRef:'',region:'sa-east-1',verified:false},identity:{brandName:'',primaryColor:'#183b2b',ownerEmail:''},publication:{status:'IDLE'},activity:emptyActivity()});
export const remoteOnboardingApi:PlatformOnboardingApi={async get(id,signal){try{return(await api<{data:OnboardingState}>(`/api/platform/tenants/${id}/onboarding`,{signal})).data}catch(e){if(e instanceof ApiError&&[404,501,503].includes(e.status))return closed(id);throw e}},async initialize(id,input){await api(`/api/platform/tenants/${id}/onboarding`,{method:'POST',body:JSON.stringify({...input,inviteExpiresInHours:48,idempotencyKey:`onboarding:${id}:${crypto.randomUUID()}`})})},async save(id,step,payload){return(await api<{data:OnboardingState}>(`/api/platform/tenants/${id}/onboarding/steps/${step.toLowerCase()}`,{method:'PUT',body:JSON.stringify(payload)})).data},async publish(id){return(await api<{data:OnboardingState}>(`/api/platform/tenants/${id}/onboarding/publish`,{method:'POST'})).data},async retry(id){return(await api<{data:OnboardingState}>(`/api/platform/tenants/${id}/onboarding/retry`,{method:'POST'})).data},async rollback(id){return(await api<{data:OnboardingState}>(`/api/platform/tenants/${id}/onboarding/rollback`,{method:'POST'})).data}};
const order:OnboardingStep[]=['CLINIC','VERCEL','SUPABASE','IDENTITY','REVIEW','PUBLISH'],stores=new Map<string,OnboardingState>(),failedOnce=new Set<string>(),wait=(ms=120)=>new Promise<void>(resolve=>setTimeout(resolve,ms));
const init=(id:string):OnboardingState=>({tenantId:id,currentStep:'CLINIC',overallProgress:0,configured:true,steps:{CLINIC:'IN_PROGRESS',VERCEL:'LOCKED',SUPABASE:'LOCKED',IDENTITY:'LOCKED',REVIEW:'LOCKED',PUBLISH:'LOCKED'},clinic:{name:'Clínica Aurora',contactEmail:'owner@example.test'},vercel:{projectName:'',connected:false},supabase:{projectRef:'',region:'sa-east-1',verified:false},identity:{brandName:'',primaryColor:'#183b2b',ownerEmail:'owner@example.test'},publication:{status:'IDLE'},activity:emptyActivity()});
const current=(id:string)=>{let state=stores.get(id);if(!state){state=init(id);stores.set(id,state)}return state},snapshot=(state:OnboardingState):OnboardingState=>structuredClone(state);
const advance=(state:OnboardingState,step:OnboardingStep)=>{const index=order.indexOf(step),next=order[Math.min(index+1,order.length-1)]!;state.steps[step]='COMPLETED';state.steps[next]='IN_PROGRESS';state.currentStep=next;state.overallProgress=Math.round(((index+1)/order.length)*100);return snapshot(state)};
async function simulate(id:string){const state=current(id),failure=new URLSearchParams(location.search).get('mockOnboardingFailure');state.publication={status:'RUNNING',message:'Executando uma simulação integral, sem chamadas externas.'};state.steps.PUBLISH='IN_PROGRESS';for(let index=0;index<state.activity.length;index++){const item=state.activity[index]!;if(item.status==='SUCCEEDED')continue;item.status='RUNNING';item.detail='Verificação fake em andamento…';state.overallProgress=84+index*3;await wait();if(failure===item.id&&!failedOnce.has(`${id}:${item.id}`)){failedOnce.add(`${id}:${item.id}`);item.status='FAILED';item.detail='Falha sintética controlada. Nenhum recurso externo foi alterado.';state.steps.PUBLISH='FAILED';state.publication={status:'FAILED',failedStage:item.id,message:`A etapa “${item.label}” falhou com segurança. Corrija e retome do mesmo ponto.`};return snapshot(state)}item.status='SUCCEEDED';item.detail=item.id==='preview'?'Preview fake criado sem rede.':'Gate sintético aprovado.'}state.publication={status:'READY',url:'https://clinica-exemplo-staging.vercel.app',message:'Preview e smoke simulados foram aprovados. Promoção continua desativada.'};state.steps.PUBLISH='COMPLETED';state.overallProgress=100;return snapshot(state)}
export const localOnboardingApi:PlatformOnboardingApi={async get(id){await wait();return snapshot(current(id))},async initialize(id,input){const state=init(id);state.clinic={name:input.clinicName,contactEmail:input.contactEmail};state.identity.ownerEmail=input.ownerEmail;stores.set(id,state);await wait()},async save(id,step,payload){const state=current(id);if(step==='CLINIC')state.clinic=payload as StepPayload['CLINIC'];if(step==='VERCEL')state.vercel={projectName:(payload as StepPayload['VERCEL']).projectName,connected:true};if(step==='SUPABASE')state.supabase={...(payload as StepPayload['SUPABASE']),verified:true};if(step==='IDENTITY')state.identity=payload as StepPayload['IDENTITY'];return advance(state,step)},async publish(id){return simulate(id)},async retry(id){const state=current(id);if(state.publication.status!=='FAILED')throw new Error('Não existe falha recuperável.');const failed=state.activity.find(item=>item.status==='FAILED');if(failed){failed.status='PENDING';failed.detail='Pronto para nova tentativa.'}state.steps.PUBLISH='IN_PROGRESS';state.publication={status:'IDLE',message:'Falha reconciliada. Retome a simulação.'};return simulate(id)},async rollback(id){const state=current(id);if(!['READY','FAILED'].includes(state.publication.status))throw new Error('Rollback indisponível neste estado.');for(const item of state.activity){if(item.id==='preview'||item.id==='smoke'){item.status='ROLLED_BACK';item.detail='Efeito fake revertido; dados preservados.'}}state.publication={status:'ROLLED_BACK',message:'Preview fake revertido. Banco e configuração foram preservados.'};state.steps.PUBLISH='IN_PROGRESS';state.overallProgress=83;return snapshot(state)}};
export const platformOnboardingApi=import.meta.env.DEV&&import.meta.env.VITE_PLATFORM_USE_MOCK==='true'?localOnboardingApi:remoteOnboardingApi;
