import type { FastifyInstance } from 'fastify';
import { z } from 'zod';
import { audit } from '../../shared/audit.js';

export async function patientAppointmentRoutes(app:FastifyInstance){
  app.addHook('preHandler',app.authenticate);
  app.addHook('preHandler',async(request,reply)=>{if(request.auth?.role!=='PATIENT'||!request.auth.patientId)return reply.code(403).send({error:'Acesso restrito ao paciente.'})});
  app.get('/',async request=>{const result=await app.db.query(`SELECT id,to_char(appointment_date,'YYYY-MM-DD') AS date,to_char(appointment_time,'HH24:MI') AS time,duration_minutes AS "durationMinutes",appointment_type AS type,status,patient_response AS "patientResponse",patient_response_at AS "patientResponseAt",patient_response_note AS "patientResponseNote" FROM appointments WHERE patient_id=$1 AND appointment_date>=current_date AND status IN('CONFIRMED','WAITING') ORDER BY appointment_date,appointment_time LIMIT 30`,[request.auth!.patientId]);return{data:result.rows}});
  app.post('/:id/response',async(request,reply)=>{const{id}=z.object({id:z.uuid()}).parse(request.params);const body=z.object({response:z.enum(['CONFIRMED','RESCHEDULE_REQUESTED']),note:z.string().trim().max(500).optional()}).parse(request.body);if(body.response==='RESCHEDULE_REQUESTED'&&!body.note)return reply.code(400).send({error:'Informe uma observação para o reagendamento.'});const result=await app.db.query<{appointment_date:Date;appointment_time:string;patient_name:string}>(`UPDATE appointments a SET patient_response=$1,patient_response_at=now(),patient_response_note=$2,status=CASE WHEN $1='CONFIRMED' AND status='WAITING' THEN 'CONFIRMED' ELSE status END,updated_at=now() FROM patients p WHERE a.id=$3 AND a.patient_id=$4 AND a.patient_id=p.id AND a.appointment_date>=current_date AND a.status IN('CONFIRMED','WAITING') RETURNING a.appointment_date,a.appointment_time,p.name AS patient_name`,[body.response,body.note||null,id,request.auth!.patientId]);if(!result.rows[0])return reply.code(404).send({error:'Consulta disponível para confirmação não encontrada.'});await app.db.query(`INSERT INTO patient_notifications(patient_id,title,body,kind,priority,entity_type,entity_id,action_url,dedupe_key,expires_at) VALUES($1,$2,$3,'APPOINTMENT','LOW','appointment',$4,'/portal/consultas','appointment:response:'||$4||':'||$5,now()+interval '30 days') ON CONFLICT(patient_id,dedupe_key) WHERE dedupe_key IS NOT NULL AND status='ACTIVE' DO NOTHING`,[request.auth!.patientId,body.response==='CONFIRMED'?'Presença confirmada':'Reagendamento solicitado',body.response==='CONFIRMED'?'Sua confirmação foi registrada.':'O consultório recebeu seu pedido e entrará em contato.',id,body.response]);if(body.response==='RESCHEDULE_REQUESTED'){await app.db.query(`INSERT INTO professional_notifications(kind,title,body,priority,entity_type,entity_id,action_url,dedupe_key) VALUES('APPOINTMENT_REQUEST','Reagendamento solicitado',$2,'HIGH','appointment',$1,'/agenda','appointment-reschedule:'||$1) ON CONFLICT(dedupe_key) DO UPDATE SET title=EXCLUDED.title,body=EXCLUDED.body,status='ACTIVE',read_at=NULL,resolved_at=NULL,archived_at=NULL,updated_at=now()`,[id,`${result.rows[0].patient_name} solicitou um novo horário. ${body.note}`])}else{await app.db.query(`UPDATE professional_notifications SET status='RESOLVED',resolved_at=COALESCE(resolved_at,now()),read_at=COALESCE(read_at,now()),updated_at=now() WHERE dedupe_key='appointment-reschedule:'||$1 AND status='ACTIVE'`,[id])}await audit(app.db,'PATIENT_APPOINTMENT_RESPONSE','appointment',{actorUserId:request.auth!.userId,entityId:id,metadata:{response:body.response}});return{message:body.response==='CONFIRMED'?'Presença confirmada.':'Pedido de reagendamento enviado.'}})
}
